### PR TITLE
[RemoteCachingService] Expose a `RemoteCacheProvider` interface and pass it to `RemoteCacheServer`

### PR DESCRIPTION
**Pull request by akyrtzi**
This creates separation of concerns between `RemoteCacheServer` and a `RemoteCacheProvider`, allowing `RemoteCacheServer` to be combined with different `RemoteCacheProvider` implementations.

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
Could I get a review? 🙏

**Review by cachemeifyoucan — APPROVED** [review]
LGTM

**Pull request merged**
