### PR TITLE
Missing cherry picks 6.1

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by felipepiovezan** [comment]
We should not cherry-pick [[lldb][test] Renable tests on asan builds](https://github.com/swiftlang/llvm-project/pull/9691/commits/faf91a2b7d855b9f6d37657a0ff66572905067f5), this has been reverted on the stable branch already

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by JDevlieghere — APPROVED** [review]
LGTM

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
