### PR TITLE
Fixup SwiftASTContext for lldb for LLVM upstream inclusiveness changes.

### PR DESCRIPTION
**Pull request by plotfi**
Also, a fix for StringRef -> std::string conversion.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @adrian-prantl @JDevlieghere

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @davezarzycki

**Review by adrian-prantl — APPROVED** [review]

**Comment by compnerd** [comment]
The Linux failure seems unrelated, going to merge this as it passes of MacOS.

**Pull request merged**
