### PR TITLE
[DebugInfo] Remove spare bits mask from LLVM IR and DWARF

### PR DESCRIPTION
**Pull request by augusto2112**
We are able to calculate the spare bits mask from other information. Remove this from the LLVM  IR representation and DWARF.

### CODE REVIEW

**Comment by augusto2112** [comment]
https://github.com/swiftlang/swift/pull/77176
@swift-ci test

**Comment by augusto2112** [comment]
https://github.com/swiftlang/swift/pull/77176
@swift-ci test

**Comment by augusto2112** [comment]
https://github.com/swiftlang/swift/pull/77176
@swift-ci test

**Comment by augusto2112** [comment]
https://github.com/swiftlang/swift/pull/77176
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]
Looks good, but can you add a test that shows we can "upgrade" the old format by ignoring the attribute?

**Comment by augusto2112** [comment]
https://github.com/swiftlang/swift/pull/77176
@swift-ci test

**Pull request merged**
