### PR TITLE
Fix -Wdocumentation warning. NFCI.

### PR DESCRIPTION
**Pull request by JDevlieghere**
llvm-svn: 372418
(cherry picked from commit 60a6f31dde488e28afab0dc39697e645d0653e2e)

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Review by cyndyishida — APPROVED** [review]

**Comment by cyndyishida** [comment]
Since the update-checkout script doesn't call this dated branch anywhere, how do you check if the PR test failure is because of a dirty baseline, check that swift/master is a reflection and check those CI jobs?

**Comment by JDevlieghere** [comment]
I don't think PR testing is using update-checkout at all. @shahmishal knows the details.

The linux failure is definitely because of a dirty baseline, which is why Linux testing in temporarily *not* required. When that's fixed you should always (in theory) be able to rely on a clean baseline. However, in practice, flakiness or configuration errors mean that it is possible to end up with a dirty baseline. When I'm suspicious I usually check a few subsequent PR-test runs and see if there's a pattern.

**Comment by shahmishal** [comment]
> I don't think PR testing is using update-checkout at all. @shahmishal knows the details.
> 
> The linux failure is definitely because of a dirty baseline, which is why Linux testing in temporarily _not_ required. When that's fixed you should always (in theory) be able to rely on a clean baseline. However, in practice, flakiness or configuration errors mean that it is possible to end up with a dirty baseline. When I'm suspicious I usually check a few subsequent PR-test runs and see if there's a pattern.

it's not using update-checkout because for `apple/*` branches don't get tested for swift changes. 

Job it self is checking out the PR branch `git rev-parse refs/remotes/origin/origin/pr/213/merge^{commit} # timeout=10`

**Comment by shahmishal** [comment]
https://github.com/apple/llvm-project/pull/1#issuecomment-550179677 I was seeing this failure yesterday when I created Linux PR testing for LLVM Project. (cc: @hyp)

**Comment by shahmishal** [comment]
@swift-ci clean test Linux

**Pull request merged**
