### PR TITLE
[Index] Add a SymbolKind::Concept -> indexstore_symbol_kind_t conversion

### PR DESCRIPTION
**Pull request by bnbarham**

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@akyrtzi I believe in a previous PR you've mentioned that you'd prefer `SymbolKind` to be more generic/language independent + `SymbolSubKind` for more specific types. I imagine this could be the case for this one as well, eg. `SymbolKind` could be `TypeRequirement` (?) with a `SymbolSubKind` of `CXXConcept`.

Are you okay with the new indexstore mapping, or would you prefer this mapped to `unknown` with a TODO to do that?

EDIT: Might be worth mentioning that template params are still mapped to unknown :(.

**Comment by akyrtzi** [comment]
I think it's fine, we still have the option to change the enum names later on if we have some cross-language "concept".

**Review by akyrtzi — APPROVED** [review]

**Comment by bnbarham** [comment]
> I think it's fine, we still have the option to change the enum names later on if we have some cross-language "concept".

Sounds good. I'll put up the indexstore-db changes once this has merged. Plus cherry-picks to next and the new stable branch.

**Review by hyp — APPROVED** [review]
Thanks!

**Pull request merged**
