### PR TITLE
Cherrypicks NSDateFormatter checker and other related (missing) commits in clang-tidy

### PR DESCRIPTION
**Pull request by t-rasmud**

### CODE REVIEW

**Comment by t-rasmud** [comment]
@swift-ci test

**Comment by t-rasmud** [comment]
@swift-ci test

**Comment by t-rasmud** [comment]
@swift-ci please test

**Review by haoNoQ — APPROVED** [review]

**Comment by t-rasmud** [comment]
swift-ci please test macOS

**Pull request merged**
