### PR TITLE
[rebranch] Push `stable/20240408` changes to `next`

### PR DESCRIPTION
**Pull request by bnbarham**
Push all the current `stable/20240408` changes up to `next` in preparation for the next branch. This is mostly LLDB, but also takes a few reverts that keep happening on `stable`.

@adrian-prantl @JDevlieghere for the LLDB changes
@etcwilde for re-exposing GTest
@aschwaighofer for the `getLoopPreheader` change (this should probably be upstreamed)
@al45tair for `Swift` triple
@egorzhdan for the cxx-interop workaround
@jroelofs for the revert of "Cleanup unwind table emission code a bit."

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please llvm test

**Comment by bnbarham** [comment]
@swift-ci please test llvm

**Review by JDevlieghere — APPROVED** [review]
LLDB LGTM

**Review by egorzhdan — APPROVED** [review]
The C++ interop bit LGTM

**Review by al45tair — APPROVED** [review]
Swift triple looks fine. Haven't reviewed the rest.

**Review by jroelofs — APPROVED** [review]
picking the EH cleanup revert LGTM

**Comment by bnbarham** [comment]
@swift-ci please test llvm

**Review by etcwilde — APPROVED** [review]
Re-exposing GTEST looks fine to me.

**Comment by bnbarham** [comment]
@aschwaighofer okay with https://github.com/apple/llvm-project/pull/8819/commits/141bce57d81f6cbd66060cdcf22e31da0b116277?

**Comment by bnbarham** [comment]
PR to upstream that change: https://github.com/llvm/llvm-project/pull/94540

**Pull request merged**
