### PR TITLE
Cherry-pick FindTypes API modernization

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by fredriss** [comment]
I think this should go to apple/stable/...

**Comment by adrian-prantl** [comment]
You're right, it's not like these cherry-picks actually contain the merge conflict resolutions.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
