### PR TITLE
[lldb] Implement TypeSystemSwiftTypeRef::GetTypeForFormatters and simplify SwiftASTContext's version

### PR DESCRIPTION
**Pull request by augusto2112**

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@adrian-prantl looks like this fixed an expected failure when disabling ClangImporter on the TestSwiftFoundationTypeDecimal.py test.

**Comment by adrian-prantl** [comment]
Nice!

**Comment by augusto2112** [comment]
@swift-ci test

**Pull request merged**
