### PR TITLE
[Coroutine][DebugInfo] Update the linkage name of the declaration of coro-split functions in the debug info.

### PR DESCRIPTION
**Pull request by dianqk**
Differential Revision: https://reviews.llvm.org/D157184

(cherry picked from commit ca1a5b37c7236dd29a3169859153dfdcce066b51)
(cherry picked from commit 88a83c90386910c959dece85c485c337c55ad05f)
(cherry picked from commit 3aed00239ca31c4cc74195ff8236d2099d7f3182)

cc @adrian-prantl

### CODE REVIEW

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by felipepiovezan** [comment]
The cherry-picks LGTM. I did leave a comment in the original review regarding how the test was created; it would be nice to address that upstream!

**Review by felipepiovezan — APPROVED** [review]

**Comment by dianqk** [comment]
> The cherry-picks LGTM. I did leave a comment in the original review regarding how the test was created; it would be nice to address that upstream!

Thanks. I saw it. I will try to reduce this test again.

**Comment by dianqk** [comment]
I picked the new test from https://reviews.llvm.org/D158178.
The upstream commit is https://github.com/llvm/llvm-project/commit/3aed00239ca31c4cc74195ff8236d2099d7f3182.

**Comment by dianqk** [comment]
Gently pinging.

**Comment by felipepiovezan** [comment]
Hi @DianQK , 
The PR is already approved, but we're missing a test run after the new push
@swift-ci test

**Comment by dianqk** [comment]
I don't have access to @swift-ci. So I'll just have to wait for you to invoke the test.
The failure now looks like a ci script error?

**Comment by felipepiovezan** [comment]
@swift-ci test

**Comment by felipepiovezan** [comment]
> I don't have access to @swift-ci. So I'll just have to wait for you to invoke the test.

Apologies, I wasn't aware of that!

 > The failure now looks like a ci script error?

Mmmm, let's try that again.

**Comment by dianqk** [comment]
Thank you very much, I think the https://github.com/apple/swift/pull/67077 test should pass as well.
Could you run the test again？

**Comment by felipepiovezan** [comment]
All merged!

**Comment by dianqk** [comment]
Thanks!

**Comment by drodriguez** [comment]
I think for that test to work `opt` might need support for the `memory(…)` attributes introduced in https://reviews.llvm.org/D135780 which are not part of the `stable/20221013` branch. There might be other pieces needed, I am not sure. It might be easier to go back to the previous spelling of the attributes in the test, but since `stable/20230725` is going to happen soon-ish, that might mean problems later.

**Comment by dianqk** [comment]
> I think for that test to work `opt` might need support for the `memory(…)` attributes introduced in https://reviews.llvm.org/D135780 which are not part of the `stable/20221013` branch. There might be other pieces needed, I am not sure. It might be easier to go back to the previous spelling of the attributes in the test, but since `stable/20230725` is going to happen soon-ish, that might mean problems later.

Weirdly, the CI has already passed. Do you have any suggestions?

**Comment by drodriguez** [comment]
As far as I understand, CI only runs the tests of the Swift compiler, so it only checks that changes to LLVM do not break the Swift compiler, but the LLVM/Clang test suites are not executed.

**Comment by dianqk** [comment]
> It might be easier to go back to the previous spelling of the attributes in the test, but since `stable/20230725` is going to happen soon-ish, that might mean problems later.

Maybe the documentation is out of date, or I'm looking in the wrong place. I'm not sure about the apple/llvm-project branching model. I think `stable/20221013` should be merged to `stable/20230725`. if we do nothing, for since `stable/20230725` development will not encounter problems.

Since apple fork project are generally not expected to have no upstream commits. I'm not sure how to do it properly.
Commit a change and then revert it in `stable/20230725`?

**Comment by felipepiovezan** [comment]
>  I think stable/20221013 should be merged to stable/20230725.

I believe this is not correct. `stable/20230725` was branched from upstream LLVM at 2023-07-25. If the commits in this PR were also placed upstream prior to that date, then they are also in `stable/20230725`.

Did this PR break any tests inside `llvm-project`? If this PR is relying on a feature that does not exist in `opt` in `stable/20221013` but it exists in `stable/20230725`, then we should fix the test _only_ in `stable/20221013`

**Comment by dianqk** [comment]
> Did this PR break any tests inside `llvm-project`?

According to @drodriguez's description, the coro-async-declaration.ll test should fail because `memory(argmem: readwrite)` is not available.

> I believe this is not correct. `stable/20230725` was branched from upstream LLVM at 2023-07-25. If the commits in this PR were also placed upstream prior to that date, then they are also in `stable/20230725`.

Thanks, I get it, great. This change landed in August.
So I should remove `memory(*)` in `stable/20221013`. Then cherry pick these commits in `stable/20230725`.

**Comment by drodriguez** [comment]
> Did this PR break any tests inside `llvm-project`?

In our test infra it does. As far as I understand ci.swift.org does not seem to run LLVM testing by default, so even if the signals are green, that might still have LLVM testing failures. In our test infra we actually run those tests and find many of these broken commits from upstream.

> > I believe this is not correct. `stable/20230725` was branched from upstream LLVM at 2023-07-25. If the commits in this PR were also placed upstream prior to that date, then they are also in `stable/20230725`.
> 
> Thanks, I get it, great. This change landed in August. So I should remove `memory(*)` in `stable/20221013`. Then cherry pick these commits in `stable/20230725`.

Again, if I understand correctly, `stable/20221013` will never be merged into `stable/20230725` (imagine them similar to LLVM release branches). I don't know what this changes are for, or why they are needed, but if you want them in future Apple releases, I think they need to be in both branches.

Since https://reviews.llvm.org/D135780 (what I think is a predependency of these changes) landed around November 2022, it is not in the `20221013` and it is probably in `20230725`. https://reviews.llvm.org/D135780 (the one pointed in the summary) is probably in none of the branches, since it was closed in August 7th.

If you want the modifications here in the new stable branch, you probably need to also cherry-pick them there. For these older stable, you can try modifying the test to pass, or try to cherry-pick the predependency, but it looks like a big change, so it might need even more changes. I don't know if the maintainers will have better ideas.

**Comment by adrian-prantl** [comment]
@DianQK The best path forward is to
- open a new PR against `stable/20221013` that backports the test such that  `check-llvm` comes out clean.
- there should be no need to cherry-pick this new PR anywhere else
- double-check that the commits in *this* PR have been cherry-picked to `stable/20230725`.

**Comment by dianqk** [comment]
> Since https://reviews.llvm.org/D135780 (what I think is a predependency of these changes) landed around November 2022, it is not in the `20221013` and it is probably in `20230725`. https://reviews.llvm.org/D135780 (the one pointed in the summary) is probably in none of the branches, since it was closed in August 7th.

@drodriguez 
I rechecked this test case. `memory(*)` doesn't make sense. I can delete it.


> The best path forward is 
>  * open a new PR against `stable/20221013` that backports the test such that  `check-llvm` comes out clean.
>  * there should be no need to cherry-pick this new PR anywhere else
>  * double-check that the commits in _this_ PR have been cherry-picked to `stable/20230725`.

@adrian-prantl 
Yeah, I'll do that. Thanks.

**Pull request merged**
