### PR TITLE
Pr merge llvm org main

### PR DESCRIPTION
**Pull request by cachemeifyoucan**

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
I don't know how to convince Github this is a good merge (basically merging two branches)

I also has a rebase on top implementation here: https://github.com/cachemeifyoucan/llvm-project/tree/experimental/cas%2Fnext

**Comment by cachemeifyoucan** [comment]
@swift-ci test

**Comment by akyrtzi** [comment]
Feel free to merge when ready, from my side. 👍

**Comment by dexonsmith** [comment]
I had a look at the history and it seems reasonable. `git log --first-parent` filters out the 10k commits, which is important.

The most important thing is that:
```
git diff --stat $(git merge-base 20ca9a65d41c llvm.org/main) 20ca9a65d41c
```
is correct but this interface won't show us that. I looked at `--stat` and it seems reasonable. I did a very basic spot check of `-u` but not much. Is there anything awkward from the merge you'd like reviewed specifically?
- If so, point me at the file(s) and I'll look at that subset of the diff.
- Else, LGTM once the bots are happy. (I suggest pushing extra commits to satisfy them rather than redoing the merge commit.)

**Comment by cachemeifyoucan** [comment]
> I had a look at the history and it seems reasonable. `git log --first-parent` filters out the 10k commits, which is important.
> 
> The most important thing is that:
> 
> ```
> git diff --stat $(git merge-base 20ca9a65d41c llvm.org/main) 20ca9a65d41c
> ```
> 
> is correct but this interface won't show us that. I looked at `--stat` and it seems reasonable. I did a very basic spot check of `-u` but not much. Is there anything awkward from the merge you'd like reviewed specifically?
> 
> * If so, point me at the file(s) and I'll look at that subset of the diff.
> * Else, LGTM once the bots are happy. (I suggest pushing extra commits to satisfy them rather than redoing the merge commit.)

There isn't anything to review. It is more to get an OK to go ahead to press merge button once the bot is green.

DepScan is not in good shape but I will rewrite it to keep both version after the merge.

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Pull request merged**
