### PR TITLE
Cherry picks

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
Thanks!

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
I can't reproduce the linux failures even on Linux ...

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
