### PR TITLE
Symbol: use elaborated type (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
This should repair the build with Visual Studio.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @dcci @JDevlieghere

**Review by dcci — COMMENTED** [review]
This of course looks good, but should we make this change upstream? Also, probably this should go to the dated branch? `apple/stable/20190619`

**Comment by compnerd** [comment]
The dated branch is out of sync with this it seems.  So, something is not right, and Id rather not make the change on the dated branch only to find that the build is still broken.  The Swift builds have been broken for ~24 hours at this point, can we please expedite fixes to get things building again?

**Comment by JDevlieghere** [comment]
> The dated branch is out of sync with this it seems. So, something is not right, and Id rather not make the change on the dated branch only to find that the build is still broken. The Swift builds have been broken for ~24 hours at this point, can we please expedite fixes to get things building again?

I assume this is because the automerger is backed up? I'm fine with merging this to unblock you, if there's also a PR for the dated branch. They really shouldn't get out of sync as far as non-Swift changes are concerned.

**Comment by compnerd** [comment]
#420 has this cherry-picked to the dated branch.

**Comment by JDevlieghere** [comment]
Thank you!

**Pull request closed without merging**
