### PR TITLE
[LLDB][5.9] Cherry-pick changes to fix TestExec.py

### PR DESCRIPTION
**Pull request by bulbazord**
I fixed this upstream but we're still missing this on the 5.9 branch.

### CODE REVIEW

**Comment by bulbazord** [comment]
@swift-ci please test

**Review by kastiglione — APPROVED** [review]

**Comment by kastiglione** [comment]
can you add another cherry pick https://github.com/apple/llvm-project/commit/78fee46d8d8e82158b79a4ad948e8723e89f7f65? (from [D142709](https://reviews.llvm.org/D142709))

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by kastiglione** [comment]
@swift-ci test Windows

**Pull request merged**
