### PR TITLE
Disable loading scalars as addresses when materializing an entity variable (swift/release/5.3)

### PR DESCRIPTION
**Pull request by augusto2112**
@adrian-prantl

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@fredriss (our release manager)
Given how easy it is to trigger this, I recommend cherry-picking this patch to 5.3. It fixes a bug when using generic values in the expression evaluator if they are stored in a register. The fix works by reverting an old workaround and restores the code to the form it has on llvm.org.

(The test is going to be updated shortly, so ignore that for now)

**Comment by adrian-prantl** [comment]
@augusto2112 When cherry-picking a commit, pease use `git cherry-pick -x`, it adds a line to the commit message that makes it obvious that this is a cherry-pick.

**Comment by augusto2112** [comment]
@adrian-prantl Ok! I'll do it next time!

**Comment by adrian-prantl** [comment]
@augusto2112 can you update the test here?
Also, I just realized: was the test missing from the master-next PR? Could you make a newPR for adding the test to master-next?

**Comment by augusto2112** [comment]
@adrian-prantl you're right, I forgot to update it there too. I'll create a new PR.

**Comment by augusto2112** [comment]
@adrian-prantl test updated!

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by fredriss — APPROVED** [review]

**Pull request merged**
