### PR TITLE
Revert "Cherry pick two swift changes from next branch"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/llvm-project#4051

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @eeckstein

**Comment by etcwilde** [comment]
Yeah, LGTM. The patch being reverted relies on the ordering of lldb after swift, which doesn't hold. When swift is processed after lldb, the `swiftCompilerStub` target doesn't exist, and so it fails (as it is when doing a unified build). Furthermore, squinting, it looks like you can't actually build lldb in isolation anymore.

**Comment by etcwilde** [comment]
`linux-nodes i-0935fc9aa18504e98 was marked offline: Connection was broken: java.io.EOFException`

@swift-ci please test Linux

**Comment by etcwilde** [comment]
@swift-ci please test Linux

**Comment by etcwilde** [comment]
@swift-ci please test Linux

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Pull request merged**
