### PR TITLE
Fix result numbering

### PR DESCRIPTION
**Pull request by jimingham**
Pulling the two commits from swift/master-next to fix the result so that Private expression results don't take up result numbering slots.

### CODE REVIEW

**Comment by jimingham** [comment]
@swift-ci please test macos

**Review by dcci — COMMENTED** [review]
@jimingham what we should do with this one?

**Comment by jimingham** [comment]
I fixed up the cherry-picks for the changes in master since I originally did this patch.  I don't remember why this didn't pass the checks the first time, I don't think it was something essential.  Let's try this again.

**Comment by jimingham** [comment]
@swift-ci please test

**Comment by dcci** [comment]
Thank you Jim

**Comment by jimingham** [comment]
Missed one of the conflict markers.  Let's try again...

**Comment by jimingham** [comment]
@swift-ci please test

**Comment by jimingham** [comment]
Now swift isn't building... This is the ICU include problem, right?  Let me see if a rebase fixes things.

**Comment by shahmishal** [comment]
The project moved the branch to `swift/main` and deleted `swift/master` branch, so GitHub automatically closed the PR. Please re-create the pull request with `swift/main` branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
