### PR TITLE
[LiveDebugValues] Remove unused static function

### PR DESCRIPTION
**Pull request by kastiglione**
Last use removed in https://github.com/apple/llvm-project/pull/7715

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by felipepiovezan** [comment]
Disappointed at myself for not seeing the compiler warning x.x

Thanks for catching this!

**Review by felipepiovezan — APPROVED** [review]

**Comment by kastiglione** [comment]
@swift-ci test macOS

**Comment by adrian-prantl** [comment]
nice!

**Comment by felipepiovezan** [comment]
I cherry-picked this to next here: https://github.com/apple/llvm-project/pull/7826

**Pull request merged**
