### PR TITLE
Swift async frame cherry pick

### PR DESCRIPTION
**Pull request by TNorthover**
Arnold wanted this cherry-picked and I need the pull request to get CI tag, apparently.

### CODE REVIEW

**Comment by aschwaighofer** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
Where was this change cherry-picked from? For example, I don't see `def SwiftAsyncContextDocs : Documentation` on the `main` branch. Perhaps I'm misunderstanding where changes are expected to be landed...

**Comment by TNorthover** [comment]
I did the implementation on `internal/main` originally. This one's entirely in LLVM+Clang and I'm not sure which branches `SwiftAsyncContextDocs` would be on.

**Comment by TNorthover** [comment]
I'm also trying to upstream it to OSS LLVM now, which might make it appear on `main` for you? I have to admit Swift's repo & branch structure is a bit of a black box for me.

**Comment by varungandhi-apple** [comment]
The branching scheme is described here: https://github.com/apple/llvm-project/blob/apple/main/apple-docs/AppleBranchingScheme.md. Here's a quick summary of the automergers that are relevant here:

1. (bleeding edge) `main` -> `apple/main` -> `swift/next`
2. (slow-moving) `apple/stable/*` -> `swift/main`.

So for landing newer changes, my understanding (cc @hyp for a spot-check) is that upstreaming is expected to be done to `main` first, then you can cherry-pick changes if needed to `apple/stable/*` (such as in this PR). I was working on submitting a Clang patch to `main` for frontend support for swiftasyncc, which uses parts of this patch. However, since this hasn't change hasn't landed on `main`, I can't submit a patch for that (I could rebase on top of your changes if you have an existing phrabricator diff, maybe?).

**Comment by varungandhi-apple** [comment]
[For future reference] Corresponding LLVM patches for the commits:

1. https://reviews.llvm.org/D95044: IR+AArch64: add `swiftasync` function parameter attribute
2. https://reviews.llvm.org/D95228: Add swift_async_context parameter attribute mapping to IR equivalent

**Pull request merged**
