### PR TITLE
Upstream ns_error_domain attribute

### PR DESCRIPTION
**Pull request by MForster**
There are two commits in this pull request:

The first commit proactively applies the changes that have been made to `ns_error_domain` during upstreaming to avoid merge conflicts when the change trickles down. This has been reviewed upstream at [D84005](https://reviews.llvm.org/D84005), but not submitted, yet. If more comments come up for this part, I would apply them to the upstream code review.

The second commit adds additional changes for APInotes that have not been reviewed, yet.

### CODE REVIEW

**Comment by MForster** [comment]
@gribozavr, @DougGregor, I would appreciate your review on this change.

**Comment by gribozavr** [comment]
LGTM!

@DougGregor could you review & merge?

**Comment by MForster** [comment]
Thanks for the review. Please don't merge, yet. I think I may have found an issue. I'll mark this as draft while I investigate (tomorrow).

**Comment by MForster** [comment]
This is ready for review (and merging) now.

**Comment by MForster** [comment]
I've added an additional test from the upstream code review and rebased against `apple/master` head.

@DougGregor, can you review and merge this?

**Comment by MForster** [comment]
Hi @DougGregor, we do have commit rights for this branch now, so we can also move ahead on our own. We are still interested in your feedback, though, if you have time.

**Review by DougGregor — APPROVED** [review]
I only had the chance to skim this, but it LGTM. Thank you!

**Pull request merged**
