### PR TITLE
[lldb] Handle CFTimeZoneRef in NSTimeZoneSummaryProvider

### PR DESCRIPTION
**Pull request by kastiglione**
rdar://114567512
(cherry picked from commit 21292fc1df960d0b5397e9a6a996c21fa91e2c7c)

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
Looks like the cherry-pick fails to compile...

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test windows

**Comment by kastiglione** [comment]
@swift-ci test windows

**Pull request merged**
