### PR TITLE
Temporarily skip test that fails nondeterministically in CI

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
accidentally disabled the wrong TestSwiftUnknown... test m(

**Review by kastiglione — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
