### PR TITLE
Revert InstCombine FoldIntegerTypedPHI optimization

### PR DESCRIPTION
**Pull request by francisvm**
This reverts commit 4cdc9da.

The compile-time initially observed is still here even after the fix in
5214dbb.

The compile-time issue triggered a slow-down up to 4x when building swift with -O2 and full LTO.

### CODE REVIEW

**Comment by francisvm** [comment]
@swift-ci please test macOS platform

**Comment by DougGregor** [comment]
What does this change do?

**Comment by francisvm** [comment]
> What does this change do?

Updated the description with the contents from the revert commit.

**Review by Gerolf-Apple — APPROVED** [review]
LGTM.

**Pull request merged**
