### PR TITLE
[cherry-pick swift/release/6.0][clang][modules] Enable built-in modules for the upcoming Apple releases

### PR DESCRIPTION
**Pull request by ian-twilightcoder**
The upcoming Apple SDK releases will support the clang built-in headers being in the clang built-in modules: stop passing -fbuiltin-headers-in-system-modules for those SDK versions.

rdar://116490661

### CODE REVIEW

**Comment by ian-twilightcoder** [comment]
Explanation: This change is required for open source clang to be able to work with the SDKs in Xcode 16 beta 5 and beyond. (It will break compatibility for the earlier betas, but not the earlier releases.)
Radar (and possibly SR Issue): rdar://116490661
Scope: This affects compiling against the Xcode 16 beta SDKs, it does not affect previous (Xcode 15 and earlier) SDKs.
Risk: None anticipated.
Testing: Local testing, CI.
Reviewed By: Cyndy Ishida (cyndyishida)

**Comment by ian-twilightcoder** [comment]
@swift-ci test llvm

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
All of the Linux llvm test failures are known failures:
```
clang: error: unknown argument '-emit-llvm-only'; did you mean '-Xclang -emit-llvm-only'?
```

**Comment by ian-twilightcoder** [comment]
> All of the Linux llvm test failures are known failures:
> 
> ```
> clang: error: unknown argument '-emit-llvm-only'; did you mean '-Xclang -emit-llvm-only'?
> ```

Same for all of the macOS llvm test failures.

**Comment by ian-twilightcoder** [comment]
@swift-ci test llvm

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test Windows

**Review by cyndyishida — APPROVED** [review]

**Pull request merged**
