### PR TITLE
[llvm][clang] Cherry-pick performance improvements to command line generation

### PR DESCRIPTION
**Pull request by jansvoboda11**

### CODE REVIEW

**Comment by jansvoboda11** [comment]
Locally, these tests fail for `check-llvm` and `check-clang` before and after this PR:
```
Failed Tests (7):
  LLVM :: CodeGen/AArch64/neon-dotreduce.ll
  LLVM :: DebugInfo/X86/debug-info-default-template-parameter.ll
  LLVM :: DebugInfo/X86/swift-async-entryvalues2.ll
  LLVM :: Instrumentation/AddressSanitizer/do-not-instrument-ptrauth-globals.ll
  LLVM :: ObjectYAML/Offload/binary.yaml
  LLVM :: ObjectYAML/Offload/multiple_members.yaml
  LLVM :: tools/yaml2obj/COFF/xrelocs.yaml
```

```
Failed Tests (3):
  Clang :: APINotes/objcxx-swift-name.m
  Clang :: SemaCXX/ptrauth-qualifier.cpp
  Clang-Unit :: Tooling/./ToolingTests/JSONCompilationDatabase/GetAllFiles
```

**Comment by artemcm** [comment]
Coooooool.

**Comment by jansvoboda11** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]

**Comment by jansvoboda11** [comment]
https://github.com/apple/swift/pull/67950
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/swift/pull/67950
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/swift/pull/67950
@swift-ci please test

**Pull request merged**
