### PR TITLE
Adds AST matcher for ObjCStringLiteral

### PR DESCRIPTION
**Pull request by t-rasmud**
Differential Revision: https://reviews.llvm.org/D128103

(cherry picked from commit eb1d908e5cf7279b98b84d1587d4665d3cdecbe9)

### CODE REVIEW

**Comment by t-rasmud** [comment]
@swift-cit test

**Comment by t-rasmud** [comment]
@swift-ci test

**Comment by haoNoQ** [comment]
LGTM!

**Review by haoNoQ — APPROVED** [review]

**Comment by t-rasmud** [comment]
@swift-ci test

**Pull request closed without merging**
