### PR TITLE
[GlobalDCE] Add !llvm.used.conditional support for conditionally used global variables

### PR DESCRIPTION
**Pull request by kubamracek**
This PR lands a preview version of !llvm.used.conditional that is not yet merged in upstream LLVM and is being reviewed at <https://reviews.llvm.org/D104496>, but it's important to unblock progress in adopting these changes in Swift. Once upstream LLVM gets !llvm.used.metadata (or a differently-named or differently-implemented) support, which downstream change will be reverted.

Commit message:
> [GlobalDCE] Add !llvm.used.conditional support for conditionally used global variables
>
> As part of the optimization work to emit dead-strippable symbols for Swift and
enable GlobalDCE to remove those symbols when possible, we need to mark some
Swift symbols as conditionally used based on a set of other symbols. Background
info can be found here: https://bugs.swift.org/browse/SR-14509.
> 
> This diff adds a module-level name metadata !llvm.used.conditional, which
contains a list of metadata triplets, that describes the conditions under which
we allow removal of globals even if they are mentioned in @llvm.used. See the
included LangRef changes to details. The implementation is a strict addition,
it does not change any semantics and does not affect IR or passes in any way,
unless !llvm.used.conditional is present in the input IR.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by fhahn** [comment]
Looks like there's a failure on macOS which may be relevant:

> 01:04:56   Swift(macosx-x86_64) :: IRGen/conditional-dead-strip-ir.swift

**Comment by kubamracek** [comment]
> Looks like there's a failure on macOS which may be relevant:
> 
> > 01:04:56   Swift(macosx-x86_64) :: IRGen/conditional-dead-strip-ir.swift

Addressed (on the Swift side), it was the IR Verifier not liking the slightly-different version of llvm.used.conditional that is used in this test :) The next run should be clean.

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test macOS platform

**Comment by kubamracek** [comment]
@swift-ci please test

**Pull request merged**
