### PR TITLE
Cherry pick status refactor

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by Michael137 — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by medismailben — APPROVED** [review]
LGTM! Thanks!

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by medismailben** [comment]
Cherry-picking my commits in #9414 to hopefully fix CI testing

**Comment by medismailben** [comment]
@adrian-prantl after my PR lands, you can try to get rid of my commits from this PR except for f732157a9d06 since it depends on your Status refactor.

**Comment by medismailben** [comment]
> @adrian-prantl after my PR lands, you can try to get rid of my commits from this PR except for [f732157](https://github.com/swiftlang/llvm-project/commit/f732157a9d067e4d300905c831a964222e0eadee) since it depends on your Status refactor.

@adrian-prantl 62cdcdf7ffa1fce6ecf7feac77a250483781a819 also depends on the status refactor so you'll have to leave it as part of this PR. Thanks.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
