### PR TITLE
[cherry-pick][stable/20230725] [lldb] Make only one function that needs to be implemented when searching for types

### PR DESCRIPTION
**Pull request by Michael137**
This patch revives the effort to get this Phabricator patch into
upstream:

https://reviews.llvm.org/D137900

This patch was accepted before in Phabricator but I found some
-gsimple-template-names issues that are fixed in this patch.

A fixed up version of the description from the original patch starts
now.

This patch started off trying to fix Module::FindFirstType() as it
sometimes didn't work. The issue was the SymbolFile plug-ins didn't do
any filtering of the matching types they produced, and they only looked
up types using the type basename. This means if you have two types with
the same basename, your type lookup can fail when only looking up a
single type. We would ask the Module::FindFirstType to lookup "Foo::Bar"
and it would ask the symbol file to find only 1 type matching the
basename "Bar", and then we would filter out any matches that didn't
match "Foo::Bar". So if the SymbolFile found "Foo::Bar" first, then it
would work, but if it found "Baz::Bar" first, it would return only that
type and it would be filtered out.

Discovering this issue lead me to think of the patch Alex Langford did a
few months ago that was done for finding functions, where he allowed
SymbolFile objects to make sure something fully matched before parsing
the debug information into an AST type and other LLDB types. So this
patch aimed to allow type lookups to also be much more efficient.

As LLDB has been developed over the years, we added more ways to to type
lookups. These functions have lots of arguments. This patch aims to make
one API that needs to be implemented that serves all previous lookups:

- Find a single type
- Find all types
- Find types in a namespace

This patch introduces a `TypeQuery` class that contains all of the state
needed to perform the lookup which is powerful enough to perform all of
the type searches that used to be in our API. It contain a vector of
CompilerContext objects that can fully or partially specify the lookup
that needs to take place.

If you just want to lookup all types with a matching basename,
regardless of the containing context, you can specify just a single
CompilerContext entry that has a name and a CompilerContextKind mask of
CompilerContextKind::AnyType.

Or you can fully specify the exact context to use when doing lookups
like: CompilerContextKind::Namespace "std"
CompilerContextKind::Class "foo"
CompilerContextKind::Typedef "size_type"

This change expands on the clang modules code that already used a
vector<CompilerContext> items, but it modifies it to work with
expression type lookups which have contexts, or user lookups where users
query for types. The clang modules type lookup is still an option that
can be enabled on the `TypeQuery` objects.

This mirrors the most recent addition of type lookups that took a
vector<CompilerContext> that allowed lookups to happen for the
expression parser in certain places.

Prior to this we had the following APIs in Module:

```
void
Module::FindTypes(ConstString type_name, bool exact_match, size_t max_matches,
                  llvm::DenseSet<lldb_private::SymbolFile *> &searched_symbol_files,
                  TypeList &types);

void
Module::FindTypes(llvm::ArrayRef<CompilerContext> pattern, LanguageSet languages,
                  llvm::DenseSet<lldb_private::SymbolFile *> &searched_symbol_files,
                  TypeMap &types);

void Module::FindTypesInNamespace(ConstString type_name,
                                  const CompilerDeclContext &parent_decl_ctx,
                                  size_t max_matches, TypeList &type_list);
```

The new Module API is much simpler. It gets rid of all three above
functions and replaces them with:

```
void FindTypes(const TypeQuery &query, TypeResults &results);
```
The `TypeQuery` class contains all of the needed settings:

- The vector<CompilerContext> that allow efficient lookups in the symbol
file classes since they can look at basename matches only realize fully
matching types. Before this any basename that matched was fully realized
only to be removed later by code outside of the SymbolFile layer which
could cause many types to be realized when they didn't need to.
- If the lookup is exact or not. If not exact, then the compiler context
must match the bottom most items that match the compiler context,
otherwise it must match exactly
- If the compiler context match is for clang modules or not. Clang
modules matches include a Module compiler context kind that allows types
to be matched only from certain modules and these matches are not needed
when d oing user type lookups.
- An optional list of languages to use to limit the search to only
certain languages

The `TypeResults` object contains all state required to do the lookup
and store the results:
- The max number of matches
- The set of SymbolFile objects that have already been searched
- The matching type list for any matches that are found

The benefits of this approach are:
- Simpler API, and only one API to implement in SymbolFile classes
- Replaces the FindTypesInNamespace that used a CompilerDeclContext as a
way to limit the search, but this only worked if the TypeSystem matched
the current symbol file's type system, so you couldn't use it to lookup
a type in another module
- Fixes a serious bug in our FindFirstType functions where if we were
searching for "foo::bar", and we found a "baz::bar" first, the basename
would match and we would only fetch 1 type using the basename, only to
drop it from the matching list and returning no results

### CODE REVIEW

**Comment by Michael137** [comment]
This cherry-picks @clayborg's `FindTypes` work. Cherry-picked the vtable ValueObject changes too for convenience

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
Have to fixup the Swift plugin side of things now

**Review by adrian-prantl — APPROVED** [review]
LGTM modulo failing Swift tests.

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test Windows platform

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test Windows platform

**Comment by Michael137** [comment]
Requires https://github.com/llvm/llvm-project/pull/75926

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test Windows platform

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci please test Windows platform

**Comment by Michael137** [comment]
@swift-ci test
@swift-ci please test Windows platform

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
Following tests are failing:
```
Unresolved Tests (2):
  lldb-api :: functionalities/vtable/TestVTableValue.py
  lldb-api :: lang/cpp/union-static-data-members/TestCppUnionStaticMembers.py

********************
Failed Tests (5):
  lldb-api :: lang/c/tls_globals/TestTlsGlobals.py
  lldb-api :: lang/cpp/thread_local/TestThreadLocal.py
  lldb-api :: macosx/indirect_symbol/TestIndirectSymbols.py
  lldb-shell :: Unwind/eh-frame-dwarf-unwind.test
  lldb-shell :: Unwind/thread-step-out-ret-addr-check.test
```

These fail on the 5.10 CI job too:
```
lldb-api :: lang/c/tls_globals/TestTlsGlobals.py
lldb-api :: lang/cpp/thread_local/TestThreadLocal.py
lldb-api :: macosx/indirect_symbol/TestIndirectSymbols.py
lldb-shell :: Unwind/eh-frame-dwarf-unwind.test
lldb-shell :: Unwind/thread-step-out-ret-addr-check.test
```

So need to see why following two are crashing:
```
Unresolved Tests (2):
  lldb-api :: functionalities/vtable/TestVTableValue.py
  lldb-api :: lang/cpp/union-static-data-members/TestCppUnionStaticMembers.py
```
Probably missing cherry-picks

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci please test Windows platform

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci please test Windows platform

**Comment by Michael137** [comment]
@swift-ci please test Windows platform

**Comment by Michael137** [comment]
Following tests are failing:
```
Failed Tests (5):
  lldb-api :: lang/c/tls_globals/TestTlsGlobals.py
  lldb-api :: lang/cpp/thread_local/TestThreadLocal.py
  lldb-api :: macosx/indirect_symbol/TestIndirectSymbols.py
  lldb-shell :: Unwind/eh-frame-dwarf-unwind.test
  lldb-shell :: Unwind/thread-step-out-ret-addr-check.test
```

But those also fail on `stable/20230725`, so I'll go ahead and merge this.

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci please test Windows platform

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by Michael137** [comment]
@swift-ci test macOS

**Comment by Michael137** [comment]
Argh now it's failing with something new:
```
Failed Tests (2):
  lldb-api :: lang/swift/deployment_target/TestSwiftDeploymentTarget.py
  lldb-api :: lang/swift/enum_objc/TestEnumObjC.py
```

Though they aren't failing on the non-PR CI jobs. Locally they don't fail either....

**Comment by adrian-prantl** [comment]
@Michael137 Note that build-script runs the LLDB Swift tests in 4 different configuration. The one that fails is
```
--- Rerun LLDB Swift API tests (Swift Config: Classic/DWARFImporter) ---
```

**Comment by adrian-prantl** [comment]
```
+ /Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20230725/build/Ninja-RelWithDebInfoAssert+stdlib-RelWithDebInfo/llvm-macosx-x86_64/bin/llvm-lit /Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20230725/build/Ninja-RelWithDebInfoAssert+stdlib-RelWithDebInfo/lldb-macosx-x86_64/test -v --xunit-xml-output=/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20230725/build/Ninja-RelWithDebInfoAssert+stdlib-RelWithDebInfo/lldb-macosx-x86_64/test-results/results.xml --filter=lang/swift --param 'dotest-args=--setting symbols.use-swift-clangimporter=false'
```
The very last argument is the important one for you

**Comment by adrian-prantl** [comment]
`--param 'dotest-args=--setting symbols.use-swift-clangimporter=false'`

**Comment by adrian-prantl** [comment]
`symbols.use-swift-clangimporter=false` turns off Swift's ClangImporter and imports all Clang types from DWARF, so it's not surprising that this is where the patch introduces some unexpected behavior change. Note that there are some known bugs with DWARFImporter, so this may not necessarily be fixable on short order. We can take a look together.

**Comment by Michael137** [comment]
> `--param 'dotest-args=--setting symbols.use-swift-clangimporter=false'`

Ah cool, with this setting I can repro the failures

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test Windows platform

**Comment by Michael137** [comment]
@swift-ci test Windows

**Comment by Michael137** [comment]
1 test failure remaining:
```
FAIL: LLDB (/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20230725/build/Ninja-RelWithDebInfoAssert+stdlib-RelWithDebInfo/llvm-macosx-x86_64/bin/clang-x86_64) :: test_swift_deployment_target_from_macho (TestSwiftDeploymentTarget.TestSwiftDeploymentTarget)
======================================================================
FAIL: test_swift_deployment_target_from_macho (TestSwiftDeploymentTarget.TestSwiftDeploymentTarget)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20230725/llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20230725/llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20230725/llvm-project/lldb/test/API/lang/swift/deployment_target/TestSwiftDeploymentTarget.py", line 64, in test_swift_deployment_target_from_macho
    self.expect("expression f", substrs=["i = 23"])
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20230725/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2433, in expect
    self.runCmd(
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20230725/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2109, in runCmd
    self.assertTrue(self.res.Succeeded(), msg if (msg) else CMD_MSG(cmd))
AssertionError: False is not True : Command 'expression f
Error output:
error: <EXPR>:3:1: error: cannot find 'f' in scope
f
^
```

Doesn't repro locally with exactly the same `dotest` invocation.

**Comment by adrian-prantl** [comment]
@swift-ci test macos

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test Windows

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test Windows

**Comment by Michael137** [comment]
@swift-ci test Windows

**Pull request merged**
