### PR TITLE
[clang][deps] Cherry-pick the 1st batch of performance improvements

### PR DESCRIPTION
**Pull request by jansvoboda11**

### CODE REVIEW

**Comment by jansvoboda11** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
Please also cherry-pick this to `stable/20230725` if it will affect API in swift. Thanks

**Comment by artemcm** [comment]
> Please also cherry-pick this to `stable/20230725` if it will affect API in swift. Thanks

Please cherry-pick even if it will not affect API in swift. :)

**Comment by etcwilde** [comment]
> Please cherry-pick even if it will not affect API in swift. :)

No, only things that are absolutely necessary to unblock rebranch qualification should be merged into this branch.

**Comment by bnbarham** [comment]
I feel like there's a bit of confusion happening here. To be clear, stable/20230725 is branched off of next. That happened on July 25th (hence the branch name). So only commits *after* that point need to be cherry-picked onto stable/20230725. That's maybe some of these, but I doubt it's all.

> No, only things that are absolutely necessary to unblock rebranch qualification should be merged into this branch.

While I would love this to be the case, it's just going to cause problems. If a change is being cherry-picked to stable/20221013 and it isn't on stable/20230725, it should also be cherry-picked to stable/20230725. Doing just API changes is going to cause trouble down the road that isn't worth it, including conflicts that wouldn't otherwise happen. Having said that, please do run testing to check that (1) the cherry-pick builds and (2) there aren't any new test failures caused by it.

It's also likely much easier to do the cherry-pick from the next branch, since we really should not be that far diverged at this point (I would hope). It will have also dealt with any merge conflicts from apple-fork only changes.

**Pull request merged**
