### PR TITLE
Open Swift healthcheck automatically when in Xcode.

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://92644555

### CODE REVIEW

**Review by kastiglione — APPROVED** [review]

**Comment by JDevlieghere** [comment]
I think opening the directory where the file lives makes more sense, but maybe I misunderstand the purpose of the healthcheck output. Do you expect the person running the healthcheck command to look at the content and be able to diagnose the issue themselves? Or is it meant to be attached to a bug report like a sysdiagnose? Which workflow do you expect to be more common?

**Comment by adrian-prantl** [comment]
>  Do you expect the person running the healthcheck command to look at the content and be able to diagnose the issue themselves? 

Yes.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
healthcheck is a very filtered types log that focusses on Swift module import issues, specifically to make easier to diagnose and fix issues yourselves.

**Review by JDevlieghere — APPROVED** [review]
Thanks for clarifying. This makes total sense then. LGTM.

**Pull request merged**
