### PR TITLE
Introduce a `LinkGraph` builder based on the `CASObjectReader` interface

### PR DESCRIPTION
**Pull request by akyrtzi**
Use the new builder to replace the specific `flatv1` and `nestedv1` builders.

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
Ok to merge? 🙏

**Comment by cachemeifyoucan** [comment]
> Ok to merge? 🙏

I just did this merge on upstream. Can you double check this commit won't break it or there is better solution now?
https://github.com/apple/llvm-project/commit/c5280ecd7a5fc0c331f9901d281e0852d6e5fa3b

**Comment by akyrtzi** [comment]
> I just did this merge on upstream. Can you double check this commit won't break it or there is better solution now?
https://github.com/apple/llvm-project/commit/c5280ecd7a5fc0c331f9901d281e0852d6e5fa3b

This PR doesn't affect `lld`. I'll double-check the commit, thank you for updating it!

**Comment by akyrtzi** [comment]
@swift-ci test linux platform

**Pull request merged**
