### PR TITLE
[lldb] Update Swift mangling example in `type lookup`

### PR DESCRIPTION
**Pull request by kastiglione**

### CODE REVIEW

**Comment by kastiglione** [comment]
Is there a way we can merge this without doing a clearly unnecessary test? Seems wasteful to use up all that time for a string change.

**Comment by adrian-prantl** [comment]
We usually don't test the _contents_ of the documentation.

**Review by adrian-prantl — APPROVED** [review]

**Comment by kastiglione** [comment]
And since there's no tests, it seems like a waste to run tests, but I guess there's no way to merge without doing an unnecessary test run?

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
You'll still want to make sure the commit isn't accidentally breaking existing tests.

**Pull request merged**
