### PR TITLE
 Un-XFAIL SDK path remapping test for DebugMap objects

### PR DESCRIPTION
**Pull request by adrian-prantl**
after cherry-picking 99267de

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
Note that this PR is a superset of https://github.com/apple/llvm-project/pull/1184.

**Review by fredriss — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
