### PR TITLE
Copy object dump code for mccas into llvm-cas-dump

### PR DESCRIPTION
**Pull request by rastogishubham**
llvm-cas-object-format is the tool that is used to dump cas statistics, we do not want to merge llvm-cas-object-format into the next branch, but we need the ability to dump cas statistics in the next branch. This patch copies some of the code needed to do cas stastitics dumping into llvm-cas-dump.

### CODE REVIEW

**Comment by rastogishubham** [comment]
@swift-ci please test

**Comment by rastogishubham** [comment]
@felipepiovezan I worked off of experimental/cas/main, I hope you can cherry-pick this into your branch for next. Thanks :)

**Review by felipepiovezan — COMMENTED** [review]
Would it be possible to move all the stats code into a new, separate file? Currently, `llvm-cas-dump.cpp` is very simple and only handles the CLI logic, so it would be nice to preserve that

**Comment by rastogishubham** [comment]
@swift-ci please test

**Review by felipepiovezan — APPROVED** [review]

**Pull request merged**
