### PR TITLE
Add '<' meta command to read in statements from external file

### PR DESCRIPTION
**Pull request by pcbeard**
Perform all error handling in ReadCode()

### CODE REVIEW

**Review by jimingham — CHANGES_REQUESTED** [review]
This looks great.  

Can I ask you to do one more thing?  In  source/Expression/REPL.cpp there is a bit of text that the REPL emits when you run :help that gives an intro to REPL specific uses.  It's in the function IOHandlerGetHelpPrologue.  Can you add a brief sentence describing the use of the initial < meta-character?  Otherwise I don't know how anyone would discover this new feature...

**Review by jimingham — APPROVED** [review]
LGTM

**Comment by pcbeard** [comment]
This will need to be split up. Most of it will need to go straight to llvm:master, the tests will remain in apple:swift/master.

**Comment by pcbeard** [comment]
This PR is subsumed by:

https://github.com/apple/llvm-project/pull/1856
https://github.com/apple/llvm-project/pull/1857
https://github.com/apple/llvm-project/pull/1858

**Pull request closed without merging**
