### PR TITLE
[lldb][NFCI] Remove unused file lldb.cpp

### PR DESCRIPTION
**Pull request by bulbazord**
This file doesn't exist upstream anymore, everything is done through `lldbVersion` now.

### CODE REVIEW

**Comment by JDevlieghere** [comment]
LGTM. Removing this file was supposed to be the last step in https://reviews.llvm.org/D115211 but seems like that never happened. Thanks!

**Review by JDevlieghere — APPROVED** [review]

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
@swift-ci please test Windows Platform

**Comment by bulbazord** [comment]
@swift-ci please test Windows Platform

**Comment by JDevlieghere** [comment]
@swift-ci please test Windows Platform

**Comment by bulbazord** [comment]
@swift-ci please test Windows Platform

**Pull request merged**
