### PR TITLE
[Gardening] Adjust for apple/swift#29155

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
Leaving a note to remind myself: Cherry-pick this into swift/master-next

**Comment by CodaFi** [comment]
apple/swift#29155

@swift-ci test

**Comment by CodaFi** [comment]
apple/swift#29155

@swift-ci test

**Comment by CodaFi** [comment]
apple/swift#29155

@swift-ci test

**Comment by CodaFi** [comment]
apple/llvm-project#563

@swift-ci smoke test

**Comment by CodaFi** [comment]
apple/llvm-project#563

@swift-ci test

**Comment by CodaFi** [comment]
apple/swift#29155

@swift-ci test

**Comment by CodaFi** [comment]
apple/swift#29155

@swift-ci test macOS platform

**Comment by CodaFi** [comment]
⛵️

**Comment by bulbazord** [comment]
@CodaFi Could you please cherry-pick this change to `apple:swift/master-next` as well?

**Comment by CodaFi** [comment]
@xiaobai Done in https://github.com/apple/llvm-project/pull/575

**Pull request merged**
