### PR TITLE
Add error handling for garbage-collected class objects.

### PR DESCRIPTION
**Pull request by adrian-prantl**
Depends on and implements LLDB support for https://github.com/apple/swift/pull/36389

### CODE REVIEW

**Comment by atrick** [comment]
We want to users to know about the `withExtendedLifetime` API if these shortened lifetimes are a problem. I don't necessarily think we should clutter the error message though. Will it be sufficient for users to search for "variable has been deinitialized" and stumble upon some release note or other documentation?

**Comment by atrick** [comment]
I arbitrarily picked the '0x880' sentinel during prototyping. The only restriction is that it should not use any spare bits according to our ABI, and should never point to readable memory (I assume anything less than 4k is safely non-readable across any OS that runs lldb). But we should get more input on this.

**Comment by jimingham** [comment]
lldb shouldn't know 0x880, should it?  We have a copy of swift built-in, seems to me this should be a swift constant.  

It would also be cleaner to move all the logic from the Materializer into a ValueObjectWasDeinitialized method in the swift runtime.  That way you wouldn't have to type "Swift.$deinit" in two places, which is a little yucky...  In fact, you could add a general WasDeinitalized method to the base runtime and only implement it for Swift with this code.  Deinitializing something before the end of its scope doesn't seem like a swift specific trick to pull.

**Comment by jimingham** [comment]
Even better would be to have:

  size_t swift_deinitialized_pointer_sentinel_value = 0x880;
   if (class_metadata_ptr == swift_deinitialized_pointer_sentinel_value) {

be a function in Swift that we could call.

**Comment by atrick** [comment]
If there's a build-time way for lldb to grab Swift constants, that would be nice. I'm not sure how to do that.

We certainly could add a runtime entry point now or any time in the future, but that creates a pretty annoying dependency and is more likely to go wrong than the constant getting out-of-sync. If this constant is out-of-sync, it isn't really a serious problem.

Longer term, the more interesting question is how lldb can recognize deintialized objects by reading the object header. It would be worthwhile to develop runtime support for that. This sentinel value is a stop-gap measure.

**Comment by jimingham** [comment]
> If there's a build-time way for lldb to grab Swift constants, that would be nice. I'm not sure how to do that.
> 

Not sure what you mean.  lldb builds against a built swift compiler and includes lots of swift headers.  If something is in a header in swift/include we should be able to get at it.

> We certainly could add a runtime entry point now or any time in the future, but that creates a pretty annoying dependency and is more likely to go wrong than the constant getting out-of-sync. If this constant is out-of-sync, it isn't really a serious problem.
> 
> Longer term, the more interesting question is how lldb can recognize deintialized objects by reading the object header. It would be worthwhile to develop runtime support for that. This sentinel value is a stop-gap measure.

Cool, we shouldn't add interfaces we're going to supplant soon, but in general whenever lldb knows too much about how swift objects are laid out we regret it later.

**Comment by atrick** [comment]
Great, I'll put up a PR with this constant in a Swift header (I was only looking at include/lldb, which doesn't actually include swift).

**Comment by jimingham** [comment]
> Great, I'll put up a PR with this constant in a Swift header (I was only looking at include/lldb, which doesn't actually include swift).

Yes, swift is all handled by particular "lldb plugins".  lldb/include only has the generic plugin interfaces.  All the actual plugins are private to themselves, and those are the ones that include swift headers.

**Comment by atrick** [comment]
Swift header with the sentinel value: https://github.com/apple/swift/pull/36395

**Comment by atrick** [comment]
@adrian-prantl fyi, when printing a deinitialized object, we do also see a JIT error after the expected diagnostic
```
error: Couldn't materialize: variable b has been deinitialized
error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression
```

**Comment by atrick** [comment]
@adrian-prantl May want to add an Optional test case while you're at it
```
private class K {
  init() {}
}

private func readKRetInt(_ f: K?) -> Int {
  return 2
}

func useInt(_ i: Int) {
  print(i)
}

public func main() {
  let b: K? = K()
  let y = readKRetInt(b)
  useInt(y)
}

main()
```

**Comment by adrian-prantl** [comment]
> `error: Couldn't materialize: variable b has been deinitialized`
> `error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression`

Yes, that is expected that's just how materializer errors are printed. But you raise good point, I have no idea if the second line is helpful at all. Not for the end user and probably not for the LLDB developers either.

**Pull request closed without merging**
