### PR TITLE
Fix Reproducer/TestDriverOptions.test in swift/master

### PR DESCRIPTION
**Pull request by vedantk**

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
Thanks!

**Comment by vedantk** [comment]
@JDevlieghere heads-up, I tried cherry-picking this to swift/master-next, but the test is not present there. I guess that's just due to the swift/master -> swift/master-next automerger being down?

**Comment by JDevlieghere** [comment]
@vedantk There is no automerger from swift/master -> swift/master-next in the monorepo. The test should be there though, but probably under `test/Shell` rather than `lit`?

**Comment by vedantk** [comment]
@JDevlieghere The test is present under `test/Shell`, but it looks substantially different. Should we tackle this in the rebranch or now?

**Comment by JDevlieghere** [comment]
Right, totally my fault, I don't think I cherry-picked the swift-only change from `master` to `master-next`, sorry. I'll do that right now.

**Comment by JDevlieghere** [comment]
Pushed it 
```
To github.com:apple/llvm-project.git
   c07e3062960a..ed5aace8b9a6  swift/master-next -> swift/master-next
```

**Pull request merged**
