### PR TITLE
[NFC][compiler-rt] disable frexpl_interceptor test

### PR DESCRIPTION
**Pull request by aralisza**
Disable this test only in this branch. rdar://81224953

### CODE REVIEW

**Comment by aralisza** [comment]
@swift-ci please test

**Comment by delcypher** [comment]
You could also use `UNSUPPORTED:` here to stop it from running. `XFAIL` will mean it still runs but we expect to fail. You should check if this also affects running on iossim.

**Comment by aralisza** [comment]
Looks like the iossim test is passing right now without this, only ios is affected

**Comment by aralisza** [comment]
@swift-ci please test

**Comment by aralisza** [comment]
@swift-ci please test

**Comment by aralisza** [comment]
@swift-ci please test

**Comment by aralisza** [comment]
@swift-ci please test

**Comment by aralisza** [comment]
@swift-ci please test

**Comment by aralisza** [comment]
@swift-ci please test

**Comment by aralisza** [comment]
@swift-ci please test

**Pull request merged**
