### PR TITLE
Update Swift reflection library name

### PR DESCRIPTION
**Pull request by Azoy**
As per https://github.com/apple/swift/pull/62846, use the new name for this library.

### CODE REVIEW

**Review by mikeash — APPROVED** [review]

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
https://github.com/apple/swift/pull/62846
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test macOS

**Comment by Azoy** [comment]
https://github.com/apple/swift/pull/62846
@swift-ci please test macOS

**Pull request merged**
