### PR TITLE
Implement TypeSystemSwiftTypeRef::IsErrorType()

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by kastiglione — COMMENTED** [review]
Should `IsErrorType` return true for types that conform to `Swift::Error`?

**Comment by adrian-prantl** [comment]
The name would suggest so, but looking at the uses of this utility, we can probably get away with just existentials conforming to Error (i.e., the way it is implemented now.)

**Comment by adrian-prantl** [comment]
I also realized that I no longer need this function, so maybe I'll just close this PR...

**Pull request closed without merging**
