### PR TITLE
Pr depscan daemon

### PR DESCRIPTION
**Pull request by cachemeifyoucan**

### CODE REVIEW

**Review by dexonsmith — APPROVED** [review]
LGTM

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
Ah, I see, I need to fix the failure. macOS has a 104 character limit for path of the socket so if the test directory name is too long, this will fail.

**Comment by dexonsmith** [comment]
> Ah, I see, I need to fix the failure. macOS has a 104 character limit for path of the socket so if the test directory name is too long, this will fail.

Test could add `REQUIRES: shell` and use `mktemp` to generate the socket file. But we'd want to clean it up, too, which the `%t` normally handles for us (because it's in the build directory).

Another option is for the daemon to create a socket itself (using `generateUniqueName()`) and register it for deletion with `removeFileOnSignal()`, then write the path to the socket into the depscand file (rather than the despcand file *being* the socket).

BTW, I'm a bit concerned that a daemon launched for testing could end up running "forever" if the test fails so the shutdown never happens. Is there a way we can mitigate against that?

**Comment by cachemeifyoucan** [comment]
> > Ah, I see, I need to fix the failure. macOS has a 104 character limit for path of the socket so if the test directory name is too long, this will fail.
> 
> Test could add `REQUIRES: shell` and use `mktemp` to generate the socket file. But we'd want to clean it up, too, which the `%t` normally handles for us (because it's in the build directory).
> 
> Another option is for the daemon to create a socket itself (using `generateUniqueName()`) and register it for deletion with `removeFileOnSignal()`, then write the path to the socket into the depscand file (rather than the despcand file _being_ the socket).
> 
> BTW, I'm a bit concerned that a daemon launched for testing could end up running "forever" if the test fails so the shutdown never happens. Is there a way we can mitigate against that?

I actually just did an implementation of the generateUniqueName in the temp directory then I realize:
* Temp directory can have very long path too
* There is more coding need to do just to pass that around because I try to give user control when to end it. We can just let the start daemon to print the socket to stdout then it is not easy to pass from an output to another command easily if the tool doesn't support that.

So I do an easy/reliable but less portable way. I check the length of the build directory in lit and only run the tests when the directory is short. Unfortunately it won't be caught in CI because of the path but it is better than nothing or a flaky test.

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by dexonsmith** [comment]
@cachemeifyoucan , any comments on this?

> BTW, I'm a bit concerned that a daemon launched for testing could end up running "forever" if the test fails so the shutdown never happens. Is there a way we can mitigate against that?

**Comment by cachemeifyoucan** [comment]
> @cachemeifyoucan , any comments on this?
> 
> > BTW, I'm a bit concerned that a daemon launched for testing could end up running "forever" if the test fails so the shutdown never happens. Is there a way we can mitigate against that?

What do you think if I make global daemon a unique location so only one global daemon can be launched? So the worst case one will be leaked.

Also maybe good to rewrite the tests to be self contained so all the commands are running in a unit test instead of leaving daemon behind? I don't have a perfect solution for this.

**Comment by dexonsmith** [comment]
I don't think a unique location would be great.

What about adding a `-fdepscan-daemon-timeout=5` flag to use when starting, which causes automatic shutdown after 5s? You can use that in all the tests.

**Pull request merged**
