### PR TITLE
[Analyzer] Cherry pick bugfixes in clang checker and clang-tidy

### PR DESCRIPTION
**Pull request by usama54321**
Removed extra space from NSErrorChecker debug message and updated relevant tests.

### CODE REVIEW

**Comment by usama54321** [comment]
@swift-ci test

**Comment by haoNoQ** [comment]
@swift-ci test

**Review by t-rasmud — APPROVED** [review]
LGTM!

**Comment by haoNoQ** [comment]
Looks like some unrelated tests failed. Let's restart.

@swift-ci test

**Comment by haoNoQ** [comment]
Looks like it's still stuck, let's try again.

@swift-ci test

**Comment by haoNoQ** [comment]
Ok just keep punching.

@swift-ci test

**Comment by haoNoQ** [comment]
@swift-ci test

**Comment by usama54321** [comment]
@swift-ci test

**Comment by usama54321** [comment]
@swift-ci test

**Comment by haoNoQ** [comment]
@swift-ci test

**Comment by haoNoQ** [comment]
> All checks have passed

YES that's how we do it at Apple!!

**Review by haoNoQ — APPROVED** [review]

**Pull request closed without merging**
