### PR TITLE
[lldb] Use add_custom_command for SBLanguages.h (#91254)

### PR DESCRIPTION
**Pull request by JDevlieghere**
Use add_custom_command instead of add_custom_target to generate SBLanguages.h.

(cherry picked from commit 3809e20afc68d7d03821f0ec59b928dcf9befbf4)

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test macos

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test windows

**Review by adrian-prantl — APPROVED** [review]

**Pull request merged**
