### PR TITLE
Disable 'DisplayDebuggerGeneratedModule' when generating a display string from TypeSystemSwiftTypeRef

### PR DESCRIPTION
**Pull request by augusto2112**

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]

**Comment by kastiglione** [comment]
> when generating a display string from `TypeSystemSwiftTypeRef`

when was this happening?

**Comment by augusto2112** [comment]
> > when generating a display string from `TypeSystemSwiftTypeRef`
> 
> when was this happening?

It's not happening yet! After I change `GetDynamicTypeAndAddress_Protocol` to get typerefs it will start happening.

**Comment by kastiglione** [comment]
> After I change `GetDynamicTypeAndAddress_Protocol` to get typerefs it will start happening.

how does this related to debugger generated modules?

**Comment by augusto2112** [comment]
> > After I change `GetDynamicTypeAndAddress_Protocol` to get typerefs it will start happening.
> 
> how does this related to debugger generated modules?

Without this change we would print `$lldb_expr.ClassName` instead of just `ClassName` in some situations. `$lldb_expr` is the debugger generated module.

**Comment by adrian-prantl** [comment]
This is about new types defined in expressions.

**Comment by kastiglione** [comment]
ah thanks Adrian

**Pull request merged**
