### PR TITLE
[lldb] Use correct log API inSwiftLanguageRuntimeDynamicTypeResolution (NFC)

### PR DESCRIPTION
**Pull request by kastiglione**

### CODE REVIEW

**Comment by kastiglione** [comment]
This can go in now, or later, either is fine.

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test windows

**Review by adrian-prantl — APPROVED** [review]
Clearly good, though if we could convert this to LLDB_LOG, and skip the string conversions that would be even nicer!

**Pull request merged**
