### PR TITLE
[AArch64] Fix crash caused by performExtractVectorEltCombine on DUP nodes with float operands.

### PR DESCRIPTION
**Pull request by asavonic**
This is a cherry-pick of 872924fab4e6. 
Fixes issue [#65422 ](https://github.com/apple/swift/issues/65422) "[Autodiff] Assertion failure SIMD AArch64"

Reviewed By: dmgreen

Differential Revision: https://reviews.llvm.org/D148705

### CODE REVIEW

**Comment by asl** [comment]
@swift-ci please test

**Comment by asl** [comment]
@TNorthover Will you please merge when you have a chance? And probably to 5.9 branch as well

Thanks!

**Comment by TNorthover** [comment]
I think this branch is locked down with forms in triplicate to make any changes, and goodness knows about 5.9 that's Swift stuff.

**Comment by asl** [comment]
@TNorthover how can we proceed then? Where the pull request should be submitted to? I do see lots of PRs merged into this branch though.

**Comment by asl** [comment]
Tagging @BradLarson

**Comment by asl** [comment]
ping

@compnerd @tkremenek What are the steps to have this backport of bugfix comitted? The compiler crash could be reproduced by the plain swift code in the latest nightly swift toolchain snapshot (see https://github.com/apple/swift/issues/65422)

**Comment by compnerd** [comment]
@TNorthover main builds against this branch, we haven’t rebranched yet.

**Comment by tkremenek** [comment]
CC @Gerolf-Apple @airspeedswift

**Comment by tkremenek** [comment]
@airspeedswift please evaluate on whether or not this should go into 5.9

**Comment by asl** [comment]
@airspeedswift @Gerolf-Apple @tkremenek Any update here?

Thanks!

**Comment by asl** [comment]
Thanks!

**Pull request merged**
