### PR TITLE
Revert "[libclang][deps] Add getFileDependencies_v3 that provides whole command lines"

### PR DESCRIPTION
**Pull request by ahmedbougacha**
This reverts commit 569a95b62c2029c970927c31cec71aaf87566809.

Reverted from next in eb2b124dd99b.

rdar://97126577

### CODE REVIEW

**Comment by ahmedbougacha** [comment]
@swift-ci test

**Comment by ahmedbougacha** [comment]
@swift-ci test

**Comment by ahmedbougacha** [comment]
@swift-ci test

**Comment by benlangmuir** [comment]
Build should be fixed by https://github.com/apple/llvm-project/pull/5026, I think we can close this.

**Pull request closed without merging**
