### PR TITLE
Cherry-Pick -enable-swifttail-musttail-check flag

### PR DESCRIPTION
**Pull request by etcwilde**
This is a cherry-pick of https://github.com/apple/llvm-project/pull/2766 onto the swift/next branch.

Resolves: rdar://78628967

### CODE REVIEW

**Review by varungandhi-apple — APPROVED** [review]
Shouldn't this have come in through an automerger? I'm surprised as to why `next` needs to updated manually for this flag...

**Comment by varungandhi-apple** [comment]
Ah, nvm, I originally landed it on apple/stable, and there's no automerger from there to next.

**Comment by varungandhi-apple** [comment]
There's one more change related to this though with NDEBUG.

**Comment by varungandhi-apple** [comment]
https://github.com/apple/llvm-project/pull/3004 <- You can cherry-pick this too for consistency.

**Comment by etcwilde** [comment]
> There's one more change related to this though with NDEBUG.

That's why I requested your review. Thanks for noting that.

**Comment by etcwilde** [comment]
> #3004 <- You can cherry-pick this too for consistency.

Commit cherry-picked. Thanks!

**Pull request merged**
