### PR TITLE
Cherrypick SymbolLocator plugin

### PR DESCRIPTION
**Pull request by JDevlieghere**

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test windows

**Comment by JDevlieghere** [comment]
`InterfaceHash/edited_property_getter.swift` is flakey. 

@swift-ci test windows

**Comment by jasonmolenda** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test windows

**Pull request merged**
