### PR TITLE
[asan][windows] Make tests more flexable (#85274) (Cherrypick)

### PR DESCRIPTION
**Pull request by usama54321**
Contains test changes from
https://github.com/llvm/llvm-project/pull/81677 that are simple test changes. For the most part just makes the tests allow more flexibility in the callstacks produced by asan.

Note: this PR has the exact changes from
https://github.com/llvm/llvm-project/pull/81677 in addition to a revert commit to remove the ones that require other things from that PR. This will be squashed, ofc. I just left things unsquashed for reviewing pleasure :).

This is a non-functional-change

### CODE REVIEW

**Comment by usama54321** [comment]
@swift-ci test

**Comment by usama54321** [comment]
@swift-ci test platform windows

**Comment by usama54321** [comment]
@swift-ci Please test Windows platform

**Review by devincoughlin — APPROVED** [review]
This is a test-only change.

**Pull request merged**
