### PR TITLE
[lldb] Re-enable TestSwiftTaskSwitch

### PR DESCRIPTION
**Pull request by kastiglione**

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test

**Review by bulbazord — APPROVED** [review]
Let's do it!

**Comment by kastiglione** [comment]
Letting it run tests on CI

**Comment by etcwilde** [comment]
Do we know why this test is passing now?

**Comment by kastiglione** [comment]
@etcwilde Felipe (@felipepiovezan) suggested it was fixed by this https://github.com/apple/llvm-project/pull/7489

**Comment by etcwilde** [comment]
Okay, cool. Thank you. Just wanted to check that there was an associated change and we weren't just pulling the xfail off because "it looks fine on the bots". That PR looks like it was merged reasonably within the timeframe that the test started UPASS'ing.

**Review by etcwilde — APPROVED** [review]
The failures on macOS look consistent with re-enabling this test.
These are current. 
```
2 warning(s) in tests
********************
Failed Tests (3):
  lldb-api :: lang/cpp/std-function-step-into-callable/TestStdFunctionStepIntoCallable.py
  lldb-api :: lang/objc/real-definition/TestRealDefinition.py
  lldb-api :: lang/swift/async/stepping/step-in/TestSwiftStepInAsync.py

********************
Unexpectedly Passed Tests (2):
  lldb-api :: lang/swift/async/stepping/step-in/task-switch/TestSwiftTaskSwitch.py
  lldb-shell :: Register/x86-64-write.test
```

The test failures on the macOS bot for this PR are the same, but without the UPASS in `TestSwiftTaskSwitch.py`.

**Comment by etcwilde** [comment]
Windows Swift failures are known. We aren't yet to testing LLDB there, so this should be fine in that regard.
```
Failed Tests (6):
  Swift(windows-x86_64) :: DebugInfo/implicitreturn.swift
  Swift(windows-x86_64) :: Driver/Dependencies/only-skip-once.swift
  Swift(windows-x86_64) :: IRGen/c_globals.swift
  Swift(windows-x86_64) :: IRGen/framepointer.sil
  Swift(windows-x86_64) :: Interop/Cxx/operators/member-inline-irgen.swift
  Swift(windows-x86_64) :: Interop/Cxx/operators/member-out-of-line-irgen.swift
```

**Pull request merged**
