### PR TITLE
[arm64] Bring this branch in a compilable state.

### PR DESCRIPTION
**Pull request by dcci**

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@swift-ci test

**Comment by vedantk** [comment]
This looks like 72105b9dcd6 (Fix compilation error in ObjectFileMachO::ParseSymtab)? I think this is fine, though I guess apple/stable/20190619 would have been the canonical cherry-pick target.

**Comment by dcci** [comment]
That code doesn't exist on the dated branch as it predates the refactor. Hence the fix only on `swift/master`.

**Pull request merged**
