### PR TITLE
[lldb] Fix summary for strings with non printable unicode characters

### PR DESCRIPTION
**Pull request by poya**
Fix Swift's StringPrinterEscapingHelper incorrectly returning the
first byte of the UTF-8 representation instead of the Unicode code point
for non printable unicode characters.

https://bugs.swift.org/browse/SR-8111

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test

**Review by dcci — COMMENTED** [review]
I'm not a big unicode expert but this seems reasonable to me. I cc:ed @milseman as he understands this area much better than I do and can probably provide some more constructive feedback on this patch.

**Comment by poya** [comment]
This part of the Swift implementation seems to be a copy/paste adaptation of the default implementation in [DataFormatters/StringPrinter.cpp](https://github.com/apple/llvm-project/blob/f90f1663c5b22f7cfa87d762b170129a2d68f60b/lldb/source/DataFormatters/StringPrinter.cpp#L127) which is displaying the code point for Unicode characters. Most likely a copy/paste error from the handling of non printable ASCII characters.

**Comment by dcci** [comment]
I'll wait a bit in case Michael wants to comment -- otherwise I'll merge it. Please don't hesitate to ping this PR in case I forget.

**Review by dcci — APPROVED** [review]
LGTM.

**Comment by dcci** [comment]
Thanks, I forgot about this one.

**Pull request merged**
