### PR TITLE
Add dylib to list of binaries installed for this test.

### PR DESCRIPTION
**Pull request by jasonmolenda**
Add dylib to list of binaries installed for this test.
(cherry picked from commit 90a38aa5853da3fa04cc6af8ab8457fae2c0addd)

### CODE REVIEW

**Comment by jasonmolenda** [comment]
@swift-ci please test

**Comment by fredriss** [comment]
Looks like the branch is missing my patch for the extra_images argument

**Comment by jasonmolenda** [comment]
Yeah, you upstreamed it to swift/master-next in a578adc1bc8e17b147ed5ef4794cd6f3f82b584b on Nov 7 but it's not on swift-5.2-branch. This xfail isn't important enough to cherry pick that larger change.

**Comment by jasonmolenda** [comment]
(er, this wasn't an xfail, it was a fix for the test file; I was thinking of a different PR.  I already landed this fix to this test on swift/master-next, it's not critical to also get it on swift-5.2-branch.)

**Pull request closed without merging**
