### PR TITLE
Backport [lldb] Only set the executable module for a target once and fix build error

### PR DESCRIPTION
**Pull request by Teemperor**
This is backporting the `[lldb] Only set the executable module for a target once and fix build error`
and also fixes the build error in TypeSystemClang in the stable branch while I'm at it.

### CODE REVIEW

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by Teemperor** [comment]
```
19:41:56 /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DNDEBUG -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/libcxx/src -I/Users/buildnode/jenkins/workspace/apple-llvm-project-pr-macos/llvm-project/libcxx/src -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.16.sdk/usr/include/libxml2 -Iinclude -I/Users/buildnode/jenkins/workspace/apple-llvm-project-pr-macos/llvm-project/llvm/include -Iprojects/libcxx/include/c++build -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers  -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -O3  -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.16.sdk -mmacosx-version-min=10.15   -DLIBCXX_BUILDING_LIBCXXABI -UNDEBUG -nostdinc++ -fvisibility-inlines-hidden -fvisibility=hidden -Wall -Wextra -W -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wno-user-defined-literals -Wno-covered-switch-default -Wno-ignored-attributes -Wno-error -std=c++14 -MD -MT projects/libcxx/src/CMakeFiles/cxx_experimental.dir/experimental/memory_resource.cpp.o -MF projects/libcxx/src/CMakeFiles/cxx_experimental.dir/experimental/memory_resource.cpp.o.d -o projects/libcxx/src/CMakeFiles/cxx_experimental.dir/experimental/memory_resource.cpp.o -c /Users/buildnode/jenkins/workspace/apple-llvm-project-pr-macos/llvm-project/libcxx/src/experimental/memory_resource.cpp
19:41:56 /Users/buildnode/jenkins/workspace/apple-llvm-project-pr-macos/llvm-project/libcxx/src/experimental/memory_resource.cpp:9:10: fatal error: 'experimental/memory_resource' file not found
19:41:56 #include "experimental/memory_resource"
19:41:56          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19:41:56 1 error generated.
```

Seems like libc++ problems.

**Comment by fredriss** [comment]
@swift-ci test

**Comment by fredriss** [comment]
@swift-ci test macOS

**Comment by fredriss** [comment]
@swift-ci test

**Pull request merged**
