### PR TITLE
SymbolGraph ExtractAPI support for C and Objective-C in clang

### PR DESCRIPTION
**Pull request by daniel-grumberg**
Cherry-pick commits for llvm.org's main branch that implement support for Symbol Graph generation using clang for C and Objective-C headers, as mentioned in https://forums.swift.org/t/extending-swift-docc-to-support-objective-c-documentation/53243. Bringing in these changes would benefit the Swift community and facilitate support in SwiftPM and similar tooling.

These changes don’t affect regular compilation and instead introduce a new action to the clang frontend and driver. Most of the changes are self contained in the ExtractAPI library. An example clang invocation for generating a symbol graph would be:  
```sh
clang -extract-api -o MyFramework.symbols.json first-header.h second-header.h
```

Changes that affect the core compiler infrastructure are constrained to the driver, the frontend actions infrastructure and the ASTs infrastructure for comment processing.

 Changes to the driver consist of creating a new JobAction for the `-extract-api` option. The aim of this is to create a single CC1 invocation that takes all the header files provided on the command line as inputs for further processing by the frontend. These changes can be found in the following files.:
- clang/include/clang/Basic/DiagnosticDriverKinds.td
- clang/include/clang/Driver/Action.h
- clang/include/clang/Driver/Options.td
- clang/include/clang/Driver/Types.def
- clang/lib/Driver/Action.cpp
- clang/lib/Driver/Driver.cpp
- clang/lib/Driver/ToolChain.cpp
- clang/lib/Driver/ToolChains/Clang.cpp
- clang/lib/Driver/Types.cpp

In CC1 itself the only new changes that aren’t self contained are to construct the appropriate new frontend action for the provided headers instead of performing a regular build. These changes can be found in the following files:
- clang/lib/Frontend/CompilerInvocation.cpp
- clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp
- clang/include/clang/Frontend/FrontendActions.h
- clang/include/clang/Frontend/FrontendOptions.h

In the AST comment processing infrastructure we introduced a new API for getting a list of comment lines with associated source locations to enable correct symbol graph generation. This new interface is only exercised by the ExtractAPI library. This new interface is defined and implemented in the following files:
- clang/lib/AST/RawCommentList.cpp
- clang/include/clang/AST/RawCommentList.h 

The rest of the changes are in the ExtractAPI library implement the new frontend action for Symbol Graph generation. These are fully self contained and will not affect the rest of the compiler.

### CODE REVIEW

**Comment by daniel-grumberg** [comment]
@swift-ci please test

**Comment by daniel-grumberg** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by zixu-w** [comment]
Failed test: https://github.com/apple/swift/blob/main/test/SourceKit/CursorInfo/cursor_symbol_graph_objc.swift#L243-L278
This is caused by the new `clang::RawComment::getFormattedLines`, which tries to fix the problem where an extra newline is added at the end of a block comment.

**Comment by bnbarham** [comment]
You'll want to grab https://github.com/zixu-w/swift/commit/1ed123e04594ca55dda4447b31d20d4498b985a3 on swift `release/5.7` to avoid spurious errors there.

**Comment by daniel-grumberg** [comment]
@swift-ci please test

**Comment by daniel-grumberg** [comment]
@swift-ci please test

**Review by ributzka — APPROVED** [review]
This is an isolated change, so I am good with taking it.

**Pull request merged**
