### PR TITLE
[OnDiskCAS] Refactor `OnDiskCAS` and decouple it from the `ObjectStore` implementation

### PR DESCRIPTION
**Pull request by akyrtzi**
This is useful for making the `OnDiskCAS` API accessible and able to evolve decoupled from the `ObjectStore` API.

One notable difference is that `OnDiskCAS` allows creating references for non-stored objects, while `ObjectStore` remains unchanged and does not support it.

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
Each commit is self-contained, it may be easier to review by commit.

**Comment by cachemeifyoucan** [comment]
Note the build error due to older compiler version. I like the new names in OnDiskCAS slight better.

Before reading the PR, my expectation was the other way that `OnDiskObjectStore` is the API that get exposed (that is a clean API with more APIs and customization possibility than default ObjectStore). Exposing all the internal bit patterns in the data structure is a lot. Is there anything you want to do that relies on those information?

Also worried about windows build. You can only verify that by putting onto stable branch and fake a swift PR to test that.

**Comment by akyrtzi** [comment]
> Before reading the PR, my expectation was the other way that `OnDiskObjectStore` is the API that get exposed (that is a clean API with more APIs and customization possibility than default ObjectStore).

`OnDiskObjectStore` being an implementation of `ObjectStore` seems natural, I'm worried it would be a bit confusing to have a `OnDiskObjectStore` class that doesn't actually subclass `ObjectStore`.
Do you think it would be better to keep `OnDiskCAS` as subclass of `ObjectStore` and create `OnDiskObjectStore` as a separate self-contained class?

> Exposing all the internal bit patterns in the data structure is a lot. Is there anything you want to do that relies on those information?

Good point, I'll look into what doesn't need to be in the header.

> Also worried about windows build. You can only verify that by putting onto stable branch and fake a swift PR to test that.

I'll give it a try; I assume this will only help me see if it builds, do we have any way to also run the llvm tests on windows via a PR?

**Comment by cachemeifyoucan** [comment]
> `OnDiskObjectStore` being an implementation of `ObjectStore` seems natural, I'm worried it would be a bit confusing to have a `OnDiskObjectStore` class that doesn't actually subclass `ObjectStore`. Do you think it would be better to keep `OnDiskCAS` as subclass of `ObjectStore` and create `OnDiskObjectStore` as a separate self-contained class?
> 

Names can be changed but I was thinking have current `OnDiskCAS` to be a shared implementation details to two separate classes, one is the subclass of `ObjectStore` and one is the new API for someone just need a OnDisk persistent CAS.

> 
> > Also worried about windows build. You can only verify that by putting onto stable branch and fake a swift PR to test that.
> 
> I'll give it a try; I assume this will only help me see if it builds, do we have any way to also run the llvm tests on windows via a PR?

Just build is enough. Basically check the build still passes when OnDiskCAS is disabled and windows environment.

**Comment by akyrtzi** [comment]
> Names can be changed but I was thinking have current `OnDiskCAS` to be a shared implementation details to two separate classes, one is the subclass of `ObjectStore` and one is the new API for someone just need a OnDisk persistent CAS.

I want to have separation of concerns, specifically I want (1) a self-contained on-disk store implementation that doesn't need to subclass from `ObjectStore` at all and is hash-algorithm independent, and (2) a `ObjectStore` subclass that is implemented by wrapping (1) and extending it with the hashing algorithm from `BuiltinCAS`.

Something like this:
1. (on-disk store)
2. (on-disk `ObjectStore`) --> implements `ObjectStore` API --> wraps (on-disk store) + `BuiltinObjectHasher`

Conceptually I like "OnDiskObjectStore" as the name for (1) in isolation, but it'd be strange if that wasn't the name for the `ObjectStore` subclass.
Alternatively we could keep `OnDiskCAS` to be the subclass and use `OnDiskDB` for the self-contained one, like this:

1. `OnDiskDB`
2. `OnDiskCAS` --> implements `ObjectStore` API --> wraps `OnDiskDB` + `BuiltinObjectHasher`

What do you think?

**Comment by cachemeifyoucan** [comment]
We already have an abstraction like that, basically your `OnDiskDB` minus all the data storage type. That abstraction is `OnDiskHashMapTrie`. You do need to replicate the logics for bit patterns and logics for where to store the data content.
 
After the change, we will have:
`OnDiskHashMapTrie` + CASDataStorage -> `OnDiskDB` + BuiltinObjectHasher -> `OnDiskCAS`

If that is not too many abstractions, I am fine with that.

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by akyrtzi** [comment]
Updates:
* Renamed `OnDiskCAS` -> `OnDiskGraphDB` and `OnDiskObjectStore` -> `OnDiskCAS`. Reverted to using `OnDiskCAS` for the `ObjectStore` subclass while `OnDiskGraphDB` is the underlying on-disk CAS nodes storage that is independent of a particular hash algorithm.
* Moved implementation details out of the `OnDiskGraphDB.h` header.

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by cachemeifyoucan** [comment]
LGTM. Just wondering why it is called `Graph`DB?

**Comment by akyrtzi** [comment]
> LGTM. Just wondering why it is called `Graph`DB?

`OnDiskDB` is too generic (what's the `DB`, is it a key-value DB?), I wanted a more specific name and since it's designed to store DAG nodes I thought `OnDiskGraphDB` is apt.

**Comment by cachemeifyoucan** [comment]
Maybe the old name of `OnDiskCAS` and `OnDiskObjectStore` is better but I am not good at names too.

**Review by cachemeifyoucan — APPROVED** [review]

**Comment by akyrtzi** [comment]
I got windows building successfully using PR testing from https://github.com/apple/swift/pull/63241

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Pull request merged**
