### PR TITLE
[lldb] Fix merge after r375160

### PR DESCRIPTION
**Pull request by smeenai**
Adjust the Swift LLDB changes accordingly.

### CODE REVIEW

**Comment by hyp** [comment]
@smeenai does this fix a build problem? I can merge this in.

**Comment by hyp** [comment]
@swift-ci please test

**Comment by smeenai** [comment]
Yup, this fixes LLDB compilation on swift/master-next.

The CI build failure seems like an infra issue?

**Comment by hyp** [comment]
@swift-ci please test

**Comment by smeenai** [comment]
The CI now seem to be unhappy about the swift/master-next branch not existing on swift-format, as far as I can tell?

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
Can't test this. @adrian-prantl Can you confirm this is ok to merge?

**Review by adrian-prantl — APPROVED** [review]
Thanks!

**Pull request merged**
