### PR TITLE
[Swift] Update for VarDecl constructor change

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
https://github.com/apple/swift/pull/33989
@swift-ci Please test

**Review by adrian-prantl — APPROVED** [review]
Please don't forget to cherry-pick this to swift/master-next!

**Comment by slavapestov** [comment]
apple/swift#33989
@swift-ci Please test

**Comment by slavapestov** [comment]
https://github.com/apple/swift/pull/33989
@swift-ci Please test

**Pull request merged**
