### PR TITLE
[lldb] Make lldbVersion a full fledged library 

### PR DESCRIPTION
**Pull request by JDevlieghere**

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test macOS

**Comment by compnerd** [comment]
This is likely the cause of the Windows build regression: https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/495/console

**Pull request merged**
