### PR TITLE
Update for apple/swift#31506

### PR DESCRIPTION
**Pull request by hamishknight**

### CODE REVIEW

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/30269

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/30269

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/30269

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/30269

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/30269

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/31506

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/31506

@swift-ci please test

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/31506

@swift-ci please test Linux

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/31506

@swift-ci please test Linux

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/31506

@swift-ci please test Linux

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/31506

@swift-ci please test Linux

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/31506

@swift-ci please test Linux

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/31506

@swift-ci please test Linux

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/31506

@swift-ci please test Linux

**Comment by hamishknight** [comment]
https://github.com/apple/swift/pull/31506

@swift-ci please test Linux

**Comment by shahmishal** [comment]
apple/swift#31506

@swift-ci please test Linux

**Pull request merged**
