### PR TITLE
[lldb] Skip the PlatformMacOSXTest test if not on Apple platforms

### PR DESCRIPTION
**Pull request by augusto2112**

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
This looks reasonable, but shouldn't we make this change on llvm.org and cherry-pick?

**Comment by adrian-prantl** [comment]
Actually, I'm not sure if this looks reasonable. When remote debugging a mac App from Linux, wouldn't you need PlatformMacOSX?

**Comment by adrian-prantl** [comment]
What's the motivation behind this?

**Comment by augusto2112** [comment]
I think I misunderstood the test then, I thought it was meant to only run on macOS. The motivation behind it is that this test is the only one failing in the Ubuntu CI: https://ci.swift.org/view/LLDB/job/oss-lldb-linux-ubuntu-18_04/822/console

**Comment by adrian-prantl** [comment]
Hmm.. this is odd:

**Comment by adrian-prantl** [comment]
```
commit b783e5c203c1959e04fc351a2e96f0700decc32c
Author: Jonas Devlieghere <jonas@devlieghere.com>
Date:   Tue Mar 15 09:29:39 2022 -0700

    [lldb] Make the PlatformMacOSX unit test Apple specific
    
    I thought that x86GetSupportedArchitectures would always return
    x86_64-apple-macosx as a compatible architecture, regardless of the host
    achitecture, but the Debian bot disagrees with that.
```

**Comment by adrian-prantl** [comment]
I guess there's nothing wrong with cherry-picking that patch then. But I'm wondering if it's basically indicating that remote debugging a mac binary isn't supported on all platforms?
@JDevlieghere ^

**Review by adrian-prantl — APPROVED** [review]

**Pull request merged**
