### PR TITLE
Update test for https://github.com/apple/swift/pull/74201

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
https://github.com/apple/swift/pull/74201
@swift-ci Please test

**Comment by adrian-prantl** [comment]
`swift/release/6.0` automerges to `stable/20230725`, however, you'll want to cherry-pick this to `next` instead (which doesn't receive automerges).

**Review by adrian-prantl — COMMENTED** [review]
Can you rebase this on `next` instead?

**Pull request merged**
