### PR TITLE
Fix compilation error with clang-10

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test llvm

**Comment by rastogishubham** [comment]
It seems that @etcwilde has one of these issues fixed in https://github.com/apple/llvm-project/pull/7676

**Review by rastogishubham — APPROVED** [review]
LGTM but please look at comment about @etcwilde 's PR

**Review by etcwilde — APPROVED** [review]
LGTM. Looks like I missed one of the missing `std::move`'s from the `llvm-cas` tool.

**Comment by adrian-prantl** [comment]
@swift-ci test llvm

**Comment by etcwilde** [comment]
#7676 already merged. This change should be a no-op if you rebase now.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request closed without merging**
