### PR TITLE
[lldb] Cherry-picks from ToT

### PR DESCRIPTION
**Pull request by medismailben**
This patch contains a bunch of fix and improvements cherry-picked from the top-of-tree llvm repo, namely:
- Fixes for JSON ObjectFile module loading
- Add the ability to load inlined symbols from crash report files
- Fix a PID parsing issue in crash report
- Remove tempfile prefix from module list
- Fix a racing issue when loading inlined symbols in a scripted process
- Create an interactive crashlog session with no target binary
- Disable variable watchpoint when the variable goes out of scope

This PR also contains some python re-formatting patches.

### CODE REVIEW

**Comment by medismailben** [comment]
@swift-ci test

**Comment by medismailben** [comment]
@swift-ci test

**Comment by medismailben** [comment]
@swift-ci test windows platform

**Comment by JDevlieghere** [comment]
I discussed this offline with @medismailben and he'll split up the PR into multiple PRs that are easier to review. All the changes here are related, but there's to much too meaningfully decide whether this is safe to go in or not.

**Comment by medismailben** [comment]
@JDevlieghere @adrian-prantl I've tried to split this across #7009 #7010 #7012 #7014 & #7015

**Pull request closed without merging**
