### PR TITLE
Revert Alexis' ns_error_domain changes from swift/main

### PR DESCRIPTION
**Pull request by hyp**

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@xymus I'm reverting your changes as they broke the CI (74168319) and they aren't actually present in the apple/stable branch, so the branches have diverged in the clang contents. I made a separate PR for apple/stable that fixes the nserrordomain attribute: https://github.com/apple/llvm-project/pull/2634

**Review by xymus — APPROVED** [review]
Thanks!

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test linux

**Pull request merged**
