### PR TITLE
[debug-info] Commits from stable/20211026 for move function support

### PR DESCRIPTION
**Pull request by gottesmm**
Just a series of commits that I did on stable/20211026 that need to be merged into next before the next stable merge.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
Could you please squash this into one LLVM and one LLDB commit?

**Comment by adrian-prantl** [comment]
Otherwise cherry-picking this will be messy

**Comment by gottesmm** [comment]
Ok.

**Comment by gottesmm** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
Failed for a different reason in compiler-rt, going to try again before merging.

**Comment by gottesmm** [comment]
Still failing in compiler-rt. Just going to merge.

**Pull request merged**
