### PR TITLE
Rsundahl/fuzzerbigfile2

### PR DESCRIPTION
**Pull request by rsundahl**
@swift-ci please test

### CODE REVIEW

**Comment by rsundahl** [comment]
CCC:

Explanation: This PR captures a fuzzer fix intended for internal/clang/1500 but was missed because the original PR was in review during the switchover to stable/swift/5.9 in early April.

Radar: rdar://99384640

Scope: Fuzzer

Risk: Low. The change is narrow in scope and has been upstream since early April.

Testing: Fuzzer test suite exercises this change extensively and has been passing both locally and upstream.
NB: The test for the change itself involves creating a 3GB file. The bulk of the commits in this PR ratchet back testing to macOS only due to testing infrastructure limitations on devices which fail to handling test artifacts as large as 3GB. This should not be interpreted as lack of testing on devices. The change is present in all of the existing fuzzer tests that are run on the device.

Reviewed by: yln

**Review by yln — APPROVED** [review]
This is the cherry-pick of replacing printf() with fputs()+fflush() to avoid hanging on very large outputs, right?

LGTM!

**Comment by rsundahl** [comment]
That is correct. Thanks for the quick review Julian! 🙂

**Comment by zoecarver** [comment]
@swift-ci please test

**Comment by rsundahl** [comment]
@swift-ci please smoke test

**Comment by zoecarver** [comment]
@swift-ci please smoke test

**Comment by rsundahl** [comment]
@swift-ci please benchmark

**Comment by zoecarver** [comment]
@swift-ci please benchmark

**Comment by zoecarver** [comment]
@swift-ci benchmark

**Comment by rsundahl** [comment]
@swift-ci test windows

**Comment by rsundahl** [comment]
@swift-ci test windows platform

**Comment by zoecarver** [comment]
@swift-ci test windows

**Comment by rsundahl** [comment]
@swift-ci please test

**Comment by rsundahl** [comment]
Thanks @shahmishal for enabling the swift-ci requests for my userid. (Sorry for the many one-lines in the comments above everbody else.)

**Review by devincoughlin — APPROVED** [review]

**Pull request merged**
