### PR TITLE
[TableGen] Fix default and description of UseAllCompilerFlags

### PR DESCRIPTION
**Pull request by JDevlieghere**
This tablegen entry was copy/pasted with the wrong default and
description. This fixes that.

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Review by adrian-prantl — APPROVED** [review]
Thanks!

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test

**Pull request merged**
