### PR TITLE
[lldb] Improve swift-healthcheck help message (NFC)

### PR DESCRIPTION
**Pull request by kastiglione**
rdar://93660209

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
Would be good to add expect line to the existing healthcheck test to make sure at least some help is being printed

**Review by ghost — APPROVED** [review]
#

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
Thanks!

**Pull request merged**
