### PR TITLE
Unxfail passing test

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by vedantk** [comment]
The macOS bot appears to have flagged a new issue:
```
Process 35958 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = step in
    frame #0: 0x000000010003e8bb Benchmark_Onone-x86_64-apple-macosx10.9`specialized TestConfig.init(registeredBenchmarks=1000 values) at DriverUtils.swift:149 [opt]
   146 	    }
   147 	
   148 	    // Configure the command line argument parser
-> 149 	    let p = ArgumentParser(into: PartialTestConfig())
   150 	    p.addArgument("--num-samples", \.numSamples,
   151 	                  help: "number of samples to take per benchmark;\n" +
   152 	                        "default: 1 or auto-scaled to measure for\n" +
Target 0: (Benchmark_Onone-x86_64-apple-macosx10.9) stopped.

None != 1024
failing type was $s11DriverUtils10TestConfigVyACSay05TestsB013BenchmarkInfoVGcfc07PartialcD0L_VD
Assertion failed: (equivalent && "TypeSystemSwiftTypeRef diverges from SwiftASTContext"), function GetBitSize, file /Users/buildnode/jenkins/workspace/apple-llvm-project-pr-macos/llvm-project/lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp, line 2107.
```

**Comment by vedantk** [comment]
Really excited to see this moving forward :)!

**Comment by adrian-prantl** [comment]
@vedantk I don't understand what's going on here. I did try this locally and got an XPASS, but now this one fails with a comparison failure. Is that due to the complexity of the test, or did something regress in the very short time in between? The failure is no longer due to typeref assertion, at least.

**Comment by vedantk** [comment]
> @vedantk I don't understand what's going on here. I did try this locally and got an XPASS, but now this one fails with a comparison failure. Is that due to the complexity of the test, or did something regress in the very short time in between? The failure is no longer due to typeref assertion, at least.

I suspect the issue is that it's a (very rapidly) moving target, as swift compiler changes landing on the 5.4 branch can affect codegen within the benchmarks, which in turn can surface new issues. The branch and the bot environment are two other variables. One explanation I don't think is likely is nondeterminism in the stepping script: it's not using randomness, and SKIP_N_FRAMES_BETWEEN_INSPECTIONS is set to 0 so we never skip any frames.

**Comment by adrian-prantl** [comment]
The rapidly-moving target sounds plausible, thanks!

**Comment by vedantk** [comment]
Hold on, check this out: `at DriverUtils.swift:149 [opt]`. We're not supposed to run the stepper tests if DriverUtils is built with optimization enabled. That might be the issue (we don't support debugging optimized swift code).

**Pull request closed without merging**
