### PR TITLE
[lldb] Update crashlog.py to accept multiple results from mdfind

### PR DESCRIPTION
**Pull request by JDevlieghere**
mdfind can return multiple results, some of which are not even dSYM
bundles, but Xcode archives (.xcrachive).

Currently, we end up concatenating the paths, which is obviously bogus.
This patch not only fixes that, but now also skips paths that don't have
a Contents/Resources/DWARF subdirectory.

rdar://81270312

Differential revision: https://reviews.llvm.org/D109263

(cherry picked from commit 4da5a446f818cd979868d830eced9770a886a5b6)

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
@swift-ci please test

**Pull request merged**
