### PR TITLE
[LTO] Add logging for timing the remote cache queries

### PR DESCRIPTION
**Pull request by akyrtzi**

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Review by cachemeifyoucan — COMMENTED** [review]
Do you think we can time around `tryLoadingBuffer()` and `write()` so the time reporting works for all caching methods?

I know this is for different scope, but if we want to know the time spent in GRPC, maybe we should put timer inside GRPCService instead?

**Comment by akyrtzi** [comment]
> Do you think we can time around `tryLoadingBuffer()` and `write()` so the time reporting works for all caching methods?

The concern with that is that it won't distinguish the timings between "cache lookup" and "cas load" (for `tryLoadingBuffer()`) and "cas save" and "cache update" (for `write()`)

> I know this is for different scope, but if we want to know the time spent in GRPC, maybe we should put timer inside GRPCService instead?

I prefer not to put in GRPCService only since that will go away at some point in the future. But that reminds me that I should add timings for `CASModuleCacheEntry` as well, since that's what is going to get used later on for distributed caching.

**Comment by akyrtzi** [comment]
>  should add timings for CASModuleCacheEntry as well

In https://github.com/apple/llvm-project/pull/7179/commits/f9dc1523fdd7fa8a2ca7785a6869bf8bfba2a2b2

**Review by cachemeifyoucan — APPROVED** [review]
Ok. LGTM

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Pull request merged**
