### PR TITLE
LLVM Support for Windows Macros

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]

**Comment by bnbarham** [comment]
Needs https://github.com/apple/llvm-project/pull/7406 as well

**Comment by bnbarham** [comment]
Also will need these on next + stable/20231013 😅 (though not the partial backport since it's already there)

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Pull request merged**
