### PR TITLE
[lldb] Cherry-pick changes to generate swig bindings from API headers instead of interface files

### PR DESCRIPTION
**Pull request by bulbazord**

### CODE REVIEW

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
@swift-ci please test

**Comment by bulbazord** [comment]
@swift-ci please test

**Review by medismailben — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
