### PR TITLE
build: always enable a dependency on intrinsics_gen

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @JDevlieghere @dcci

**Comment by JDevlieghere** [comment]
Thanks @compnerd!

**Comment by JDevlieghere** [comment]
@swift-ci please test macOS

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
`Swift(iphonesimulator-i386) :: attr/attr_originally_definedin_backward_compatibility.swift` doesnt seem related?  Swift has been broken for ~72 hours now :/

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by shahmishal** [comment]
@swift-ci please test macOS platform

**Pull request merged**
