### PR TITLE
[lldb] Support swiftlang tests with nested make invocations on Windows

### PR DESCRIPTION
**Pull request by weliveindetail**
Following the upstream patches https://github.com/llvm/llvm-project/pull/112342 and https://github.com/llvm/llvm-project/pull/112360, we can roll out the fix for the swiftlang-specific tests.

### CODE REVIEW

**Review by hjyamauchi — APPROVED** [review]

**Comment by weliveindetail** [comment]
Haha, this is how to get attention. To all the new reviewers: sorry for the noise, this is still a boring patch.

**Comment by hjyamauchi** [comment]
@swift-ci please test

**Comment by weliveindetail** [comment]
The Linux build failed, because the just-built Swift compiler hits an assertion in the standard library during CMake's "Check for working Swift compiler" step in swift-corelibs-libdispatch:
```
swift-frontend: /home/build-user/swift/stdlib/public/runtime/AccessibleFunction.cpp:110:
void swift::addImageAccessibleFunctionsBlockCallbackUnsafe(const void *, const void *, uintptr_t):
Assertion `size % sizeof(AccessibleFunctionRecord) == 0 && "accessible function section not a multiple of AccessibleFunctionRecord"' failed.
```

This is unrelated to my patch. LLDB built fine and testing didn't start yet. Previous premerge checks failed for the same reason since https://github.com/swiftlang/llvm-project/pull/9442

Edit: All still-visible failures here happened for the same reason: https://ci.swift.org/view/Swift%20rebranch/job/oss-swift-rebranch-lldb-linux-ubuntu-22_04/

**Comment by hjyamauchi** [comment]
@swift-ci please test Linux Platform

**Comment by weliveindetail** [comment]
Thanks. Rebranch linux is still broken.

**Comment by hjyamauchi** [comment]
@swift-ci please test Linux Platform

**Comment by weliveindetail** [comment]
Perfect, I think this can land any time.

**Pull request merged**
