### PR TITLE
[lldb] Unlock Swift scratch context before early return 

### PR DESCRIPTION
**Pull request by adrian-prantl**
(cherry picked from commit 32fa0939a878d4b88a3609abafdb97f646144ae4)

rdar://90666943

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test macOS

**Comment by kastiglione** [comment]
The result is the same, but on stable I ended up using a scoped exit (good suggestion by the reviewer ;) See [#3865](https://github.com/apple/llvm-project/pull/3865/files)

**Review by kastiglione — APPROVED** [review]

**Comment by adrian-prantl** [comment]
Right.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
