### PR TITLE
[rebranch] Various changes to get rebranch compiling

### PR DESCRIPTION
**Pull request by bnbarham**

### CODE REVIEW

**Comment by bnbarham** [comment]
@drexin your codegen change needs cherry-picking to `next`.

@ian-twilightcoder I assume I should also cherry-pick the modulemap change to `next` too (or is that upstream, I haven't actually checked yet)?

**Comment by bnbarham** [comment]
https://github.com/swiftlang/swift/pull/74851

@swift-ci please test

**Review by drexin — APPROVED** [review]

**Comment by drexin** [comment]
> @drexin your codegen change needs cherry-picking to `next`.

https://github.com/apple/llvm-project/pull/8939

**Comment by ian-twilightcoder** [comment]
> @ian-twilightcoder I assume I should also cherry-pick the modulemap change to `next` too (or is that upstream, I haven't actually checked yet)?

Probably, which modulemap change?

**Comment by bnbarham** [comment]
> Probably, which modulemap change?

https://github.com/apple/llvm-project/pull/8938/commits/58d2b77f0a0dda4831bb059c3898b36aadd54d3b

**Comment by ian-twilightcoder** [comment]
> > Probably, which modulemap change?
> 
> [58d2b77](https://github.com/apple/llvm-project/commit/58d2b77f0a0dda4831bb059c3898b36aadd54d3b)

Yep that should be there.

**Comment by bnbarham** [comment]
@augusto2112 seems we ended up with an extra `DoPlanExplainsStop` in some conflict resolution, I've just removed it here (will cherry-pick on next after this is merged)

**Comment by augusto2112** [comment]
> @augusto2112 seems we ended up with an extra `DoPlanExplainsStop` in some conflict resolution, I've just removed it here (will cherry-pick on next after this is merged)

Looks correct to me!

**Pull request merged**
