### PR TITLE
[MCCAS] Update list of known forms that affect debug info deduplication

### PR DESCRIPTION
**Pull request by felipepiovezan**
This commit changes the list of forms that affect deduplication in two ways:

1. The list is now aware of the Attributes in which the forms are used.
2. The list is enhanced with extra forms that have substantial impact in deduplication rate.

### CODE REVIEW

**Comment by felipepiovezan** [comment]
test please

**Comment by felipepiovezan** [comment]
@swift-ci test please

**Comment by felipepiovezan** [comment]
@swift-ci test

**Comment by felipepiovezan** [comment]
Ping

**Review by rastogishubham — APPROVED** [review]
Sorry for the late review on this, but it is pretty simple, and LGTM

**Comment by felipepiovezan** [comment]
@swift-ci test

**Pull request merged**
