### PR TITLE
[move-function] Enable running break point tests on all platforms.

### PR DESCRIPTION
**Pull request by gottesmm**
Just want to see if this works.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@adrian-prantl I am just trying this out and will probably use this PR to work out any issues on Linux. I am not expecting anything, but there /could/ be differences.

**Comment by gottesmm** [comment]
@swift-ci test windows platform

**Comment by adrian-prantl** [comment]
This should have been `@skipUnlessDarwin` anyway. Running tests on more platforms is always better :-)

**Pull request merged**
