### PR TITLE
[X86] Do not lower INSERT_VECTOR_ELT to vselect for vXf16 without BWI

### PR DESCRIPTION
**Pull request by compnerd**
We cannot handle i8/i16/f16 vselect without BWI.

Fixes #59980

Differential Revision: https://reviews.llvm.org/D141668

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @TNorthover @hyp @bnbarham @etcwilde @shahmishal

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Linux test failures are the same as https://ci.swift.org/view/Swift%20rebranch/job/oss-swift-rebranch-lldb-linux-ubuntu-18_04/2749/console.

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
