### PR TITLE
Merge apple/stable/20190619 into swift/master

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by dcci — COMMENTED** [review]
I skimmed through it and I didn't see anything obviously wrong but Raphael should take another look.

**Comment by adrian-prantl** [comment]
Yeah this was mostly meant to let you know to not bother trying

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
The bots are complaining that
`15:51:09 ERROR: File clang/include/clang/Basic/DiagnosticOptions.def is not allowed to be changed directly on swift/master`

but as far as I can tell, this PR only modifies the lldb subdirectory.

**Comment by adrian-prantl** [comment]
Hmmm.. not according to "Files Changed" on the Github web interface.

**Comment by adrian-prantl** [comment]
I forgot I need to catch the automerger...

**Pull request closed without merging**
