### PR TITLE
Update the crashlog.py shebang to run under Python 3

### PR DESCRIPTION
**Pull request by JDevlieghere**
rdar://78629167

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Review by adrian-prantl — COMMENTED** [review]
Shouldn't this be done on llvm.org?

**Comment by adrian-prantl** [comment]
`lldb/test/Shell/ScriptInterpreter/Python/Crashlog/text.test` is also running on Linux. Could hardcoding the name like this be a problem?

**Comment by adrian-prantl** [comment]
The test doesn't depend on the shebang though

**Comment by adrian-prantl** [comment]
I see the discussion for upstream is still going on

**Review by adrian-prantl — APPROVED** [review]

**Comment by JDevlieghere** [comment]
> I see the discussion for upstream is still going on

Yes, and we really want this path to point to the Python 3 interpreter from Xcode (which `/usr/bin/python3` is a shim for).

**Comment by JDevlieghere** [comment]
@swift-ci please test macos platform

**Pull request merged**
