### PR TITLE
[lldb] Enable test swift reference storage type linux

### PR DESCRIPTION
**Pull request by augusto2112**

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test linux

**Comment by augusto2112** [comment]
@adrian-prantl this test suddenly stopped failing again (on my Linux machine as well), do we just re-enable it?

**Comment by adrian-prantl** [comment]
Let's give it a try. I'm sure this won't be the last we've seen of this error though. But perhaps it comes back in a more easy-to-reproduce form.

**Review by adrian-prantl — APPROVED** [review]

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Comment by augusto2112** [comment]
CI failed when cloning the repo:
```
16:56:45 ERROR: Error cloning remote repo 'origin'
16:56:45 hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- git@github.com:apple/llvm-project.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
```

Lets try again

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Pull request merged**
