### PR TITLE
Revert "Cherry-pick 51d5d7bbae92493a5bfa7cc6b519de8a5bb32fdb from LLVM mainline"

### PR DESCRIPTION
**Pull request by natecook1000**
Reverting apple/llvm-project#7797 and apple/swift#69843, since they seem to be causing a miscompile when code throws in the middle of a modify access: https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-simulators/3870/console

### CODE REVIEW

**Comment by asl** [comment]
@natecook1000 Will you please tag the original PR next time? I only suddenly realized that you reverted something as depending PRs started not to apply.

**Comment by asl** [comment]
@natecook1000 The test does not fail for me when running locally. Any idea how it could be debugged? What is the environment?

**Comment by aschwaighofer** [comment]
The log at https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-simulators/3870/consoleText should contain some information.

The build command is:

```
+ /Users/ec2-user/jenkins/workspace/oss-swift_tools-RA_stdlib-DA_test-simulators/swift/utils/build-script --preset=buildbot,tools=RA,stdlib=DA install_destdir=/Users/ec2-user/jenkins/workspace/oss-swift_tools-RA_stdlib-DA_test-simulators/install installable_package=/Users/ec2-user/jenkins/workspace/oss-swift_tools-RA_stdlib-DA_test-simulators/oss-swift_tools-RA_stdlib-DA_test-simulators-b3870.tar.gz --cmake-c-launcher /usr/local/bin/sccache --cmake-cxx-launcher /usr/local/bin/sccache
note: skipping Xcode version check
[/Users/ec2-user/jenkins/workspace/oss-swift_tools-RA_stdlib-DA_test-simulators/swift/utils/build-script] NOTE: using preset "buildbot,tools=RA,stdlib=DA", which expands to 

/Users/ec2-user/jenkins/workspace/oss-swift_tools-RA_stdlib-DA_test-simulators/swift/utils/build-script --ios --tvos --watchos --test --validation-test --lit-args=-v --compiler-vendor=apple --verbose-build --build-ninja --build-swift-stdlib-unittest-extra --install-llvm --install-swift --install-swiftsyntax --skip-test-cmark --install-destdir=/Users/ec2-user/jenkins/workspace/oss-swift_tools-RA_stdlib-DA_test-simulators/install --installable-package=/Users/ec2-user/jenkins/workspace/oss-swift_tools-RA_stdlib-DA_test-simulators/oss-swift_tools-RA_stdlib-DA_test-simulators-b3870.tar.gz --reconfigure '--swift-install-components=back-deployment;compiler;clang-builtin-headers;libexec;stdlib;sdk-overlay;static-mirror-lib;editor-integration;tools;toolchain-tools;testsuite-tools;sourcekit-xpc-service;swift-remote-mirror;swift-remote-mirror-headers;swift-external-generic-metadata-builder;swift-external-generic-metadata-builder-headers' --release --assertions --swift-stdlib-build-type=Debug --swift-stdlib-enable-assertions=true --enable-array-cow-checks --skip-test-ios-host --skip-test-tvos-host --skip-test-watchos-host --cmake-c-launcher /usr/local/bin/sccache --cmake-cxx-launcher /usr/local/bin/sccache
```

The Xcode installed on the bots claims to be Xcode 15.1 (https://ci.swift.org)

https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-simulators/3870 lists the git commits

**Comment by aschwaighofer** [comment]
The Swift standard library is build in debug mode with assertions:
```
-- Building Swift standard library and overlays for SDKs: IOS;IOS_SIMULATOR;OSX;TVOS;TVOS_SIMULATOR;WATCHOS;WATCHOS_SIMULATOR
--   Build type:       Debug
--   Assertions:       TRUE
```

**Comment by asl** [comment]
@aschwaighofer Thanks! Yes, I was finally able to reproduce the issue replicating the buildbot configuration. The debug stdlib is the key.

Looks like there subtle misalignment between LLVM side of coroutines support and what Swift assumes / expect that was exposed by this commit. I will likely workaround on Swift side and then work with LLVM co-routines code owner to see what would be the better overall resolution

**Pull request merged**
