### PR TITLE
Fix an invalid iterator dereference in LiveDebugValues.

### PR DESCRIPTION
**Pull request by adrian-prantl**
The early exit to avoid tracking spills for async entry values

      if (IsSwiftAsyncFunction && Var.second.Properties.DIExpr &&
          Var.second.Properties.DIExpr->isEntryValue())
        continue;

skips over

      loadVarInloc(MBB, DbgOpStore, ValueToLoc, Var.first, Var.second);

which among many other things inserts the variable into ActiveVLocs.

    auto Result = ActiveVLocs.insert(std::make_pair(Var, NewValue));

 This breaks two places where we assume that

    ActiveVLocs.find(Var)

always succeeds.

rdar://106291711

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by felipepiovezan — APPROVED** [review]
LGTM!

One of the asserts doesn't make a lot of sense with the swift modifications, but better to leave it there and avoid extra diffs from upstream.

**Comment by adrian-prantl** [comment]
@swift-ci test macOS

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Pull request merged**
