### PR TITLE
Merge stable/20221013 into swift/release/5.9

### PR DESCRIPTION
**Pull request by adrian-prantl**
Because the automerger wasn't set up, swift/release/5.9 is currently behind of stable/20221013. Now that the automerger is set up, I'm doing a one-time merge of stable/20221013 into swift/release/5.9 to make sure all the "lost" contents is on the branch.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by kavon** [comment]
please hold off on merging this before I get a chance to approve this PR :)

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Review by kavon — APPROVED** [review]
This looks good to land. Once the reverts from this land in `stable/20221013` we should merge https://github.com/apple/llvm-project/pull/6630 to fix that. Thanks for working on this.

**Pull request merged**
