### PR TITLE
Revert "[lldb] Make lldbVersion a full fledged library "

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/llvm-project#3662

This is likely the culprit of the Windows build regression: https://ci-external.swift.org/job/oss-swift-windows-toolchain-x86_64-vs2019/495/console

CC: @JDevlieghere @etcwilde

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
The error says it can't find `'/GenerateVersionFromVCS.cmake'`, which implies that `${LLVM_CMAKE_DIR}` is empty in `"${LLVM_CMAKE_DIR}/GenerateVersionFromVCS.cmake"`. Why would this only happen on Windows?

**Comment by compnerd** [comment]
Likely not a Windows specific thing but rather a unified build thing.

**Comment by JDevlieghere** [comment]
Ah, that would make more sense. That's something I can reproduce more easily.

**Comment by JDevlieghere** [comment]
I reproduced the issue locally and confirmed that https://github.com/apple/llvm-project/pull/3692 fixes it.

**Pull request closed without merging**
