### PR TITLE
🍒/python changes

### PR DESCRIPTION
**Pull request by JDevlieghere**

### CODE REVIEW

**Comment by JDevlieghere** [comment]
Should fix issues like https://ci.swift.org/job/oss-swift-package-ubuntu-20_04/362/console

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Im fine with these being cherry-picked, but the question is should it be on stable/20200108 instead (as @adrian-prantl kindly reminded me).  Seems that both already made the cutoff for stable/20200714, so that branch should be fine.

**Comment by JDevlieghere** [comment]
No, these changes should go to master. Adrian's statement is correct: all cherrypick form llvm.org should go to the `apple/stable` branch and only swift specific changes should go to the `swift/` branches. However there's an exception: when we've reached the point in the release that we don't want to take any more changes. This has to do with the layout of the auto-merger:

```
apple/stable/20200108 -> swift/release/5.3 -> swift/master. 
```

The changes in this PR should *not* go to swift 5.3 so that's why I'm cherry-picking them to `swift/master`. They're just here to work with the Python changes you're doing on Swift's `master` branch. 

PS: I already cleared this up with @adrian-prantl offline.

**Review by compnerd — APPROVED** [review]

**Pull request merged**
