### PR TITLE
[LLDB][ELF] Fix section unification to not just use names.

### PR DESCRIPTION
**Pull request by al45tair**
Section unification cannot just use names, because it's valid for ELF binaries to have multiple sections with the same name. We should check other section properties too.

rdar://124467787

### CODE REVIEW

**Comment by al45tair** [comment]
This is a cherry pick of https://github.com/llvm/llvm-project/pull/90099

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
@swift-ci Please test

**Comment by al45tair** [comment]
The macOS failure doesn't appear to be related to the changes in this PR.

**Comment by al45tair** [comment]
@swift-ci Please test macOS platform

**Review by etcwilde — COMMENTED** [review]
I think this looks like it should work. I don't know enough about LLDB details to feel comfortable approving though.

**Comment by al45tair** [comment]
:-) I'm told we don't actually need this one anyway, because there's an auto merger that will take #8699 and apply it here.

**Comment by al45tair** [comment]
Closing as #8699 has been merged and the auto merger has done its job.

**Pull request closed without merging**
