### PR TITLE
[CAS] Fix Windows build

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Fix windows build by wrapping function definition into proper namespace.

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci Please test Windows platform

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
The changes look fine, though I think that the commit message should be updated to identify the fact that `getDefaultOnDiskActionCachePath` was hoisted out of the condition to ensure it is always defined.

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Pull request merged**
