### PR TITLE
Cherry-picking 4 to Stable/20220421

### PR DESCRIPTION
**Pull request by ziqingluo-90**

### CODE REVIEW

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Review by haoNoQ — APPROVED** [review]
LGTM!

**Comment by ziqingluo-90** [comment]
It's been a few weeks old. Let me do test one more time before merge.
@swift-ci test

**Comment by ziqingluo-90** [comment]
Just rebased. 
@swift-ci test

**Comment by drodriguez** [comment]
`clang/test/Analysis/region-store.c` diagnostics wording depends on https://github.com/llvm/llvm-project/commit/681c50c62e933 which has not been cherry-picked. You might also want 605651135b4c37e423825a9201b06a16ff6160a1 to be complete.

**Pull request merged**
