### PR TITLE
Static analyzer equality tracking cherrypicks

### PR DESCRIPTION
**Pull request by SavchenkoValeriy**
Static analyzer cherry picks from master fixing <rdar://problem/56586853> [Solver] a != b and a == 0 implies b != 0

### CODE REVIEW

**Comment by SavchenkoValeriy** [comment]
@swift-ci please test!

**Review by haoNoQ — APPROVED** [review]
Sure!

**Comment by SavchenkoValeriy** [comment]
@swift-ci test

**Comment by SavchenkoValeriy** [comment]
I spent good 10min trying to find what's wrong with https://ci.swift.org/job/apple-llvm-project-pr-linux/1175/, but had no luck 😞

**Pull request merged**
