### PR TITLE
Libclang new apis 20200714

### PR DESCRIPTION
**Pull request by jkorous-apple**
PR for another stable branch
https://github.com/apple/llvm-project/pull/1756

### CODE REVIEW

**Comment by jkorous-apple** [comment]
@swift-ci please test

**Comment by jkorous-apple** [comment]
Swift Test Linux Platform

21:54:20 Failed Tests (2):
21:54:20   LeakSanitizer-Standalone-x86_64 :: TestCases/Linux/fork_and_leak.cpp
21:54:20   Profile-x86_64 :: Posix/gcov-fork.c

Doesn't seem like something this code would break

**Comment by jkorous-apple** [comment]
@swift-ci please test

**Review by hyp — APPROVED** [review]
LGTM

**Pull request merged**
