### PR TITLE
[AArch64] Relax 'inbounds' requirement for llvm.ptrauth signed GEPs.

### PR DESCRIPTION
**Pull request by kubamracek**

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci test

**Comment by rjmccall** [comment]
Hmm.  Probably reasonable, although a GEP that actually violates `inbounds` here is probably not going to be supported by the linker.

**Comment by kubamracek** [comment]
@swift-ci test

**Comment by kubamracek** [comment]
@swift-ci test

**Comment by kubamracek** [comment]
@swift-ci test

**Comment by kubamracek** [comment]
@swift-ci test

**Comment by kubamracek** [comment]
@swift-ci test

**Pull request merged**
