### PR TITLE
Skip test on older platforms

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by Michael137 — APPROVED** [review]

**Comment by Michael137** [comment]
```
--
Command Output (stderr):
--
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-swift/release/6.0/llvm-project/lldb/test/API/dotest.py", line 8, in <module>
    lldbsuite.test.run_suite()
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-swift/release/6.0/llvm-project/lldb/packages/Python/lldbsuite/test/dotest.py", line 1040, in run_suite
    visit("Test", dirpath, filenames)
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-swift/release/6.0/llvm-project/lldb/packages/Python/lldbsuite/test/dotest.py", line 714, in visit
    visit_file(dir, name)
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-swift/release/6.0/llvm-project/lldb/packages/Python/lldbsuite/test/dotest.py", line 655, in visit_file
    module = __import__(base)
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-swift/release/6.0/llvm-project/lldb/test/API/lang/swift/late_swift_dylib_clangdeps/TestSwiftLateSwiftDylibClangDeps.py", line 5, in <module>
    class TestSwiftLateSwiftDylibClangDeps(TestBase):
  File "/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-swift/release/6.0/llvm-project/lldb/test/API/lang/swift/late_swift_dylib_clangdeps/TestSwiftLateSwiftDylibClangDeps.py", line 6, in TestSwiftLateSwiftDylibClangDeps
    @skipIf(macos=["<", "13.0"])
TypeError: skipIf() got an unexpected keyword argument 'macos'
```

I think this should be `macos_version`?

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Pull request merged**
