### PR TITLE
Cherry-pick two upstream lit changes to optimize swift testing performance

### PR DESCRIPTION
**Pull request by davezarzycki**
… start times based on prior test timing data

Lit as it exists today has three hacks that allow users to run tests earlier:

1) An entire test suite can set the `is_early` boolean.
2) A very recently introduced "early_tests" feature.
3) The `--incremental` flag forces failing tests to run first.

All of these approaches have problems.

1) The `is_early` feature was until very recently undocumented. Nevertheless it still lacks testing and is a imprecise way of optimizing test starting times.
2) The `early_tests` feature requires manual updates and doesn't scale.
3) `--incremental` is undocumented, untested, and it requires modifying the *source* file system by "touching" the file. This "touch" based approach is arguably a hack because it confuses editors (because it looks like the test was modified behind the back of the editor) and "touching" the test source file doesn't work if the test suite is read only from the perspective of `lit` (via advanced filesystem/build tricks).

This patch attempts to simplify and address all of the above problems.

This patch formalizes, documents, tests, and defaults lit to recording the execution time of tests and then reordering all tests during the next execution. By reordering the tests, high core count machines run faster, sometimes significantly so.

This patch also always runs failing tests first, which is a positive user experience win for those that didn't know about the hidden `--incremental` flag.

Finally, if users want, they can _optionally_ commit the test timing data (or a subset thereof) back to the repository to accelerate bots and first-time runs of the test suite.

Reviewed By: jhenderson, yln

Differential Revision: https://reviews.llvm.org/D98179

### CODE REVIEW

**Comment by davezarzycki** [comment]
@shahmishal — So this is the very fruitful result of some work I did with the LLVM community. It allows us to reorder tests with actual timing data and is the much better replacement for the "early_tests" work that we cherry-picked a few weeks ago. It'd be great if we could cherry-pick this. Thanks!

@swift-ci please test macos

**Comment by davezarzycki** [comment]
One more thing @shahmishal – The timing data would be a useful starting point for detecting test performance regressions incurred by a pull request. :-)

**Comment by davezarzycki** [comment]
@swift-ci please test macos

**Comment by shahmishal** [comment]
Thanks @davezarzycki!

**Pull request merged**
