### PR TITLE
Cherry pick trampoline support

### PR DESCRIPTION
**Pull request by augusto2112**

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]
We may rename the clang attribute later, but for now, this LGTM.

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Comment by augusto2112** [comment]
Swift asan validation tests timed out:

```
Timed Out Tests (3):
  lldb-api :: functionalities/asan/swift/TestAsanSwift.py
  lldb-api :: functionalities/tsan/swift-access-race/TestTsanSwiftAccessRace.py
  lldb-api :: functionalities/tsan/swift/TestTsanSwift.py
```

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Pull request merged**
