### PR TITLE
Fix Reproducer/TestCaptureEnvOverride.test in swift/master

### PR DESCRIPTION
**Pull request by vedantk**

### CODE REVIEW

**Comment by vedantk** [comment]
@swift-ci test macOS platform

**Comment by JDevlieghere** [comment]
Thanks!

**Review by JDevlieghere — APPROVED** [review]

**Comment by vedantk** [comment]
I got itchy fingers. The test still fails, looking into it.

**Comment by vedantk** [comment]
@JDevlieghere is `LLDB_CAPTURE_REPRODUCER=0` expected to be a no-op in swift-lldb? That's the current state of affairs, which seems weird to me.

**Comment by JDevlieghere** [comment]
No, it should always be honored, unless you're in replay mode. Let's figure this out offline.

**Comment by vedantk** [comment]
Jonas and I investigated the issue, and it turned out to be a problem with my test setup. The functionality is behaving as expected.

**Comment by vedantk** [comment]
@swift-ci test Linux platform

**Pull request merged**
