### PR TITLE
[SwiftASTContext] Update for SourceManager API renaming

### PR DESCRIPTION
**Pull request by owenv**
counterpart to https://github.com/apple/swift/pull/31943

### CODE REVIEW

**Comment by owenv** [comment]
https://github.com/apple/swift/pull/31943

@swift-ci test

**Comment by owenv** [comment]
apple/swift#31943

@swift-ci test Linux platform

**Comment by owenv** [comment]
apple/swift#31943

@swift-ci test Linux platform

**Comment by hamishknight** [comment]
CI issues should be fixed now

apple/swift#31943

@swift-ci test Linux platform

**Comment by hamishknight** [comment]
@owenv Would you mind also opening a cherry-pick for the `swift/master-next` branch? Unfortunately we don't have an automerger for it, so PRs have currently have be done for both branches.

I can then go ahead and do the cross-merge for you :)

**Comment by owenv** [comment]
@hamishknight thanks, it's been awhile since I made changes here and I'd forgotten some of the specifics. I just opened the master-next cherrypick as https://github.com/apple/llvm-project/pull/1260/

**Comment by hamishknight** [comment]
No worries, thank you!

**Pull request merged**
