### PR TITLE
[clangd] Support rename of Objective-C method names

### PR DESCRIPTION
**Pull request by ahoppen**
Merging https://github.com/apple/llvm-project/pull/7915 into `next`.

---

This integrates the rename support for Objective-C selectors that we had in libclang into `clangd`. 

While doing this, it unifies `SymbolName` and `OldSymbolName`. `OldSymbolName` was used by `Refactor`, the refactoring library that only exists in Apple’s fork, while `SymbolName` was used by `Refactoring`, the upstream refactoring library. Unify them and add mulit-piece symbol support ot the upstream `SymbolName`.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test llvm

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test llvm

**Comment by ahoppen** [comment]
@swift-ci Please test llvm

**Comment by ahoppen** [comment]
@swift-ci Please test llvm

**Comment by ahoppen** [comment]
@swift-ci Please test llvm

**Comment by ahoppen** [comment]
@swift-ci Please test llvm Linux

**Comment by ahoppen** [comment]
Test failures are unrelated.

**Pull request merged**
