### PR TITLE
Move the initialization of common language options into the 

### PR DESCRIPTION
**Pull request by adrian-prantl**
SwiftASTContext constructor.

rdar://104197426

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by augusto2112 — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
