### PR TITLE
Enable MCCAS in stable/20230725

### PR DESCRIPTION
**Pull request by rastogishubham**
With https://github.com/apple/llvm-project/pull/7121, MCCAS has been enabled in next, so this change cherry-picks it into the stable branch

### CODE REVIEW

**Comment by rastogishubham** [comment]
@swift-ci please test

**Review by benlangmuir — APPROVED** [review]
I only skimmed the patch since I assume it's roughly identical to the previous one, but cherry-picking to stable/2023 SGTM

**Comment by rastogishubham** [comment]
@benlangmuir I just cherry-picked the commits from next to stable, so no changes were made. Thanks!

**Review by cachemeifyoucan — APPROVED** [review]

**Comment by benlangmuir** [comment]
@rastogishubham please cherry-pick https://github.com/apple/llvm-project/pull/7175 into this PR

**Comment by rastogishubham** [comment]
@swift-ci please test

**Comment by rastogishubham** [comment]
@swift-ci please test

**Pull request merged**
