### PR TITLE
Fix a nullptr deref in SwiftLanguageRuntime:Get().

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://problem/53961749

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test and merge

**Comment by adrian-prantl** [comment]
Technically, the nullptr deref happened in GetBitSize(), not in Get().

**Review by dcci — APPROVED** [review]
LGTM

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
