### PR TITLE
monorepo fixup: Merge --theirs all the untracked dirs in swift/master

### PR DESCRIPTION
**Pull request by dexonsmith**
Because LLDB branched significantly later than the other tracked
directories, the generated content for swift/master has a much newer
version of the untracked directories (llgo, polly, lld, etc.) than
apple/stable/20190619.

@hyp did the work to fix this, running:

```sh
for repo in debuginfo-tests libclc libcxxabi \
            libunwind lld llgo openmp parallel-libs polly pstl
do
  git rm -rf $repo > /dev/null
  latest_commit=$(git rev-list HEAD -n1 -- $repo)
  tree=$(git rev-parse origin/apple/stable/20190619:$repo)
  git read-tree --prefix=$repo $tree
done
```

I've just simplified by making this a simple re-merge from
the merge-base with apple/stable/20190619 instead of an octopus from the
last commit to each directory above (which seems to unnecessarily
compilicate `git log --graph`).

In case anyone does care about those commits, here they are:

- 559c6e17cd88da0c70fea7d9fd8933d1d2739ab7: debuginfo-tests/
- 2abbe2f09119ccad8ad96841ea4632a9c8a8f04d: libclc/
- 5a14c1722183bbe3224f8c69b8e189326185522a: libcxxabi/
- d8bdb9225ce3896797892293053efac8ad8d52fb: libunwind/
- d581dd50138186fe2c29eff617e7ca5897e3c69e: lld/
- c0e6b8ac3ad442e08d7a16382ff50969ba3f2b2d: llgo/
- 673e5476a817e93440e4b269df8bcb0d4b8aae14: openmp/
- 4a1b95bda0c444798a5240fe924dd127b776d12d: parallel-libs/
- acbdd07de6dee3f0604c3256acedd58e15a08d5c: polly/
- 1b6d6e595b5e27566579c03923667aaab58bd3cd: pstl/

### CODE REVIEW

**Comment by dexonsmith** [comment]
@swift-ci test

(although, we know at least one test will fail because it modifies directories outside of `lldb/`)

**Comment by dexonsmith** [comment]
@swift-ci please test

**Comment by dexonsmith** [comment]
This is the failure we expected.
```
21:48:18 + python /Users/buildnode/jenkins/workspace/apple-llvm-project-pr-macos/swift-ci/jobs/pull-request/check_changed_files.py
21:48:19 ERROR: File debuginfo-tests/nrvo-string.cpp is not allowed to be changed directly on swift/master
```

@hyp, let me know if this looks good.

**Review by hyp — APPROVED** [review]
Lg

**Pull request merged**
