### PR TITLE
Cherrypick missing commits master next

### PR DESCRIPTION
**Pull request by JDevlieghere**

### CODE REVIEW

**Review by dcci — COMMENTED** [review]
My commits are OK.

**Comment by dcci** [comment]
Can't speak for the others.

**Comment by adrian-prantl** [comment]
Thanks! It may also pay off to look at the diff between the branches manually afterwards. I've fixed an issue in the past (when we did the big testsuite rename/move) where a merge conflict resolution had dropped entire files.

**Comment by JDevlieghere** [comment]
> Thanks! It may also pay off to look at the diff between the branches manually afterwards. I've fixed an issue in the past (when we did the big testsuite rename/move) where a merge conflict resolution had dropped entire files.

Yep, I already did that for the commits where the test paths were different.

**Comment by fredriss** [comment]
Thanks for doing this Jonas!

**Comment by fredriss** [comment]
My part looks good!

**Review by fredriss — APPROVED** [review]

**Comment by JDevlieghere** [comment]
Thanks everyone. I'll wait for Raphael to have a look and merge this tomorrow. Worst case we can always revert individual commits.

**Comment by Teemperor** [comment]
LGTM, thanks!

**Comment by JDevlieghere** [comment]
I guess it's after midnight so technically this counts as tomorrow :-)

**Pull request merged**
