### PR TITLE
[cherry-pick swift/release/6.0][clang][modules] stdarg.h and stddef.h shouldn't directly declare anything

### PR DESCRIPTION
**Pull request by ian-twilightcoder**
stdarg.h and especially stddef.h are textual and so everything they declare gets precompiled into all of their clients' pcm files. They shouldn't directly declare anything though, their purpose is to select what submodules get imported, and not to add duplicate declarations to all of their clients. Make it so that they always ignore their header guards, even without modules, and declare them in separate header files so that they only go into the stdarg/stddef pcms. Still declare them in case clients rely on them.

rdar://127326141

### CODE REVIEW

**Comment by ian-twilightcoder** [comment]
Explanation: This change makes clang's stdarg.h and stddef.h not declare anything directly, allowing them to be included by any module and not bloat that module's pcm. Instead, all of their declarations including their header macros go into their own pcm and are not duplicated.
Radar (and possibly SR Issue): rdar://127326141
Scope: This will only affect environments where the clang built-in modules are used (non-default on Apple platforms).
Risk: None anticipated.
Testing: Local testing, CI
Reviewed By: Michael Spencer (Bigcheese)

**Comment by ian-twilightcoder** [comment]
@swift-ci test llvm

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Review by cyndyishida — APPROVED** [review]
LGTM

**Comment by ian-twilightcoder** [comment]
LLVM failures are unrelated, they're mostly these.
```
error: unknown argument '-emit-llvm-only'; did you mean '-Xclang -emit-llvm-only'?
```

And then FixIt/format.cpp is missing some expected warnings, but it's not using stdarg or stddef so it should be unrelated too.

**Pull request merged**
