### PR TITLE
Update SwiftFormatters.cpp to account for interface changes

### PR DESCRIPTION
**Pull request by shafik**
Change to interface made by https://reviews.llvm.org/D113098

see: rdar://86228572

### CODE REVIEW

**Comment by shafik** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Oh cool, thanks Shafik! I started doing this but I wasn't sure about the change for `readStringFromAddress`. I'm assuming building will fail without https://github.com/apple/llvm-project/pull/3641. If someone wants to have a look at that one too that'd be great :) (@JDevlieghere / @adrian-prantl)

**Comment by shafik** [comment]
> Oh cool, thanks Shafik! I started doing this but I wasn't sure about the change for `readStringFromAddress`. I'm assuming building will fail without #3641. If someone wants to have a look at that one too that'd be great :) (@JDevlieghere / @adrian-prantl)

Yeah, I was assuming that the build would fail but it would fail with a different error and we could merge.

**Review by adrian-prantl — APPROVED** [review]
Thanks!

**Comment by adrian-prantl** [comment]
This being _next_ feel free to merge without waiting for a bot if it's blocked on unrelated changes.

**Pull request merged**
