### PR TITLE
[lldb/bindings] Update python static bindings

### PR DESCRIPTION
**Pull request by medismailben**
Signed-off-by: Med Ismail Bennani <medismail.bennani@gmail.com>

### CODE REVIEW

**Comment by medismailben** [comment]
@swift-ci test

**Comment by medismailben** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by medismailben** [comment]
@swift-ci test macOS Platform

**Comment by JDevlieghere** [comment]
@swift-ci test macOS Platform

**Comment by Teemperor** [comment]
I'm gonna take over writing swift test in a loop here: https://github.com/apple/llvm-project/pull/2676

(I also fixed the tools script that autogenerates the PRs)

**Pull request closed without merging**
