### PR TITLE
Cherry-pick "[lldb] Fix missing characters when autocompleting LLDB commands in REPL" to swift/master

### PR DESCRIPTION
**Pull request by poya**
Cherry-pick of recent fix for https://bugs.swift.org/browse/SR-12867 in swift/master-next to swift/master

Differential Revision: https://reviews.llvm.org/D82835

### CODE REVIEW

**Comment by poya** [comment]
@Teemperor Porting this recent fix to swift/master to be able to resolve the bug report as fixed. I'm not fully familiar with the branching strategy used, whether this fix should go into any other stable/release branch at this time?

**Comment by Teemperor** [comment]
The LLDB change goes into stable/ and the swift test goes into swift/master (it's a bit confusing). I did the cherry-pick [here](https://github.com/apple/llvm-project/pull/1428) so you can just drop the LLDB change from this PR and we're all set!

**Comment by Teemperor** [comment]
(Also sorry for the delay)

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by fredriss** [comment]
The test should also go to `swift/master-next`

**Comment by poya** [comment]
@Teemperor LLDB change dropped, now only Swift REPL test in this PR

**Comment by poya** [comment]
> The test should also go to `swift/master-next`

@fredriss The test was originally added to swift/master-next in #1388 so that part has already been taken care of

**Comment by fredriss** [comment]
@swift-ci test

**Comment by poya** [comment]
@Teemperor @fredriss Anything missing, or ready to merge?

**Review by Teemperor — APPROVED** [review]

**Comment by Teemperor** [comment]
This is only a test so I'll go ahead and merge this. The change for this already landed.

**Pull request merged**
