### PR TITLE
Cp/add fixaddress sbprocess apis

### PR DESCRIPTION
**Pull request by jasonmolenda**

### CODE REVIEW

**Comment by jasonmolenda** [comment]
@swift-ci test

**Comment by jasonmolenda** [comment]
@swift-ci test

**Comment by jasonmolenda** [comment]
@swift-ci test linux

**Comment by jasonmolenda** [comment]
@augusto2112 the 4th commit on this PR is a change to LLDBMemoryReader::queryDataLayout's DLQ_GetPtrAuthMask if you'd like to look at it.  I changed the value of "no mask" and this needed to be updated to match, it was resulting in test failures on Intel systems where there is no mask.

**Comment by jasonmolenda** [comment]
I'm putting off PR testing tonight because github main branch testing fails because of a compilation error in swift-docc, but I'll test tomorrow once that's been looked at.

**Comment by jasonmolenda** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci test windows

**Comment by jasonmolenda** [comment]
@augusto2112 the PR testing passed.   Are you OK with my change to the swift metadata mask getter?

**Review by augusto2112 — APPROVED** [review]

**Pull request merged**
