### PR TITLE
[lldb] Use specified LD_EXTRAS when building TestSwiftCPPExceptionsInREPL

### PR DESCRIPTION
**Pull request by augusto2112**

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Review by adrian-prantl — APPROVED** [review]

**Comment by augusto2112** [comment]
Unrelated test failure:

```
Failed Tests (1):
  Swift(watchsimulator-i386) :: Distributed/Runtime/distributed_actor_init_local.swift
```

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Comment by augusto2112** [comment]
@swift-ci test

**Pull request merged**
