### PR TITLE
 [Darwin] Fix availability of exp10 for BridgeOS, DriverKit.

### PR DESCRIPTION
**Pull request by fhahn**

### CODE REVIEW

**Comment by fhahn** [comment]
@swift-ci please test

**Comment by fhahn** [comment]
@swift-ci please test llvm

**Comment by fhahn** [comment]
@swift-ci please test

**Comment by porglezomp** [comment]
@swift-ci please test

**Comment by fhahn** [comment]
Looks like CI is not required to merge any more, merging now

**Pull request merged**
