### PR TITLE
Resuscitate TestSwiftStaticLinking.py 

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://31066897

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@jimingham does that look like it's still testing what was originally intended?

**Comment by jimingham** [comment]
This is testing that having two separate swiftmodules linked into one binary image doesn't keep us from being able to produce types for those modules (in this case the one class defined by each module).  That seems like it could be tricky, so testing that seems worthwhile.  But now that we get most type information from the runtime instead, just doing "frame var" and asserting that it got a type might no longer be a sufficient test.  We might want to also make sure `expr self` also works to trigger building all the AST's?

**Comment by adrian-prantl** [comment]
Good point!

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
