### PR TITLE
[stable/20221013] Cherry-pick CAS changes

### PR DESCRIPTION
**Pull request by benlangmuir**

### CODE REVIEW

**Comment by benlangmuir** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
LGTM. That `ThinLTO` commit has a followup https://reviews.llvm.org/rG279c2971951c2ea58a2bd1e6687ce61451f9d329

**Comment by benlangmuir** [comment]
@swift-ci please test Windows

**Comment by benlangmuir** [comment]
@swift-ci please test Windows

**Comment by benlangmuir** [comment]
@swift-ci please test Windows

**Comment by benlangmuir** [comment]
@swift-ci please test macOS

**Pull request merged**
