### PR TITLE
[LLDB] [Windows] Initial support for ARM64 register contexts

### PR DESCRIPTION
**Pull request by compnerd**
Differential Revision: https://reviews.llvm.org/D67954

llvm-svn: 374866
(cherry picked from commit b1f6ba2a2ecdf253c1ee2f2a04156eba78cfe3fa)

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @shahmishal @hyp @dexonsmith @dcci @JDevlieghere

**Comment by compnerd** [comment]
This should hopefully restore the ability to build lldb for Windows AArch64.  https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=13269&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=fe77543e-0992-5aa1-b1f9-554117177cec&l=4880

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
LGTM, thanks!

**Pull request merged**
