### PR TITLE
Move SwiftASTContext::GetResourceDir to HostInfo.

### PR DESCRIPTION
**Pull request by adrian-prantl**
This allows us to simplify and customize the implementations for
non-macOS hosts.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by compnerd — APPROVED** [review]
I think that this is going to be incredibly helpful for cleaning up some of the resource dir location logic on Windows.  Thanks for doing this!

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
