### PR TITLE
Fix compile errors in no-asserts configuration

### PR DESCRIPTION
**Pull request by adrian-prantl**
Thanks @drodriguez for pointing this out!

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by drodriguez** [comment]
@swift-ci please test llvm

**Comment by adrian-prantl** [comment]
@swift-ci test llvm

**Comment by drodriguez** [comment]
I left comments about those LLVM test failures in #8253 and #8254.

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Comment by al45tair** [comment]
FYI, I'm reverting #8254 (the revert is #8396), and #8397 should fix the problem #8253 introduced.

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by al45tair** [comment]
Hmmm. I wonder if the not-triggering-Windows thing is related to the 403 errors I'm getting from `ci-external.swift.org` right now?

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Pull request merged**
