### PR TITLE
Revert "lldb: link swift's libswift to lldb"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/llvm-project#3537

In case we need to revert if we cannot get things fixed - it is likely that people will be rushing to get changes in when the tree is unlocked.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
Yep, the PR being reverted is breaking the Windows build. Will merge once it passes and branches are unlocked.
Failing bot: https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/

**Comment by etcwilde** [comment]
@eeckstein Do you have a fix for Windows ready? If not, the offending PR will need to be reverted.

**Comment by eeckstein** [comment]
@etcwilde yes: https://github.com/apple/llvm-project/pull/3737

**Comment by philipturner** [comment]
@compnerd I have tried reaching out to you about pending pull requests to S4TF repositories. Please review them.

**Comment by compnerd** [comment]
@philipturner - constantly pinging on various different repositories, consistently is _EXTREMELY_ inappropriate.  S4TF has been archived, it is not in activate development, and I have plenty of other things to work on.  I will look at it as I have the time.  Please do **NOT** ping for reviews on unrelated projects and pull requests.

**Comment by compnerd** [comment]
#3737 works, I don't see why this needs to remain open.  Thanks @eeckstein.

**Pull request closed without merging**
