### PR TITLE
[move-keyword] Now that move keyword is back behind a feature flag, add that flag to the tests that use it...

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by gottesmm** [comment]
Associated with apple/swift#60493

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/60493

@swift-ci test

**Review by adrian-prantl — APPROVED** [review]
Looks good. Please also cherry-pick this to the `stable/20220421` and `next` branches!

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/60493

@swift-ci test

**Comment by gottesmm** [comment]
@adrian-prantl Done

https://github.com/apple/llvm-project/pull/5103
https://github.com/apple/llvm-project/pull/5105

**Pull request merged**
