### PR TITLE
Sprinkle scoped timer support all over the Swift language binding.

### PR DESCRIPTION
**Pull request by adrian-prantl**
The scoped timers translate into Signposts on Darwin and should make
performance tracking much easier.

rdar://76070796

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by JDevlieghere — APPROVED** [review]
Thanks for doing this!

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
How did you decide which functions to instrument?

**Pull request merged**
