### PR TITLE
Cherry-picking 3 to stable/20221013

### PR DESCRIPTION
**Pull request by ziqingluo-90**
cherry-picking static analysis related commits from `llvm/main` to `stable/20221013`

### CODE REVIEW

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by ziqingluo-90** [comment]
These commits is a sub-sequence of this [PR to stable/20220421](https://github.com/apple/llvm-project/pull/5497) because some commits are already in `stable/20221013`

**Review by haoNoQ — APPROVED** [review]
Good stuff!

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Pull request closed without merging**
