### PR TITLE
Correctly identify "self" inside an allocator.

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://problem/59429786

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by dcci — APPROVED** [review]
This is a no-brainer. Ideally we should try to move away from a model where lldb knows what's `self` looking at the demangled tree -- I'm under the impression I brought this up in the past, but for now this is fine.

I suspect this might fix a bunch of `"self not found"` uncovered by @vedantk's testing script.

Also, thanks for picking up the slack.

**Comment by dcci** [comment]
I think we're all on the same page about this one -- but it's such a critical problem and a low-risk fix that 5.2 is the right target for it.

**Comment by adrian-prantl** [comment]
> Ideally we should try to move away from a model where lldb knows what's self looking at the demangled tree

In most cases LLDB knows what self is because it it is marked as artificial and is the last function parameter. However, in allocators, self is not an argument but a local variable created inside the allocator. And we need to distinguish that from a weak self local variable somehow.

**Comment by dcci** [comment]
Oh right. I forgot about that. LGTM.

**Pull request merged**
