### PR TITLE
[DNM] Manually merge apple/stable/20190619

### PR DESCRIPTION
**Pull request by varungandhi-apple**
The automerger seems to be blocked because of a conflict, need to manually merge this.

I haven't even compiled this yet locally (my CMake is too old?), so don't merge this right away.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
The conflicts were in lldb/source/DataFormatters/FormatManager.cpp and lldb/source/DataFormatters/LanguageCategory.cpp

**Comment by varungandhi-apple** [comment]
@shahmishal can you kick off a build? I'm having trouble building locally (for what seems like an unrelated reason) and my swift-ci powers don't seem to work here.

**Comment by shahmishal** [comment]
Only LLDB changes are allowed to `swift/master` branch, you will have to cherry-pick them to `apple/stable/20190619`.

**Comment by shahmishal** [comment]
```
ERROR: File clang/docs/ClangCommandLineReference.rst is not allowed to be changed directly on swift/master
```

**Comment by varungandhi-apple** [comment]
I don't understand. I am seeing the following automerger failure:

```
[apple/stable/20190619 -> swift/swift-5.2-branch]
- There are 24 unmerged commits. 0 commits are currently being merged/build/tested.
- Unmerged commits:
  * a63fc74743bd32d0f9a3fb81aac23d16c8056e83 Thu Dec 12 15:04:28 2019 +0000: Conflic
```

Which is why I merged `apple/stable/20190619` onto `swift/master` manually and submitted that change to `swift/swift-5.2-branch`. Am I misunderstanding the issue? Should I submit the same PR but to `apple/stable/20190619`?

**Pull request closed without merging**
