### PR TITLE
LLD cherry-picks

### PR DESCRIPTION
**Pull request by compnerd**
llvm cherry-picks required to build lld

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @dexonsmith @Bigcheese @devincoughlin @shahmishal @gottesmm

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @hyp

**Comment by shahmishal** [comment]
You should cherry-pick these changes to `apple/stable/20190619` which will get merged into `swift/master`. Only LLDB changes will be allowed in `swift/master` branch directly, and CI will fail if you make changes outside of LLDB dir.

**Comment by compnerd** [comment]
@shahmishal I don't think that `swift/master` and `apple/stable/20190619` are even close... there are about 4000 commits apart

**Comment by shahmishal** [comment]
`apple/stable/20190619` gets merged into `swift/master`

>@shahmishal I don't think that swift/master and apple/stable/20190619 are even close... there are about 4000 commits apart

@hyp do you know why they are so far a part?

**Comment by hyp** [comment]
@compnerd Could you be specific about what you mean by 4000 commits apart? `swift/master` has contents from laster LLVM svn revisions, but that contents includes only LLDB changes, as LLDB branched their old `stable` branch later than June 19th. The rest of the monorepo is the same between `swift/master` and `apple/stable/20190619`

**Comment by compnerd** [comment]
@hyp interesting, okay, so I should be able to just rebase here then.

**Comment by compnerd** [comment]
Ah, okay, seems that I just needed to refresh, in any case, rebased

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Review by dexonsmith — APPROVED** [review]
LGTM once the tests pass.

**Comment by dexonsmith** [comment]
> Ah, okay, seems that I just needed to refresh, in any case, rebased

You probably tried before I committed 3efa5045937f368a6d8c7bb37810aa052c024d72 to swift/master, which rewound the "untracked" sub-projects to the content as of apple/stable/20190619.  The monorepo generation automatically updated the untracked stuff to match the newest upstream commit, and since LLDB branched way later, swift/master had way newer lld content than it really should have.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by dexonsmith** [comment]
@compnerd the test failures look unrelated to this PR; looks like not all the tests pass on the baseline yet.  Let me know if you want me to merge this for you (I have the power to ignore the status check).

**Comment by compnerd** [comment]
@dexonsmith - yes please!  That would be wonderful!  Thank you!

**Pull request merged**
