### PR TITLE
[lldb] Re-enable test after Xcode upgrade

### PR DESCRIPTION
**Pull request by JDevlieghere**

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test macos

**Review by fredriss — APPROVED** [review]
This is fine for the branch, however it would be great to understand why it started working if we haven't yet? @adrian-prantl?

**Comment by JDevlieghere** [comment]
@shahmishal  says they started passing after upgrading the Xcode on the bots. Based on @adrian-prantl description in #1381 it seems like it might depend on 212faae which is not on the 5.3 branch. So let's see what PR testing says.

**Comment by adrian-prantl** [comment]
I _thought_ that they were fixed by 212faae (which is not on this branch). But if the Xcode upgrade is really responsible then it must be a difference in debug info generated for the stdlib, or a change in the SDK.

**Comment by JDevlieghere** [comment]
```
11:14:21 Failing Tests (2):
11:14:21     lldb-api :: lang/swift/tagged_pointer/TestSwiftTaggedPointer.py
11:14:21     lldb-api :: lang/swift/variables/dict_nsobj_anyobj/TestSwiftDictionaryNSObjectAnyObject.py
```

**Pull request closed without merging**
