### PR TITLE
Cherry-picking 3 to stable/20220421

### PR DESCRIPTION
**Pull request by ziqingluo-90**
cherry-picking static analysis related commits from `llvm/main` to `stable/20220421`

### CODE REVIEW

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by jkorous-apple** [comment]
@swift-ci please test

**Comment by ziqingluo-90** [comment]
@jkorous-apple @haoNoQ @t-rasmud @malavikasamak 
Is this PR looking good?

**Comment by jkorous-apple** [comment]
Just out of curiosity - do we need this patch?
https://github.com/apple/llvm-project/pull/5497/commits/bf75f5546be34b42f6d558f7af4b688985a0d451

**Comment by ziqingluo-90** [comment]
> Just out of curiosity - do we need this patch?
> [bf75f55](https://github.com/apple/llvm-project/commit/bf75f5546be34b42f6d558f7af4b688985a0d451)

I picked this commit because in my opinion reducing non-determinism in diagnostic report is a good improvement and the commit is from an Apple employee.    Does this sound reasonable?

**Comment by haoNoQ** [comment]
It's most likely a very good commit, but not our call to make. They're in better position to decide whether this needs to be cherry-picked, when and where. They need to weigh it against risks of regressions. Clang folks have their own policies. We're not responsible for all clang diagnostics.

I'm also not sure about thread safety analysis, I don't think we actually make use of it, but if we do, it's also a potential source of clang qualification issues as it emits compiler warnings that can be `-Werror`-ed.

**Comment by ziqingluo-90** [comment]
> Just out of curiosity - do we need this patch?
> [bf75f55](https://github.com/apple/llvm-project/commit/bf75f5546be34b42f6d558f7af4b688985a0d451)



> It's most likely a very good commit, but not our call to make. They're in better position to decide whether this needs to be cherry-picked, when and where. They need to weigh it against risks of regressions. Clang folks have their own policies. We're not responsible for all clang diagnostics.
> 
> I'm also not sure about thread safety analysis, I don't think we actually make use of it, but if we do, it's also a potential source of clang qualification issues as it emits compiler warnings that can be `-Werror`-ed.

Got it!  I have reverted the commit.

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by haoNoQ** [comment]
LGTM!

**Review by haoNoQ — APPROVED** [review]

**Pull request merged**
