### PR TITLE
[Cherry-pick] Patches related to dwarf linker

### PR DESCRIPTION
**Pull request by felipepiovezan**
This is another wave of cherry-picks from llvm.org with the ultimate goal of cherry-picking the debug_names work that has been done.

Before we can change AccelTable.cpp/.h, there are indirect dependencies with DWARFLinker (parallel and dsymutil) that must be cherry-picked (a lot of work was done upstream to refactor these entities). This PR handles some of those.

### CODE REVIEW

**Comment by felipepiovezan** [comment]
@swift-ci test

**Comment by felipepiovezan** [comment]
@swift-ci test

**Review by JDevlieghere — APPROVED** [review]

**Review by adrian-prantl — APPROVED** [review]

**Comment by felipepiovezan** [comment]
@swift-ci test platform windows

**Comment by felipepiovezan** [comment]
@swift-ci test Windows platform

**Pull request merged**
