### PR TITLE
[lldb] Fix --bind-generic-types to only apply to expression

### PR DESCRIPTION
**Pull request by augusto2112**
rdar://104617432

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]
Seems fine in principle — what about `frame variable`?

**Comment by augusto2112** [comment]
> Seems fine in principle — what about `frame variable`?

I'll add the option to frame variable when we make it work

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Pull request merged**
