### PR TITLE
 Add an lldb setting to disable ClangImporter (in favor of DWARFImport…

### PR DESCRIPTION
**Pull request by adrian-prantl**
…er).

rdar://problem/57880844

### CODE REVIEW

**Review by dcci — APPROVED** [review]
Do you need to merge this?

**Comment by adrian-prantl** [comment]
Yes, I'm just completely behind with everything at the moment :-(

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/30303
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/30303
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/30303
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/30303
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/30303
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/30303
@swift-ci test

**Pull request merged**
