### PR TITLE
[rebranch] LLDB compilation fixes

### PR DESCRIPTION
**Pull request by bnbarham**
This gets LLDB to a compiling state on at least MacOS arm64. Mostly it's just cherry-picks, I'll need to go through stable/20211026 properly and make sure nothing else is missing.

I'm not sure what happened with the changes from https://reviews.llvm.org/D117490, I can only assume there were merge conflicts and it ended up being merged incorrectly. That's the fixes in 76f9bf23c6d50a47930d2bc8fa4d0af1a786ac48.

Other than that it's just ae79cdd9875804f422b3129dd9ba1fdcc247e2e9 which resulted from cherry-picking a similar change from both stable/20210726 and stable/20211026 (84db6bad8f08ffd47edbeb0366693105c4a4b468 and 8964971f93f5c84d47ba7e76dd97dba6e7d405fe).

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by medismailben** [comment]
@bnbarham All the changes related to the lldb log refactor should be listed in #3959 and #3974. However, I'm a bit confused because I thought I cherry-picked them to the next branch on #3974 ... Did I miss something ?

**Comment by bnbarham** [comment]
> @bnbarham All the changes related to the lldb log refactor should be listed in #3959 and #3974. However, I'm a bit confused because I thought I cherry-picked them to the next branch on #3974 ... Did I miss something ?

As I mentioned, I'm honestly not sure what happened. The files that were messed up weren't Swift-specific, so I assume what happened was that there was a merge conflict while merging LLVM tip -> Apple next and those just weren't fixed correctly. It's not super surprising since I imagine next wasn't building and thus fixing the conflicts was just a best effort.

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Compilation succeeds, it's just failing tests now.

**Review by JDevlieghere — APPROVED** [review]

**Pull request merged**
