### PR TITLE
[AArch64][CodeGen] Fix wrong operand order when creating vcmla intrin…

### PR DESCRIPTION
**Pull request by ellishg**
…sic (#65278)

### CODE REVIEW

**Comment by ellishg** [comment]
We've discovered a floating point miscompilation in XCode 16 when using `-ffp-contract=fast`. I found this patch that fixes the issue.

@fhahn can we get this merged into the release branch?

**Comment by ellishg** [comment]
Oh, and the patch did not cherry-pick cleanly so I had to fix the tests to make them pass on this branch.

**Comment by drodriguez** [comment]
@swift-ci please test llvm

**Comment by drodriguez** [comment]
@swift-ci please test

**Comment by drodriguez** [comment]
(I think the LLVM tests will fail in some cases, but hopefully not in the specific tests that the commit changes)

**Comment by drodriguez** [comment]
About  the LLVM Test failures:

I left a comment about `ExtractAPI/enum.c` last week in https://github.com/swiftlang/llvm-project/pull/8987#issuecomment-2237153895

For the `Driver/` ones is probably because https://github.com/swiftlang/llvm-project/pull/8668 is in `stable/20230725`, but not in `swift/release/6.0` (has been like that a couple of months)

**Comment by ellishg** [comment]
Friendly ping @fhahn @ravikandhadai

**Comment by ravikandhadai** [comment]
cc @Gerolf-Apple

**Comment by fhahn** [comment]
Unfortunately I think it is too late at this point in the release to take this change.

**Comment by drodriguez** [comment]
Should it be applied to `stable/20230725` at least so it is used by a future Swift 6.0.x release? What's the process to get it in the next release before `stable/20240723` is used?

**Comment by ellishg** [comment]
This is a critical codegen fix. If it isn't picked, some floating point operations will simply give the wrong result. Also, the non-test changes are pretty simple and safe in my opinion.

**Review by Gerolf-Apple — COMMENTED** [review]
Looks good to me.

**Review by Gerolf-Apple — APPROVED** [review]

**Comment by drodriguez** [comment]
@Gerolf-Apple are you able to merge into this branch for us? Is this the right branch to merge at this point?

**Comment by Gerolf-Apple** [comment]
We will need to get this on a newer branch.

**Comment by fhahn** [comment]
It looks like the commit is already on  `stable/20240723` which should be the correct one for the next release.

```
commit 9ef15f4109890b2ad1e7ac714e4398d44b2087ff
Author: daisy202309 <144047963+daisy202309@users.noreply.github.com>
Date:   Thu Sep 14 12:10:16 2023 +0800

    [AArch64][CodeGen] Fix wrong operand order when creating vcmla intrinsic (#65278)
```

**Comment by ellishg** [comment]
> It looks like the commit is already on `stable/20240723` which should be the correct one for the next release.
> 
> ```
> commit 9ef15f4109890b2ad1e7ac714e4398d44b2087ff
> Author: daisy202309 <144047963+daisy202309@users.noreply.github.com>
> Date:   Thu Sep 14 12:10:16 2023 +0800
> 
>     [AArch64][CodeGen] Fix wrong operand order when creating vcmla intrinsic (#65278)
> ```

Thanks for checking. I'll close this then.

**Pull request closed without merging**
