### PR TITLE
[ConstantRange] Fix miscompile caused by off by 1 bugs in UIToFP and SIToFP handling

### PR DESCRIPTION
**Pull request by AZero13**
We were passing the min and max values of the range to the ConstantRange
constructor, but the constructor expects the upper bound to 1
more than the max value so we need to add 1.

We also need to use getNonEmpty so that passing 0, 0 to the constructor
creates a full range rather than an empty range. And passing smin, smax+1
doesn't cause an assertion.

This is significant because this fixes a miscompile regarding Float2Int when
the float converts to a very large integer.

(cherry picked from commit https://github.com/llvm/llvm-project/commit/12836467b76c56872b4c22a6fd44bcda696ea720)

### CODE REVIEW

**Comment by AZero13** [comment]
See: https://godbolt.org/z/Kbsza5K63

**Comment by AZero13** [comment]
@adrian-prantl

**Comment by JDevlieghere** [comment]
It looks like we have the same bug upstream. Any reason not to fix it there and then cherrypick the fix to the relevant Apple branches?

**Comment by AZero13** [comment]
> It looks like we have the same bug upstream. Any reason not to fix it there and then cherrypick the fix to the relevant Apple branches?

It's merged upstream now.

**Comment by AZero13** [comment]
@JDevlieghere Now that this code is merged upstream and is being backported to the release branch.

**Comment by JDevlieghere** [comment]
Can you please cherrypick the upstream commit with `-x`? This helps engineers, our qualification team and automation trace this back to the corresponding upstream commit if they encounter any issues. Besides that this LGTM.

**Comment by AtariDreams** [comment]
-x https://github.com/llvm/llvm-project/commit/12836467b76c56872b4c22a6fd44bcda696ea720

**Comment by AtariDreams** [comment]
> Can you please cherrypick the upstream commit with `-x`? This helps engineers, our qualification team and automation trace this back to the corresponding upstream commit if they encounter any issues. Besides that this LGTM.

Like this? Sorry, this is new to me

**Comment by JDevlieghere** [comment]
I meant cherrypicking the upstream commit to the branch for this PR with: 

```
git cherry-pick -x 12836467b76c56872b4c22a6fd44bcda696ea720
```

The `-x` adds a little trailer at the bottom saying "cherry picked from commit 12836467b76c56872b4c22a6fd44bcda696ea720". Here's an example of one of my PRs that showcases this: https://github.com/apple/llvm-project/pull/8414

**Comment by AZero13** [comment]
> I meant cherrypicking the upstream commit to the branch for this PR with:
> 
> ```
> git cherry-pick -x 12836467b76c56872b4c22a6fd44bcda696ea720
> ```
> 
> The `-x` adds a little trailer at the bottom saying "cherry picked from commit [1283646](https://github.com/apple/llvm-project/commit/12836467b76c56872b4c22a6fd44bcda696ea720)". Here's an example of one of my PRs that showcases this: #8414

Thank you!

**Comment by AZero13** [comment]
@JDevlieghere Is this good?

**Comment by AZero13** [comment]
I don't have perms to do swift ci tests or whatever by the way that's why I ask.

**Comment by adrian-prantl** [comment]
Could you please rebase this on `swift/release/6.0` which automerges into `stable/20230725` and change the target branch accordingly?

**Comment by AZero13** [comment]
> Could you please rebase this on `swift/release/6.0` which automerges into `stable/20230725` and change the target branch accordingly?

Done!

**Comment by AtariDreams** [comment]
https://github.com/apple/llvm-project/pull/8451

**Review by JDevlieghere — APPROVED** [review]
Thanks for bearing with us!

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test llvm

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by AZero13** [comment]
@adrian-prantl @JDevlieghere Are these results okay?

**Pull request merged**
