### PR TITLE
Introduce LockGuarded and make swift::ASTContext accesses thread safe

### PR DESCRIPTION
**Pull request by augusto2112**
swift::ASTContext is not thread safe by default, wrap SwiftASTContext's swift::ASTContext in a LockGuarded.

rdar://121409294

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
Will this work when someone calls CompilerType::GetBitSize() for example?

**Comment by adrian-prantl** [comment]
> Will this work when someone calls CompilerType::GetBitSize() for example?

Nevermind. You created a thread-safe `swift::ASTContext` not a `SwiftASTContext`.

**Review by adrian-prantl — APPROVED** [review]

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci test Windows

**Pull request merged**
