### PR TITLE
[Swift] Stop forcing the triple, we can infer it automatically.

### PR DESCRIPTION
**Pull request by dcci**

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
I understand this needs to land on `2^aleph_zero` branches, and this is not the right one, but I just want a review to make sure this is fine.

**Review by jimingham — APPROVED** [review]
I have no idea why this was necessary at some time in the past.   And why these two tests and no others?  This seems like a wart that it's best to get rid of.

There are two more tests with this construct, ./functionalities/mtc/swift-property and ./functionalities/mtc/swift.  Probably should remove it from those tests as well.

**Review by adrian-prantl — APPROVED** [review]
In this particular case this really seems to be unnecessary.

**Pull request merged**
