### PR TITLE
[🍒][apinotes][cxx-interop] Add support for namespaces, nested tags, and methods.

### PR DESCRIPTION
**Pull request by zoecarver**

### CODE REVIEW

**Comment by zoecarver** [comment]
@swift-ci please test.

**Review by compnerd — CHANGES_REQUESTED** [review]
This should go upstream first.  Most of the infrastructure is already upstreamed, and this is unnecessarily increasing divergence between the two branches.  This only makes it more difficult to remove the differences.

**Comment by zoecarver** [comment]
@swift-ci Please Build Toolchain macOS Platform

**Comment by zoecarver** [comment]
@swift-ci please test.

**Pull request merged**
