### PR TITLE
[lldb] Fix missing characters when autocompleting LLDB commands in REPL

### PR DESCRIPTION
**Pull request by poya**
When tabbing to autocomplete LLDB commands in the Swift REPL, characters would at best be missing from the completed command, but at worst cause the REPL to crash due to out of range string access

https://bugs.swift.org/browse/SR-12867

### CODE REVIEW

**Comment by poya** [comment]
Realized that the main code change should probably go to the upstream, and only the test belongs here

**Comment by poya** [comment]
Fix in https://reviews.llvm.org/D82835 and tests in this PR

**Comment by poya** [comment]
@Teemperor Please have a look at this accompanying Swift REPL test for https://reviews.llvm.org/D82835

**Comment by Teemperor** [comment]
LGTM, thanks for fixing this!

**Pull request merged**
