### PR TITLE
[6.0 🍒][clang][deps] Collect discovered module dependencies' Link Libraries

### PR DESCRIPTION
**Pull request by artemcm**
Cherry-pick of https://github.com/llvm/llvm-project/pull/93588
----------------------------
**Explanation**: This will allow scanner clients to be able to compute e.g. auto-linking dependencies of the scanned translation unit.

**Risk**: Low. This change is additive and does not exercise meaningfully-changed code-paths.

**Testing**: Automated test added to the compiler test suite.

**Reviewed By**: @benlangmuir

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test Windows platform

**Comment by artemcm** [comment]
@swift-ci test

**Review by nkcsgexi — APPROVED** [review]

**Comment by NuriAmari** [comment]
@nkcsgexi @artemcm I think a couple more tests need updating: https://github.com/apple/llvm-project/pull/8856

**Comment by nkcsgexi** [comment]
ah, thank you for updating them, @NuriAmari !

**Comment by NuriAmari** [comment]
> ah, thank you for updating them, @NuriAmari !

@nkcsgexi No problem, but I can't merge or run tests myself, nor am I sure which branches to merge into. If someone could take a look at the PR, that'd be great. Thanks.

**Pull request merged**
