### PR TITLE
Also disable flang test on [Fedora] Linux

### PR DESCRIPTION
**Pull request by davezarzycki**
See #63 and #69.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test platform

**Comment by davezarzycki** [comment]
@shahmishal – Looks like @swift-ci is ignoring me because I don't have write access to the repo. I also can't add you as a reviewer for some reason. Weird.

**Comment by davezarzycki** [comment]
@swift-ci please test platform

**Comment by davezarzycki** [comment]
@shahmishal – Thanks for the commit access. For future reference: where are the docs for the stable/$DATE branches and in particular, when/where should pull requests target stable/$DATE versus just swift/master? Would it have been okay if I just requested that this be merged into swift/master? Thanks!

**Review by hyp — APPROVED** [review]
LGTM

**Comment by hyp** [comment]
@davezarzycki swift/master is reserved for LLDB changes only. @JDevlieghere is working on automerger graph that we can add to the README to show the merge graph to explain this better.

**Comment by davezarzycki** [comment]
Okay. Is `apple/stable/20190619` the right place for this fix? And yes, it would be nice if this were documented.

**Comment by davezarzycki** [comment]
Ping. Is apple/stable/20190619 the right place for this fix?

**Comment by shahmishal** [comment]
I recommend this change should be made on `apple/llvm-project:apple/master`, if it can't be made on `llvm/llvm-project:master`. However, it should still be on `apple/stable/20190619` branch.

* `apple/stable/20190619` branch was created from `apple/master` on June 19 2019
* `apple/stable/20190619` gets automerged into `swift/master` branch.

**Comment by davezarzycki** [comment]
@shahmishal – This is fallout from cherry-picking changes so LLVM proper doesn't need this fix. If I understand you correctly, I need two pull requests? One for `apple/master` and one for `apple/stable/20190619`?

**Comment by davezarzycki** [comment]
@shahmishal – Ping. If I understand you correctly, I need two pull requests? One for apple/master and one for apple/stable/20190619?

**Comment by shahmishal** [comment]
@davezarzycki Yes, that is correct.

**Pull request merged**
