### PR TITLE
[rebranch] Cherry-pick dependency scanner changes post branch

### PR DESCRIPTION
**Pull request by bnbarham**
These just missed the branch, cherry-pick to stable/20230725

### CODE REVIEW

**Comment by bnbarham** [comment]
I've built locally and rebranch is currently blocked anyway, so going to go ahead and merge.

**Comment by artemcm** [comment]
I think this means we need to revert https://github.com/apple/swift/pull/67880.

**Comment by artemcm** [comment]
Ah I see it https://github.com/apple/swift/pull/67888


Thank you @bnbarham

**Comment by bnbarham** [comment]
Ah yeah, sorry should have mentioned I did that here 👍. Like I said, did a local build and that wouldn't have worked without the revert of the revert 😅

**Pull request merged**
