### PR TITLE
[lldb] Override override attribute in TestDumpPCMInfo

### PR DESCRIPTION
**Pull request by augusto2112**

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
Thank you, I just noticed this from failures on other PRs. I am not sure how it didn't fail on the original PR #4968 🤔

**Review by kastiglione — APPROVED** [review]

**Comment by kastiglione** [comment]
I had put up a PR before seeing this, and somehow mine finished testing before this. So I merged that one to prevent further CI failures. This can be closed now.

**Comment by augusto2112** [comment]
Thanks!

**Pull request closed without merging**
