### PR TITLE
Avoid calling os.chdir() in test.

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
This may or may not explain flakyness in the tests.

**Comment by jimingham** [comment]
It looks like the test suite already resets the cwd to the source directory before beginning a new test, so the chdir that you are removing should not be necessary, but mostly because it's redundant.

However, I can't see how it would have caused the test to be flakey?

**Comment by adrian-prantl** [comment]
Yeah, I think you are right. 
I recently removed all instances of os.chdir from tests and it may be that not all of them had a cleanup action registered. I'd still feel better about not changing global state in any test so at least I don't have to go back thinking whether this could have an unintended impact.

**Comment by adrian-prantl** [comment]
We keep having very rare test failures where tests suddenly hit the wrong number of breakpoints and my best guess is that, for example, we are attaching to the wrong a.out so I'm trying to eliminate all possible avenues where such a thing might happen

**Review by kastiglione — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by jimingham** [comment]
Yeah, I always thought it was a little unfortunate that we didn't have a system that would base executable names off of the test name or something, so that we couldn't make this kind of mistake...  But short of that this seems a reasonable thing to try.

Jim

**Comment by adrian-prantl** [comment]
> Yeah, I always thought it was a little unfortunate that we didn't have a system that would base executable names off of the test name or something, so that we couldn't make this kind of mistake... But short of that this seems a reasonable thing to try. 

That is still (way down) on my list to figure out who the `a.out` zombies are that tend to accumulate on the bots.

**Pull request merged**
