### PR TITLE
[Swift] Build a 'do { ... }' instead of a 'repeat { ... } while 1 == 0'

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Review by adrian-prantl — APPROVED** [review]
That's a nice cleanup! Please don't forget to cherry-pick this to swift/rebranch and swift/next

**Comment by slavapestov** [comment]
@swift-ci Please clean test Linux

**Comment by slavapestov** [comment]
@swift-ci Please test Linux

**Pull request merged**
