### PR TITLE
[apple-ci] Add github swift-ci automation PR script for testing LLVM

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Adding script for testing PR on apple github.

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please test llvm

**Comment by cachemeifyoucan** [comment]
@swift-ci please test llvm

**Comment by cachemeifyoucan** [comment]
@swift-ci please test llvm

**Comment by shahmishal** [comment]
@swift-ci please test llvm macOS

**Comment by cachemeifyoucan** [comment]
@swift-ci please test llvm linux

**Comment by cachemeifyoucan** [comment]
@swift-ci please test llvm

**Pull request merged**
