### PR TITLE
[lldb] Add test for Swift.DecodingError enum

### PR DESCRIPTION
**Pull request by kastiglione**
rdar://126563813

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
Please recreate this against a newer branch.

**Comment by kastiglione** [comment]
https://github.com/swiftlang/llvm-project/pull/9115

**Pull request closed without merging**
