### PR TITLE
[lldb] Report clang module build remarks

### PR DESCRIPTION
**Pull request by kastiglione**
Update the Clang diagnostic consumer (in ClangModulesDeclVendor) to report
progress on Clang module builds, as both progress events and expression logs.

Module build remarks are enabled by with clang's `-Rmodule-build` flag.

With this change, command line users of lldb will see progress events showing
which modules are being built, and - by how long they stay on screen - how much
time it takes to build them. IDEs that show progress events can show these
updates if desired.

This does not show module-import remarks, although that may be added as a
future change.

Differential Revision: https://reviews.llvm.org/D140056

(cherry picked from commit 9c5b97570502c5c6648730f75d097910ae2faa22)

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
Also including https://reviews.llvm.org/D147248

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
Also cherry picking [D143687](https://reviews.llvm.org/D143687) and [D143690](https://reviews.llvm.org/D143690)

**Comment by kastiglione** [comment]
@swift-ci test

**Review by JDevlieghere — APPROVED** [review]

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Pull request merged**
