### PR TITLE
Crashlog help

### PR DESCRIPTION
**Pull request by medismailben**
- [lldb] Add long help to crashlog
- [lldb] Print message after loading 'crashlog' command
- [lldb/crashlog] Show help when the command is called without any argument

### CODE REVIEW

**Comment by medismailben** [comment]
@swift-ci test

**Comment by medismailben** [comment]
Add missing commit 967dd8fe300fc6dee28723be278ea1f0efbacbb8

**Comment by medismailben** [comment]
@swift-ci test

**Comment by medismailben** [comment]
@kastiglione am I missing any of your patches ?

**Review by kastiglione — APPROVED** [review]

**Comment by kastiglione** [comment]
I think you've got it covered. thanks!

**Review by adrian-prantl — APPROVED** [review]

**Pull request merged**
