### PR TITLE
[🍒][-Wunsafe-buffer-usage] Warning unsafe libc calls

### PR DESCRIPTION
**Pull request by ziqingluo-90**
cherry-picked from `swiftlang/llvm-project/next`

### CODE REVIEW

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by ziqingluo-90** [comment]
I somehow can't find @jkorous-apple in the reviewer list.

**Comment by haoNoQ** [comment]
> I somehow can't find @jkorous-apple in the reviewer list.

Doesn't work for me either hmm.

**Comment by jkorous-apple** [comment]
Weird, I am here 🤷 
So, do IIUC we want to hold-off merging this until we land the changes VendorOverrides internally?

**Comment by ziqingluo-90** [comment]
> Weird, I am here 🤷 So, do IIUC we want to hold-off merging this until we land the changes VendorOverrides internally?

yeah, that works the best.

**Comment by ziqingluo-90** [comment]
Rebased, and @swift-ci test

**Comment by ziqingluo-90** [comment]
Rebased, and @swift-ci test

**Comment by ziqingluo-90** [comment]
Rebased, and @swift-ci test

**Comment by jkorous-apple** [comment]
LGTM

**Review by haoNoQ — APPROVED** [review]

**Pull request merged**
