### PR TITLE
Surface fatal errors in VALIDATE_OR_RETURN

### PR DESCRIPTION
**Pull request by adrian-prantl**
This is going to help understand what's going on when the macro is triggered.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
I like this implementation better than my first attempt.

**Review by augusto2112 — APPROVED** [review]

**Review by kastiglione — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test Linux

**Pull request merged**
