### PR TITLE
Various warning and compilation fixes for stable/20211026

### PR DESCRIPTION
**Pull request by bnbarham**

### CODE REVIEW

**Comment by bnbarham** [comment]
@JDevlieghere feel free to check everything, but the last few commits would be good to look at:
  - 22c9a68: I just added `-DLLDB_USE_STATIC_BINDINGS:BOOL=OFF` and then ran `copy-static-bindings.py`, is there anything else to do there? Seems to pass locally with `-DLLDB_USE_STATIC_BINDINGS:BOOL=ON` now.
  - a0d730e: not 100% sure what happened here, but this looks like left over code (had a warning for missing Invalid)
  - 89eca2e: is passing `false` for `requiresOSSAModules` in the call to `validateSerializedAST` correct?
  - 52874b1: what do we actually want to dump here? I've just left an empty dump in `TypeSystemSwift` for now, but I assume we'll actually want to dump *something* in its subclasses.

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
Adding @adrian-prantl for the Swift-related changes in LLDB.

**Comment by JDevlieghere** [comment]
> @JDevlieghere feel free to check everything, but the last few commits would be good to look at:
> 
> * [22c9a68](https://github.com/apple/llvm-project/commit/22c9a68709b153c498d7f3d8ee5bc13fbae64bba): I just added `-DLLDB_USE_STATIC_BINDINGS:BOOL=OFF` and then ran `copy-static-bindings.py`, is there anything else to do there? Seems to pass locally with `-DLLDB_USE_STATIC_BINDINGS:BOOL=ON` now.

Perfect.

> * [a0d730e](https://github.com/apple/llvm-project/commit/a0d730e72dbbcfed45e2f13e80721f75ed02a4b5): not 100% sure what happened here, but this looks like left over code (had a warning for missing Invalid)

@jimingham can you please double check?

> * [89eca2e](https://github.com/apple/llvm-project/commit/89eca2eaf71adf091fd0e6f0ecdb3013267f4682): is passing `false` for `requiresOSSAModules` in the call to `validateSerializedAST` correct?
> * [52874b1](https://github.com/apple/llvm-project/commit/52874b14b4d4cdba67e4a4381caf007365884d8c): what do we actually want to dump here? I've just left an empty dump in `TypeSystemSwift` for now, but I assume we'll actually want to dump _something_ in its subclasses.

@adrian-prantl can you please double check?

**Comment by bnbarham** [comment]
I'm going to merge this to get the bots actually building. `Dump` will still need to be implemented, but we can do that later.

**Comment by jimingham** [comment]
> On Nov 16, 2021, at 9:09 AM, Jonas Devlieghere ***@***.***> wrote:
> 
> 
> @JDevlieghere feel free to check everything, but the last few commits would be good to look at:
> 
> 	• 22c9a68: I just added -DLLDB_USE_STATIC_BINDINGS:BOOL=OFF and then ran copy-static-bindings.py, is there anything else to do there? Seems to pass locally with -DLLDB_USE_STATIC_BINDINGS:BOOL=ON now.
> Perfect.
> 
> 	• a0d730e: not 100% sure what happened here, but this looks like left over code (had a warning for missing Invalid)
> @jimingham can you please double check?

That code got moved to ValueObjectVariable::DoUpdateChildrenAddressType, and shouldn't be in ValueObjectVariable::UpdateValue.  If you expand the file in the patch you referred to, this code is properly in the DoUpdate method.  So everything is right once yp remove the redundant copy.

This looks right to me.

Jim

**Comment by bnbarham** [comment]
> That code got moved to ValueObjectVariable::DoUpdateChildrenAddressType, and shouldn't be in ValueObjectVariable::UpdateValue. If you expand the file in the patch you referred to, this code is properly in the DoUpdate method. So everything is right once yp remove the redundant copy. This looks right to me. Jim

Thanks for checking! Sorry, I should have been more clear in the comment itself - the commit message mentions the duplicate code + relevant commits.

**Pull request merged**
