### PR TITLE
Fix Stable20210726 lldb Release Builds

### PR DESCRIPTION
**Pull request by gmittert**
ShouldSkipValidation is only defined #ifndef NDEBUG so it should only be
called #ifndef NDEBUG

### CODE REVIEW

**Comment by gmittert** [comment]
cc @augusto2112 @adrian-prantl

**Comment by gmittert** [comment]
@swift-ci please test

**Review by adrian-prantl — APPROVED** [review]
Thanks, Gwen! Could you cherry-pick this to next/, too?

**Comment by augusto2112** [comment]
Thanks!

**Comment by gmittert** [comment]
Cherrypicked in PR https://github.com/apple/llvm-project/pull/3479. I don't have write access to llvm-project, so someone will have to merge it for me. Does PR testing work on next?

**Comment by adrian-prantl** [comment]
> Cherrypicked in PR #3479. I don't have write access to llvm-project, so someone will have to merge it for me. Does PR testing work on next?

Usually the Swift compiler doesn't build ...

**Pull request merged**
