### PR TITLE
fdepscan: Continue unifying code paths; mostly NFC

### PR DESCRIPTION
**Pull request by dexonsmith**
No important functional changes here, just unifying a few code paths
that were diverged because of history of driver vs. separate tool.

### CODE REVIEW

**Comment by dexonsmith** [comment]
This is a WIP. There are a couple of test failures because error handling isn't quite right when bad options are passed. Posting anyway as an FYI.

@swift-ci test

**Comment by dexonsmith** [comment]
Note, for context, I pushed a number of commits ahead of this:

- 961d2cb3fc49 fdepscan: Give updateCC1Args and CC1ScanDeps better names, NFC
- f58dfd3e2f1e fdepscan: Inline and delete addCC1ScanDepsArgsInline
- 4c22f86e8d7c fdepscan: Move the daemon protocol from the driver lib to tool, NFC
- 7ba76fd74989 fdepscan: Make -fdump-depscan-tree work even with a daemon
- fe88685c4f4c fdepscan: Rename `scanAndUpdateCC1*()` more before simplifying, NFC

**Comment by dexonsmith** [comment]
Fixed in the updated version, f320684a23514cdf30c2aa15776aeffbd2abf27d. Problem was an overly broad `return 1` statement (whenever the daemon was used, instead of just when the daemon had an error).

@swift-ci test

**Comment by dexonsmith** [comment]
- 174eccec91697cf4d924fed032e0240e49bf4745 works around the old clang on the bot not knowing how to implicitly move a returned Error to Expected.
- c634f2f690bb01da3b699e1a793c5b9b3ccf209d updates `-fdepscan=daemon`'s output to exactly match `-fdepscan=inline`. I looked more deeply into some odd logic I'd replicated in the main commit here for parsing args sent over by the daemon, and it turns out it shouldn't really have worked except by louck. It's more obvious why it works now :). I added a test to ensure the two stay in sync.

**Comment by dexonsmith** [comment]
And:
- 2b3c9950297d89a15d4bf8d28c5b7fdb7747c33c adds a FIXME for using the CAS to communicate with the daemon. It doesn't make sense to be sending command-lines / etc. over a socket. We should just send a single ID over to describe the job, and get a single ID back to describe the result.

**Comment by dexonsmith** [comment]
@swift-ci test

**Comment by akyrtzi** [comment]
> * [2b3c995](https://github.com/apple/llvm-project/commit/2b3c9950297d89a15d4bf8d28c5b7fdb7747c33c) adds a FIXME for using the CAS to communicate with the daemon. It doesn't make sense to be sending command-lines / etc. over a socket. We should just send a single ID over to describe the job, and get a single ID back to describe the result.

I'm not sure I agree that "it doesn't make sense", these are "ephemeral" pieces of information, they have no value beyond an IPC call, should they really be taking up permanent storage?

**Comment by dexonsmith** [comment]
> > * [2b3c995](https://github.com/apple/llvm-project/commit/2b3c9950297d89a15d4bf8d28c5b7fdb7747c33c) adds a FIXME for using the CAS to communicate with the daemon. It doesn't make sense to be sending command-lines / etc. over a socket. We should just send a single ID over to describe the job, and get a single ID back to describe the result.
> 
> I'm not sure I agree that "it doesn't make sense", these are "ephemeral" pieces of information, they have no value beyond an IPC call, should they really be taking up permanent storage?

The command lines repeat over and over again, with far more redundancy than the sources. In aggregate, they are free.

**Comment by dexonsmith** [comment]
> > > * [2b3c995](https://github.com/apple/llvm-project/commit/2b3c9950297d89a15d4bf8d28c5b7fdb7747c33c) adds a FIXME for using the CAS to communicate with the daemon. It doesn't make sense to be sending command-lines / etc. over a socket. We should just send a single ID over to describe the job, and get a single ID back to describe the result.
> > 
> > 
> > I'm not sure I agree that "it doesn't make sense", these are "ephemeral" pieces of information, they have no value beyond an IPC call, should they really be taking up permanent storage?
> 
> The command lines repeat over and over again, with far more redundancy than the sources. In aggregate, they are free.

(But if you still disagree, I can revert that commit / remove the FIXME.)

**Comment by akyrtzi** [comment]
> The command lines repeat over and over again, with far more redundancy than the sources. In aggregate, they are free.

The ID you get back will change along with the sources and, even for the command-line input, why *not* prefer to send it via the socket?
Essentially you have a socket IPC (that is still necessary even if you switch to IDs) and:

1. Either pass the info, that the other IPC side is waiting for, directly via the socket
2. Or write out the info into semi-permanent storage on the file system, and let the other side through the socket know how to find the info from the file system

It's not clear to me why (2) is much preferable between these options.

> (But if you still disagree, I can revert that commit / remove the FIXME.)

I'd prefer to remove it, we can re-evaluate later if it becomes more compelling. E.g. say potentially in the future the build system encodes command-lines in the CAS already.

**Comment by dexonsmith** [comment]
> > The command lines repeat over and over again, with far more redundancy than the sources. In aggregate, they are free.
> 
> The ID you get back will change along with the sources

That doesn't have to affect the command-lines.

- The command-line being sent to the daemon will be stable
- The command-line being returned will be stable if the daemon skips `-fcas-fs` (or uses a placeholder), and let's the client add it instead

> and, even for the command-line input, why _not_ prefer to send it via the socket? Essentially you have a socket IPC (that is still necessary even if you switch to IDs) and:
> 
> 1. Either pass the info, that the other IPC side is waiting for, directly via the socket
> 2. Or write out the info into semi-permanent storage on the file system, and let the other side through the socket know how to find the info from the file system
> 
> It's not clear to me why (2) is much preferable between these options.

Is (2) supposed to be the CAS?

If so, I'm a bit confused about your perspective here. You make it sound like it's a complicated dance to "somehow find the info from the filesystem", but this entire model is predicated on being able to transfer data safely/consistently/quickly via the CAS, and the client and daemon already communicate via the CAS.

In terms of why sending an arbitrarily large command-line is better to do in the CAS vs over a socket:
- Socket protocols are hard to test; making the socket protocol stupidly simple reduces the burden (once we start testing)
- Sockets are slow and we can't optimize them; the CAS needs to be fast
- Already depend on communicating via the CAS so no increase in complexity
- There's effectively no storage cost, since the sources will change significantly more than the command-lines (command-lines will repeat exactly across incremental compilations)
- If we transfer command-lines via the CAS, we have the opportunity to optimize their serialization for the CAS. In particular, we can make each CompilerInvocation options structure a different CAS object (`CompilerInvocation::generateCC1CommandLine()` would be easy to modify for this due to its structure). Most compilations in a target will share most sub-objects. Although I'm not sure this is worth doing, since I expect command-lines themselves are already relatively cheap compared to the sources.

> > (But if you still disagree, I can revert that commit / remove the FIXME.)
> 
> I'd prefer to remove it, we can re-evaluate later if it becomes more compelling. E.g. say potentially in the future the build system encodes command-lines in the CAS already.

21885a9cd1d48931a9e8349335e0ed66b27cc0fb

**Comment by akyrtzi** [comment]
> Sockets are slow and we can't optimize them; the CAS needs to be fast

It would be interesting to measure sending the command-lines via the socket vs putting them in the CAS and sending the IDs.
(We could also consider using mach ports if socket performance is an issue).

> There's effectively no storage cost

All the command-lines will take up permanent storage; you can say that it's small enough and with small growth when the project changes but "no storage cost" seems a bit inaccurate.

> If we transfer command-lines via the CAS, we have the opportunity to optimize their serialization for the CAS.

But we wouldn't need to optimize their serialization for the CAS if we don't put them in the CAS in the first place, right?
Specifically, it shouldn't technically be a requirement that command-lines get stored in the CAS for the sole reason of forming their input hash key for a cached compilation.

**Comment by dexonsmith** [comment]
> > Sockets are slow and we can't optimize them; the CAS needs to be fast
> 
> It would be interesting to measure sending the command-lines via the socket vs putting them in the CAS and sending the IDs. (We could also consider using mach ports if socket performance is an issue).

I'd be surprised if either one showed up on a profile. If the CAS showed up on a profile, I would take that as a sign that we were missing important optimizations. We want small things to be fast.

> > There's effectively no storage cost
> 
> All the command-lines will take up permanent storage; you can say that it's small enough and with small growth when the project changes but "no storage cost" seems a bit inaccurate.

Sure. I think it's in the noise, something like ~1% of what we'll be storing overall for a single build. I would guess closer to 0.01% when you include incremental builds.

In my mind, that makes the storage cost "effectively none". But the point is that it's disappearingly small.

> > If we transfer command-lines via the CAS, we have the opportunity to optimize their serialization for the CAS.
> 
> But we wouldn't need to optimize their serialization for the CAS if we don't put them in the CAS in the first place, right? 

We don't *need* to optimize their serialization at all, since the storage cost will be disappearingly small.

Hence:

>> Although I'm not sure this is worth doing

That said, it is an *opportunity* to take advantage of the CAS to avoid doing redundant work.
- The current approach transfers many nearly identical command-lines to the daemon, once for each compilation. This is wasteful.
- Structuring the command-line allows that redundant work to be avoided, doing less work in aggregate during the build.

A micro-optimization that's probably not worth doing—the costs are hidden behind the cost of the dependency scan—but an opportunity that's only available if we're using the CAS.

Overall, I'm inclined to use a fractal approach to modelling data. If we're going to use the CAS for big things, why not use it for small things? If we're going to avoid redundancy for big tasks, why not avoid redundancy for small tasks? (I mean, if it's not worth doing because it's not a bottleneck, happy enough with a FIXME.)

> Specifically, it shouldn't technically be a requirement that command-lines get stored in the CAS for the sole reason of forming their input hash key for a cached compilation.

I don't disagree with this point, but I'm not sure why you're bringing up the action cache here. This sentence seems unrelated to the rest of the discussion. Can you explain?

**Comment by akyrtzi** [comment]
> I don't disagree with this point, but I'm not sure why you're bringing up the action cache here. This sentence seems unrelated to the rest of the discussion. Can you explain?

I thought when you mentioned "If we transfer command-lines via the CAS, we have the opportunity to optimize their serialization for the CAS" you were referring as the opportunity to optimize how we form the compilation cache key (which currently involves putting command-lines in the CAS. I guess I misunderstood and you meant it as "transferring the command-line can be optimized".

> That said, it is an opportunity to take advantage of the CAS to avoid doing redundant work.

To clarify, what is the redundant work that this avoids, the work by the kernel to transfer the command-line strings via the socket? The kernel does significant more work to send the command-line vs just the CAS ID?

> Overall, I'm inclined to use a fractal approach to modelling data. If we're going to use the CAS for big things, why not use it for small things?

I'm all for using the CAS for small things (I think we should eventually model an AST graph on it), I'm just a bit skeptical of using it for storing transient objects, that are only relevant in the context of an IPC transfer and not referenced/used anywhere else, unless there is some clear benefit for it.

**Pull request merged**
