### PR TITLE
[Swift REPL] Only print the interactive welcome message if stdin is a tty

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test platform

**Comment by vedantk** [comment]
Some of the tests may need fixing up, but this looks good to me otherwise.

**Comment by davezarzycki** [comment]
@swift-ci please test platform

**Comment by davezarzycki** [comment]
@swift-ci please test platform

**Comment by davezarzycki** [comment]
@swift-ci please test platform

**Comment by davezarzycki** [comment]
The Mac failure looks spurious.

@swift-ci please test macos platform

**Pull request merged**
