### PR TITLE
[LLDB] Cherrypick tablegen dependencies

### PR DESCRIPTION
**Pull request by JDevlieghere**
Cherry-pick tablegenify commits.

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
These are needed for the reproducer dump command.

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Pull request merged**
