### PR TITLE
[lldb] Support for -print-diagnostic-groups

### PR DESCRIPTION
**Pull request by DmT021**
This is a complimentary change to the change in compiler options https://github.com/swiftlang/swift/pull/76363

### CODE REVIEW

**Comment by DmT021** [comment]
@DougGregor PTAL

**Comment by DougGregor** [comment]
https://github.com/swiftlang/swift/pull/76363

@swift-ci please test

**Comment by DmT021** [comment]
The same issue as [here](https://github.com/swiftlang/swift/pull/76363#issuecomment-2343435822)

**Comment by DougGregor** [comment]
https://github.com/swiftlang/swift/pull/76363

@swift-ci please test Windows

**Pull request merged**
