### PR TITLE
[cherry-pick][swift/release/5.9] [lldb][cmake] Allow specifying custom libcxx for tests in standalone builds

### PR DESCRIPTION
**Pull request by Michael137**
Standalone builds currently do not set the `LLDB_HAS_LIBCXX`,
`LIBCXX_LIBRARY_DIR`, `LIBCXX_GENERATED_INCLUDE_DIR`.
These are necessary for API tests with `USE_LIBCPP` to run against
a custom built libcxx. Thus on all buildbots using standalone builds
(most notably the public swift-ci), the API tests always run against
the libcxx headers in the system SDK.

This patch introduces a new cmake variable `LLDB_TEST_LIBCXX_ROOT_DIR`
that allows us to point the tests in standalone builds to a custom
libcxx directory.

Since the user can control the libcxx location we can hard error if
no such custom libcxx build exists.

Differential Revision: https://reviews.llvm.org/D150954

(cherry picked from commit 2901ce3ac24799dacda21be3903d6d8294b70ea0)

### CODE REVIEW

**Comment by Michael137** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/66026

@swift-ci test

**Comment by Michael137** [comment]
@swift-ci Please test macOS platform

**Comment by Michael137** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/66026

@swift-ci Please test macOS platform

**Comment by Michael137** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/66026

@swift-ci Please test macOS platform

**Comment by Michael137** [comment]
The failing test is due to the newest libcxx causing `std::forward` to get mangled in a way that's not supported by the demangler that LLDB uses:
```
   frame #0: 0x0000000100006c28 a.out`_ZNSt3__17forwardB7v160000IRK3BarEEOT_Ru20__remove_reference_tIS4_E(__t=0x000000016fdfe7c4) at forward.h:26:29
   23   template <class _Tp>
   24   _LIBCPP_NODISCARD_EXT inline _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR _Tp&&
   25   forward(__libcpp_remove_reference_t<_Tp>& __t) _NOEXCEPT {
-> 26     return static_cast<_Tp&&>(__t);
   27   }
```

Probably a missing cherry-pick

**Comment by Michael137** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/66026

@swift-ci Please test

**Comment by Michael137** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/66026
https://github.com/apple/swift/pull/66018

@swift-ci Please test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/66026
@swift-ci test

**Comment by Michael137** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/66026

@swift-ci Please test

**Comment by Michael137** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/66026

@swift-ci Please test windows Platform

**Comment by Michael137** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/66026

@swift-ci Please test

**Comment by Michael137** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/66026

@swift-ci Please test windows Platform

**Comment by Michael137** [comment]
Please test with following PR:
https://github.com/apple/swift/pull/66026

@swift-ci Please test windows Platform

**Pull request merged**
