### PR TITLE
Cherry-pick patches to make StringRef to std::string conversion explicit. make string ref to string explicit (attempt 2)

### PR DESCRIPTION
**Pull request by varungandhi-apple**
The difference leads to compilation errors when merging from Swift's master -> master-next, as new code on Swift's master sometimes ends up relying on the StringRef -> std::string implicit conversion.

Instead, we sync up LLVM swift/master with LLVM swift/master-next in this respect to avoid this.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
Previous attempt: https://github.com/apple/llvm-project/pull/1461

**Comment by varungandhi-apple** [comment]
https://github.com/apple/swift/pull/32899

@swift-ci please smoke test

**Comment by JDevlieghere** [comment]
🤞

**Comment by varungandhi-apple** [comment]
apple/swift#32899

@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
apple/llvm-project#1462

@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
apple/swift#32899

@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
~~Turns out, two tiny commits were missing because the change was split over 4 commits. 🙃 This caused Linux only failures thanks to good old GCC 5.4.0 on Ubuntu 16.04.~~

Looks like this patch was broken up over almost 2 dozen commits, most of them to appease GCC 5.

**Comment by varungandhi-apple** [comment]
apple/swift#32899

@swift-ci please smoke test

**Comment by varungandhi-apple** [comment]
apple/swift#32899

@swift-ci please smoke test Linux platform

**Comment by varungandhi-apple** [comment]
apple/swift#32899

@swift-ci please test Linux platform

**Comment by varungandhi-apple** [comment]
Closing this PR. See https://github.com/apple/swift/pull/32899#issuecomment-659161630 for the plan. The TLDR is we fix only Swift master-next (in https://github.com/apple/swift/pull/32897) until the rebranch happens (see https://forums.swift.org/t/updating-llvm-project-swift-master-branch/38484), after which we will get all these commits on LLVM swift/master.

**Pull request closed without merging**
