### PR TITLE
Ensure lexical stack is non-empty when popping cleanups for synthesized properties

### PR DESCRIPTION
**Pull request by vedantk**
This essentially sets the state of the stable branch to match upstream.

Fixes rdar://57796656, by making sure that the lexical stack is non-empty when popping cleanups for synthesized properties.

### CODE REVIEW

**Comment by vedantk** [comment]
I will add a regression test upstream and add it to this PR.

**Review by adrian-prantl — APPROVED** [review]

**Comment by vedantk** [comment]
@swift-ci test macOS

**Comment by vedantk** [comment]
Hi @shahmishal, this ran 51566 of 51567 tests before timing out. Could we please force-merge this?

**Comment by vedantk** [comment]
Mishal and I just took a look. The tests added here passed.

`ThreadSanitizer-x86_64h :: Darwin/mach_vm_allocate.c` (Haswell variant) seems to be hanging on the bots. @yln, mind taking a look (possibly just disabling that test for now)?

**Pull request merged**
