### PR TITLE
Enable union support in DWARFImporter.

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://problem/55026321

Depends on https://github.com/apple/llvm-project/pull/472

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
This was somehow left over without me noticing. Thanks to @dcci for finding it!

**Comment by adrian-prantl** [comment]
rdar://problem/55026321

**Review by fredriss — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
