### PR TITLE
[5.9][lldb][cmake] Remove local rpaths from the build host on ELF platforms

### PR DESCRIPTION
**Pull request by finagolfin**
Cherrypick of #6456

__Explanation:__ Because lldb is built separately and last, the official snapshots of the Swift toolchain for linux have a bunch of `/home/build-user/` absolute runpaths from the CI in lldb executables and shared libraries:
```
> find swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-02-a-ubuntu20.04 -name "lib*\.so*"|xargs readelf -d|ag "File:|runpath"|ag /home/ -B1
File: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-02-a-ubuntu20.04/usr/lib/liblldb.so.13.0.0git
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/home/build-user/build/buildbot_linux/llvm-linux-x86_64/./lib:/home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux:$ORIGIN/../lib/swift/linux]
File: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-02-a-ubuntu20.04/usr/lib/liblldb.so
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/home/build-user/build/buildbot_linux/llvm-linux-x86_64/./lib:/home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux:$ORIGIN/../lib/swift/linux]
File: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-02-a-ubuntu20.04/usr/lib/liblldb.so.13git
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/home/build-user/build/buildbot_linux/llvm-linux-x86_64/./lib:/home/build-user/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux:$ORIGIN/../lib/swift/linux]
File: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-02-a-ubuntu20.04/usr/lib/clang/13.0.0/lib/linux/libclang_rt.memprof-x86_64.so
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/home/build-user/build/buildbot_linux/llvm-linux-x86_64/./lib]
File: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-02-a-ubuntu20.04/usr/lib/clang/13.0.0/lib/linux/libclang_rt.ubsan_minimal-x86_64.so
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/home/build-user/build/buildbot_linux/llvm-linux-x86_64/./lib]

> readelf -d swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-02-a-ubuntu20.04/usr/bin/*|ag "File:|runpath"|ag /home/ -B1
File: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-02-a-ubuntu20.04/usr/bin/lldb
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/home/build-user/build/buildbot_linux/llvm-linux-x86_64/./lib]
File: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-02-a-ubuntu20.04/usr/bin/lldb-argdumper
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/home/build-user/build/buildbot_linux/llvm-linux-x86_64/./lib]
File: swift-5.9-DEVELOPMENT-SNAPSHOT-2023-05-02-a-ubuntu20.04/usr/bin/lldb-server
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/home/build-user/build/buildbot_linux/llvm-linux-x86_64/./lib]
```
This pull merges two upstream commits that fix that, along with a local commit for just the Swift runpaths, which also adds rpath support for more platforms, like Android and the BSDs.

__Scope:__ Only affects runpaths on ELF platforms like linux

__Issue:__ None

__Risk:__ low, as it only affects runpaths for ELF platforms

__Testing:__ Passed all CI, including a trunk toolchain build that worked well

__Reviewer:__ @JDevlieghere

### CODE REVIEW

**Comment by finagolfin** [comment]
Ping @fredriss, please let me know what you think.

**Comment by finagolfin** [comment]
Ping @ravikandhadai, since this affects all the LLVM sub-projects, maybe you can review.

**Comment by finagolfin** [comment]
@JDevlieghere, can we get this in?

**Review by JDevlieghere — APPROVED** [review]

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by finagolfin** [comment]
Thanks for pushing this through, @JDevlieghere. I'd like to nominate the upstream commits for the 16.0.5 release, what do you think?

**Comment by JDevlieghere** [comment]
> Thanks for pushing this through, @JDevlieghere. I'd like to nominate the upstream commits for the 16.0.5 release, what do you think?

Sure, I'm happy to sign off on the LLDB parts.

**Pull request merged**
