### PR TITLE
[cmake] Enable -Wmisleading-indentation

### PR DESCRIPTION
**Pull request by kastiglione**
Enable `-Wmisleading-indentation` to balance with the LLVM style of optional parentheses.

Differential Revision: https://reviews.llvm.org/D102092

(cherry picked from commit f44c6f20f5e9976357b4851c4432d96b4e4d3521)

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test macOS Platform

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
Is the Swift compiler clean?

**Comment by kastiglione** [comment]
Changed merge target to `swift/main`.

**Comment by kastiglione** [comment]
> Is the Swift compiler clean?

I'll verify

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
commit is on `swift/next`.

**Pull request closed without merging**
