### PR TITLE
Add missing nullptr checks after SwiftLanguageRuntimeImpl::GetTypeInfo()

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://73749956

### CODE REVIEW

**Comment by jimingham** [comment]
It's a little confusing that this function from SwiftLanguageRuntimeImpl.h is called GetTypeInfo.  There is much more common GetTypeInfo defined in TypeSystem.h (implemented in TypeSystemSwiftTypeRef and TypeSystemCland, etc.) that returns a uint32_t of flags.  It's made more confusing because you use auto for the return type, so it isn't immediately clear you are looking at a different beast here.

Anyway, since this thing returns a pointer that can be null, shouldn't we be using an Expected?

**Comment by adrian-prantl** [comment]
> It's a little confusing that this function from SwiftLanguageRuntimeImpl.h is called GetTypeInfo.

That's true. This `TypeInfo` comes from the Swift runtime. Maybe we should call it `GetSwiftRuntimeTypeInfo()`?

> Anyway, since this thing returns a pointer that can be null, shouldn't we be using an Expected?

Using something that forces us to check for null would be useful. From the looks of it (https://llvm.org/doxygen/classllvm_1_1Expected.html) `Expected` seems to want convertible `Error` objects, so it's best suited for system calls like file I/O. I suppose we could define a generic "nullptr" error here, but it also looks a little weird. Do we use Expected like this elsewhere?

**Comment by jimingham** [comment]
> > It's a little confusing that this function from SwiftLanguageRuntimeImpl.h is called GetTypeInfo.
> 
> That's true. This `TypeInfo` comes from the Swift runtime. Maybe we should call it `GetSwiftRuntimeTypeInfo()`?

Yes, that's a better name.

> 
> > Anyway, since this thing returns a pointer that can be null, shouldn't we be using an Expected?
> 
> Using something that forces us to check for null would be useful. From the looks of it (https://llvm.org/doxygen/classllvm_1_1Expected.html) `Expected` seems to want convertible `Error` objects, so it's best suited for system calls like file I/O. I suppose we could define a generic "nullptr" error here, but it also looks a little weird. Do we use Expected like this elsewhere?

Doing this is a fairly recent style change.  For instance we pass out "TypeSystem &" as Expected<TypeSystem &> in a bunch of places, e.g. when doing GetScratchTypeSystemForLanguage.  In that case, on error we do:

    return llvm::make_error<llvm::StringError>("unable to construct scratch type system",
                                               llvm::inconvertibleErrorCode());

And then we either copy that over to an lldb_private::Status and/or use LLDB_LOG_ERROR to log it.  The code to do that is a little ugly, however.  I'm not wedded to this part.

**Comment by jimingham** [comment]
Mostly it's confusing to have a named thing that in other places in the code returns a scalar, return a pointer that needs to be checked in this context...

**Comment by jimingham** [comment]
I'd be happy with just giving it its own name and documenting that it can return null.

**Comment by adrian-prantl** [comment]
Done.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
I didn't look at the implementation, but the method below returns an `llvm::Optional<const swift::reflection::TypeInfo *>`, which implies that you either get a valid pointer or None (and an invalid pointer is a real error). Any reason that wouldn't work for `GetSwiftRuntimeTypeInfo`?

**Comment by jimingham** [comment]
> I didn't look at the implementation, but the method below returns an `llvm::Optional<const swift::reflection::TypeInfo *>`, which implies that you either get a valid pointer or None (and an invalid pointer is a real error). Any reason that wouldn't work for `GetSwiftRuntimeTypeInfo`?

Adrian and I considered that offline.  As Adrian pointed out, Optional doesn't force you to check the result, it is more to provide a "Not Valid" value in the case where it's not obvious what the "Not Valid" value should be.  But in this case, nullptr is a perfectly good "Not Valid" value, so Optional doesn't add any real value here.  If we wanted to do more checking we'd go with Expected, but this doesn't get used widely enough to warrant that, IMO.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
