### PR TITLE
[lldb] Regenerate the static bindings with SWIG4

### PR DESCRIPTION
**Pull request by JDevlieghere**
From now on please prefer SWIG4 to generate the bindings. The version
doesn't really matter, but it keeps the diff for the generated files
smaller.

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
CC @adrian-prantl

**Comment by JDevlieghere** [comment]
rdar://68714662

**Comment by adrian-prantl** [comment]
Thanks!

**Pull request merged**
