### PR TITLE
Adapt DebugTypeODRUniquingTest to new SpecificationOf attribute

### PR DESCRIPTION
**Pull request by augusto2112**

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by vsapsai** [comment]
Does it work for you locally? Because I have similar but not equivalent setup and see
```
Assertion failed: ((std::end(Ops) - std::begin(Ops)) == (int)CT->getNumOperands() && "Mismatched number of operands"), function buildODRType, file DebugInfoMetadata.cpp
```

I suspect the entire branch [`dl/lldb-Use-__TEXT-segment-in-embedded-summary-test`](https://github.com/apple/llvm-project/commits/dl/lldb-Use-__TEXT-segment-in-embedded-summary-test/) has `ninja check-llvm-unit` failing because commit https://github.com/apple/llvm-project/pull/8243/commits/c56fd938d9986b90dbe28dcbe86efa7f525b3a5f has changed DebugInfoMetadata.h but hasn't updated the unit test. And consequently branches "next" and "stable/20230725" are failing because of this.

**Review by vsapsai — COMMENTED** [review]
A change like
```
@@ -816,7 +816,7 @@ DICompositeType *DICompositeType::buildODRType(
   Metadata *Ops[] = {File,          Scope,        Name,           BaseType,
                      Elements,      VTableHolder, TemplateParams, &Identifier,
                      Discriminator, DataLocation, Associated,     Allocated,
-                     Rank,          Annotations};
+                     Rank,          Annotations,  SpecificationOf};
   assert((std::end(Ops) - std::begin(Ops)) == (int)CT->getNumOperands() &&
          "Mismatched number of operands");
```

in llvm/lib/IR/DebugInfoMetadata.cpp allows the unit tests to finish without hitting an assertion.

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci test Windows

**Comment by augusto2112** [comment]
Thanks for finding the fix @vsapsai

**Comment by augusto2112** [comment]
@swift-ci test Windows

**Comment by augusto2112** [comment]
@swift-ci test windows

**Review by vsapsai — APPROVED** [review]

**Comment by vsapsai** [comment]
@swift-ci test windows

**Comment by augusto2112** [comment]
@swift-ci test windows

**Pull request merged**
