### PR TITLE
[CMake] Add missing dep when building with BUILD_SHARED_LIBS

### PR DESCRIPTION
**Pull request by davezarzycki**
Cherry pick: #335.

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test platform

**Comment by davezarzycki** [comment]
@swift-ci please smoke test platform

**Comment by davezarzycki** [comment]
@swift-ci please test platform

**Review by compnerd — CHANGES_REQUESTED** [review]
Nothing should be committed to `swift/master`.  Commit to `apple/stable/20190619` which will flow into master.

**Comment by davezarzycki** [comment]
@swift-ci please test macos platform

**Pull request merged**
