### PR TITLE
Eng/pr casdb rename

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
More big patches! Rename everything!

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
Rename commits LGTM; I would prefer we pull the other two commits into a separate PR since they get completely lost in this one.

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Comment by cachemeifyoucan** [comment]
@benlangmuir ok to merge this one?

**Review by benlangmuir — APPROVED** [review]
LGTM

**Pull request merged**
