### PR TITLE
🍒 [clang][ExtractAPI] Serialize platform specific unavailable attribute in symbol graphs (#89277)

### PR DESCRIPTION
**Pull request by daniel-grumberg**
rdar://125622225

### CODE REVIEW

**Comment by daniel-grumberg** [comment]
@swift-ci please test

**Review by QuietMisdreavus — APPROVED** [review]

**Comment by daniel-grumberg** [comment]
@swift-ci please test

**Comment by daniel-grumberg** [comment]
@swift-ci please test

**Comment by daniel-grumberg** [comment]
@swift-ci please test

**Pull request merged**
