### PR TITLE
[lldb] Update calls to SILModule::print to use SILOptions.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
See also: https://github.com/apple/swift/pull/29239

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
https://github.com/apple/swift/pull/29239

@swift-ci please smoke test

**Review by adrian-prantl — APPROVED** [review]
Thanks!

**Comment by varungandhi-apple** [comment]
apple/swift#29239

@swift-ci please test

**Comment by varungandhi-apple** [comment]
apple/swift#29239

@swift-ci please test

**Pull request merged**
