### PR TITLE
Cherry-pick  [LLDB] Expose several methods in SBWatchpoint and rebuild bindings

### PR DESCRIPTION
**Pull request by delcypher**
Cherry-pick of 55a363fea18b20a81e8ebb9518997a3bda602f32 from upstream. In a separate commit I've updated the static python bindings. Unfortunately a different version of swig was used previously so a lot of noise is created in the generated bindings due to the version difference.

### CODE REVIEW

**Comment by delcypher** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
We're moving to SWIG 4.1 everywhere so the noise is fine. LGTM.

**Review by JDevlieghere — APPROVED** [review]

**Comment by medismailben** [comment]
LGTM! Thanks!

**Review by medismailben — APPROVED** [review]

**Comment by delcypher** [comment]
Re-running CI. The CI broke because of a recent merge and was recently fixed by (https://github.com/apple/swift/pull/64021)

**Comment by delcypher** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test Linux

**Pull request merged**
