### PR TITLE
[SystemInitializerCommon] Remove divergence from upstream.

### PR DESCRIPTION
**Pull request by dcci**

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test

**Comment by dcci** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
Are you also making these changes on swift/master-next? Because I don't think there is an automerger in that direction.

**Comment by dcci** [comment]
I think the changes should both on `swift/master` and `swift/master-next`.

**Comment by dcci** [comment]
So, to answer your question, yes, I'm going to do the same work for `master-next`.

**Pull request merged**
