### PR TITLE
Revert "[lldb] Update calls to SILModule::print to use SILOptions."

### PR DESCRIPTION
**Pull request by eeckstein**
Reverts apple/llvm-project#609

See https://github.com/apple/swift/pull/29350

### CODE REVIEW

**Comment by eeckstein** [comment]
https://github.com/apple/swift/pull/29350

@swift-ci please smoke test

**Comment by eeckstein** [comment]
https://github.com/apple/swift/pull/29350

@swift-ci please smoke test

**Comment by eeckstein** [comment]
https://github.com/apple/swift/pull/29350

@swift-ci test

**Comment by varungandhi-apple** [comment]
We should close this as the corresponding Swift PR was closed.

**Pull request closed without merging**
