### PR TITLE
SwiftASTContext: allow deserializing @_implementationOnly dependencies to avoid crashing

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://65570721

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by fredriss** [comment]
@adrian-prantl can you think of any way to test this in LLDB?

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@fredriss It seems we do have an existing test covering this case: `implementation_only_imports/library_indirect/TestLibraryIndirect.py`.

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Comment by nkcsgexi** [comment]
@swift-ci please test

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@nkcsgexi please also create pull requests against master-rebranch and master-next. We don't have automergers in that direction.

**Comment by nkcsgexi** [comment]
@adrian-prantl yeah. I'll merge to these branches using https://github.com/apple/llvm-project/pull/1627 and https://github.com/apple/llvm-project/pull/1626

**Comment by adrian-prantl** [comment]
@nkcsgexi Awesome. Thank you!

**Pull request merged**
