### PR TITLE
Revert "[lldb] Fix that the embedded Python REPL crashes if it receives SIGINT"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/llvm-project#3533

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Note that this has been reverted upstream as well: https://github.com/llvm/llvm-project/commit/c3a3e65ecc082542080376e917d9c57d22901f6b

**Comment by compnerd** [comment]
CC: @JDevlieghere

**Comment by compnerd** [comment]
Cross-lining the failure log here: https://ci-external.swift.org/job/oss-swift-windows-x86_64-vs2019/7146/consoleText

**Comment by shahmishal** [comment]
Merged to unblock CI

**Pull request merged**
