### PR TITLE
[upstreaming] Remove unused and duplicate ClangASTContext constructor

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by Teemperor** [comment]
Seems like it's only unused in master-next but not in master....

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by Teemperor** [comment]
Let's just use the constructor that we use in master-next (they are anyway the same beside that the one we remove here seems very shady).

**Comment by Teemperor** [comment]
@swift-ci test

**Review by dcci — COMMENTED** [review]
Fine if it's unused.

**Comment by dcci** [comment]
@swift-ci test

**Pull request closed without merging**
