### PR TITLE
Static analyzer cherrypicks 52

### PR DESCRIPTION
**Pull request by malavikasamak**
# **DO NOT FILE A PULL REQUEST**

This repository does not accept pull requests. Please follow http://llvm.org/docs/Contributing.html#how-to-submit-a-patch for contribution to LLVM.

# **DO NOT FILE A PULL REQUEST**

### CODE REVIEW

**Comment by malavikasamak** [comment]
@swift-ci test

**Comment by malavikasamak** [comment]
@swift-ci test

**Review by jkorous-apple — APPROVED** [review]
LGTM
Nit: Maybe we could've squashed 733ee8a and cc11bae.

**Comment by malavikasamak** [comment]
@swift-ci test

**Comment by haoNoQ** [comment]
@malavikasamak says it's abandoned so I closed.

**Pull request closed without merging**
