### PR TITLE
Redirect repl input from a file

### PR DESCRIPTION
**Pull request by pcbeard**

### CODE REVIEW

**Comment by fredriss** [comment]
@Teemperor you looked some at the REPL code, do you mind taking a look?

**Comment by fredriss** [comment]
@swift-ci test

**Comment by jimingham** [comment]
It seems to me like "pull the text of the expression from a file" should be a feature of the expression command which the REPL would use when it got a < as the first character of the reply, not something confined to the REPL.  Reading an expression from a file is an oft requested feature, not just for the REPL.  

Were there roadblocks that made it difficult to go that way?

**Comment by pcbeard** [comment]
@jimingham If you think it's not ready to land this way, I can go back and generalize it.

**Comment by pcbeard** [comment]
Closing to simplify and generalize.

**Pull request closed without merging**
