### PR TITLE
[clang][DepScan] cherry-pick EBM optimizations from next to stable/20230725

### PR DESCRIPTION
**Pull request by Bigcheese**
This contains all of the recently upstreamed module dependency scanning optimizations from next.

### CODE REVIEW

**Review by ributzka — APPROVED** [review]

**Comment by ributzka** [comment]
@swift-ci please check

**Comment by ributzka** [comment]
@swift-ci test

**Comment by artemcm** [comment]
https://github.com/apple/swift/pull/70145
@swift-ci test

**Comment by Bigcheese** [comment]
https://github.com/apple/swift/pull/70145
@swift-ci test

**Comment by Bigcheese** [comment]
https://github.com/apple/swift/pull/70145
@swift-ci test

**Pull request merged**
