### PR TITLE
Reland "Cherry-pick 51d5d7bbae92493a5bfa7cc6b519de8a5bb32fdb from LLVM mainline"

### PR DESCRIPTION
**Pull request by asl**
Required for https://github.com/apple/swift/pull/71645

### CODE REVIEW

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/71645
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/71645
@swift-ci please test

**Comment by asl** [comment]
@rjmccall This is LLVM part of https://github.com/apple/swift/pull/71645

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/71645
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/71645
@swift-ci please test windows platform

**Comment by asl** [comment]
@rjmccall Will you please check / review this PR as well? This is a cherry-pick from LLVM mainline that is required for https://github.com/apple/swift/pull/71645

Thanks!

Tagging @rxwei

**Comment by asl** [comment]
@rjmccall Ping

Thanks!

**Comment by rjmccall** [comment]
Hi, Anton.  Sorry for the delay; I'm trying to figure out what our risk tolerance on merging patches like this is, since this is a long-established release branch.

**Comment by asl** [comment]
Sure. Few points here:
 - This is cherry-pick from LLVM mainline
 - The patch in question is in LLVM since August 2023
 - There is an auto-upgrade path for bitcode in "old" format
 - The corresponding patch is already in `next` branch just in case

**Comment by rjmccall** [comment]
Alright.  We're going to hold on this for a week or so until an internal branch is complete, but then we plan to merge it, and it should ultimately land in Swift 6.0.

**Comment by asl** [comment]
> Alright. We're going to hold on this for a week or so until an internal branch is complete, but then we plan to merge it, and it should ultimately land in Swift 6.0.

Great, thanks!

**Comment by asl** [comment]
Hi @rjmccall 

Just wondering about the status of your internal branch.

Thanks!

**Comment by rjmccall** [comment]
Okay, 6.0 has branched, so if you want to land this in this branch, you're welcome to.  Swift `main` will probably stay on this branch for a few months until eventually retrenching from LLVM `main`.

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/71645
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/71645
@swift-ci please test windows platform

**Comment by asl** [comment]
@rjmccall Thanks! I rebased both this PR and https://github.com/apple/swift/pull/71645

Will you be able to land both for me? They need to be merged at the same time, but I do not have commit access to apple/llvm, so I cannot do this by myself.

Thanks!

**Pull request merged**
