### PR TITLE
Register the symbol context's module first.

### PR DESCRIPTION
**Pull request by adrian-prantl**
This makes it more likely that compatible AST blobs are found first, since then the local AST blobs overwrite any ones with the same import path from another dylib.

### CODE REVIEW

**Review by augusto2112 — APPROVED** [review]

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
This is now ready to review, and adds some cute formatting to the types log.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
I would also be shocked if this test works on Linux on first try.

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/73153
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/73153
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/73153
@swift-ci test

**Comment by adrian-prantl** [comment]
test with https://github.com/apple/swift/pull/73153
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@shahmishal I've been requesting windows tests 12 times now, and it still hasn't started...

**Comment by shahmishal** [comment]
Re-requesting the new build kills the previous run: 
Screenshot 2024-04-22 at 4 15 32 PM

https://ci-external.swift.org/view/Pull%20Request/job/apple-llvm-project-PR-windows/

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test macos

**Comment by adrian-prantl** [comment]
@swift-ci test macos

**Pull request merged**
