### PR TITLE
[upstreaming] Make Swift a proper build option that can be turned off/on

### PR DESCRIPTION
**Pull request by Teemperor**
This PR are three commits doing the following things:
1. Adding a define `LLDB_ENABLE_SWIFT` that is set when Swift support is enabled (which it is by default in the swift branches).
2. Only compile Swift-specific LLDB sources when Swift support is enabled.
3. Put all Swift-specific code in non-Swift-specific LLDB sources behind the #ifdef from commit 1.

With this PR (and some small workaround in LLVM's CMake sanity checks) I can compile swift/master-next without having any Swift sources when I turn off the Swift build option.

### CODE REVIEW

**Comment by Teemperor** [comment]
I am not entirely sure about how `LLDB_ENABLE_SWIFT` should be implemented (see the first commit). It should only be in the config header, but it could happen that someone isn't including that header and then suddenly Swift support is gone from one file which could lead to strange bugs. Adding the define to the compiler invocation fixes this, but brings up the problem what people should do when they include LLDB's internal headers in their project (even though no one should be really doing that). We could define it both ways, but that's also not very nice.

**Comment by Teemperor** [comment]
The workaround needed for LLVM is that it will detect the unused source files in our directories. Usually this is done by putting non-generic files in their own subdirectories, but we currently don't do that. I'll move all these files around in their own commit as this would otherwise just blow up the diff for this PR.

We also need some filter for the test runs to disable Swift tests, but I Jonas probably has a better idea how to do that.

**Comment by fredriss** [comment]
I'm not a fan of moving files around. It will make any cherry-picking between branches extremely painful

**Comment by Teemperor** [comment]
Yeah, we could also patch LLVM's CMake function so that it doesn't abort when it sees that we don't follow LLVM's directory-based approach for doing plugins (e.g., have a whitelist where we just pass in the few Swift files that don't follow this structure).

**Comment by adrian-prantl** [comment]
Two high-level thoughts:

1. I think `#ifdef LLDB_ENABLE_SWIFT` should replace the BEGIN SWIFT / END SWIFT comments.

2. What about using `#ifndef LLDB_DISABLE_SWIFT` instead. This way we won't loose any code if we have a build system screwup that removes the flag?

**Comment by adrian-prantl** [comment]
> What about using #ifndef LLDB_DISABLE_SWIFT instead. This way we won't loose any code if we have a build system screwup that removes the flag?

However, if we want to upstream any of the code, this wouldn't fly.

**Comment by JDevlieghere** [comment]
- I would *not* hack around the plugin support in llvm/lldb. It works really well and it's conceptually what we want (especially if we plan to get that part upstream). Git is pretty good with renames and I haven't had any issues with the test directory so far. If cherry-picking really is the problem, we can pay the price once and cherry-picking this commit.
- Disabling the tests should be easy, for lit we can add  `REQUIRES: swift` and for dotest we already have the decorators.  I'm happy to take care of that. 
- We have precedent for both `LLDB_ENABLE_*` and `LLDB_DISABLE_*` macros, so I think either is fine at least on Github.

**Comment by Teemperor** [comment]
> * I would _not_ hack around the plugin support in llvm/lldb. It works really well and it's conceptually what we want (especially if we plan to get that part upstream). Git is pretty good with renames and I haven't had any issues with the test directory so far. If cherry-picking really is the problem, we can pay the price once and cherry-picking this commit.

I'm fine with doing both, even though we most likely have to move the files if this ever goes upstream. So I'll leave this for you guys to decide.

> * Disabling the tests should be easy, for lit we can add  `REQUIRES: swift` and for dotest we already have the decorators.  I'm happy to take care of that.

Cool! But this can be done after this PR because right now we can't even build anything.

> * We have precedent for both `LLDB_ENABLE_*` and `LLDB_DISABLE_*` macros, so I think either is fine at least on Github.

I prefer ENABLE_ because otherwise we have to use the double-negated `#ifndef LLDB_DISABLE_SWIFT` which is IMHO harder to read.

**Review by dcci — COMMENTED** [review]
Raph, this is really obsolete. Should we rebase it or close it?

**Comment by Teemperor** [comment]
This actually has already landed in master-next since then (in several smaller PRs), so I think we can close this one.

**Pull request closed without merging**
