### PR TITLE
[cherry-pick][stable/20230725] [lldb][Symbol] Make sure we decrement PC before checking location list

### PR DESCRIPTION
**Pull request by Michael137**
When stopping in optimized code, we can end up with the return address being the next instruction in a different block. If we are dealing with location lists, we want to decrement the PC value so it's within the calling block range that we're checking against the loclists.

This was addressed in https://reviews.llvm.org/D124597 (`6e56c4961a106b8fde69ffcf9f803fe0890722fa`), by introducing a `GetFrameCodeAddressForSymbolication`. This fixed `frame variable`, but `expr` calls into `Variable::LocationIsValidForFrame`, where this new API wasn't used yet.

So in the associated test-case, running `frame var this` works, but `expr this` doesn't. With `dwim-print` this makes the situation more surprising for the user because `p this`, `v this` and `v *this` work, but `p *this` doesn't because it falls back onto `expr` (due to the dereference).

This patch makes sure we lookup loclists using the correct PC by using this new `GetFrameCodeAddressForSymbolication` API.

### CODE REVIEW

**Review by adrian-prantl — APPROVED** [review]

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci test

**Comment by Michael137** [comment]
@swift-ci please test platform Windows

**Comment by Michael137** [comment]
@swift-ci please test Windows platform

**Pull request merged**
