### PR TITLE
[cas][debug info] Split debug info for enumerations and type definitions

### PR DESCRIPTION
**Pull request by felipepiovezan**
LLVM build, before this patch:

image

After this patch:

image

### CODE REVIEW

**Comment by felipepiovezan** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]
Nice!

**Review by rastogishubham — APPROVED** [review]
This looks great!

**Comment by felipepiovezan** [comment]
@swift-ci test

**Comment by felipepiovezan** [comment]
rebased

**Pull request merged**
