### PR TITLE
Reapply: Port swift specific compiler-rt code to Windows

### PR DESCRIPTION
**Pull request by vedantk**
Patch by Hugh Bellamy.

https://github.com/apple/swift-compiler-rt/pull/5

### CODE REVIEW

**Comment by hyp** [comment]
@vedantk is this something that can be committed to llvm.org's master instead?

**Comment by vedantk** [comment]
No, doing file I/O in a signal handler was never reliable and this code needs to be deleted ASAP. I aim to delete+replace it with a continuous mmap() mode by next week (https://reviews.llvm.org/D68351).

**Comment by hyp** [comment]
👍

**Comment by smeenai** [comment]
Can we merge this while the proper fix is being done upstream, to unbreak Windows builds?

(Just to be clear, the code that's being modified here is specific to Swift's fork as well.)

**Comment by vedantk** [comment]
Yes, sgtm

**Pull request merged**
