### PR TITLE
Remove obsolete calls to MemoryPressureDetected

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by xedin — COMMENTED** [review]
Could you un-XFAIL https://github.com/apple/llvm-project/pull/8038 to make sure that it doesn't hang anymore?

**Comment by adrian-prantl** [comment]
This patch turned out to have no effect on the strange test behavior.

**Pull request merged**
