### PR TITLE
[clangd] Adjust rename test to expect placeholder response

### PR DESCRIPTION
**Pull request by ahoppen**
This fixes another test failure I found while running CI on https://github.com/apple/llvm-project/pull/7961.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test llvm

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
