### PR TITLE
Cherry-picking swiftasync support to the new stable branch.

### PR DESCRIPTION
**Pull request by TNorthover**

### CODE REVIEW

**Comment by TNorthover** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by xymus** [comment]
@swift-ci Please test linux

**Comment by TNorthover** [comment]
@swift-ci please test linux

**Comment by aschwaighofer** [comment]
@swift-ci Please test linux

**Comment by aschwaighofer** [comment]
The linux failures look unrelated to this PR and also occurred on a different PR here: https://ci.swift.org/job/apple-llvm-project-pr-linux/1825

**Pull request merged**
