### PR TITLE
[CAS] Improve the cc1 flag round trip speed when CAS is used. NFCI

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Delay initialize the inputs from CAS to after ParseArgs to speed up the performance of round tripping arguments. This will save the CAS initialization/destruction costs when round tripping cc1 arguments, which is often used to modify/update cc1 arguments.

rdar://134363755

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please smoke test

**Comment by cachemeifyoucan** [comment]
@swift-ci please test llvm

**Review by jansvoboda11 — APPROVED** [review]

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Review by benlangmuir — APPROVED** [review]
Nice, thanks!

**Pull request merged**
