### PR TITLE
[analyzer] Add support for __attribute__((returns_nonnull)).

### PR DESCRIPTION
**Pull request by t-rasmud**
Differential Revision: https://reviews.llvm.org/D118657

(cherry picked from commit faabdfcf7f6704d5a7241d8b79b4dd5cc7a5527e)

### CODE REVIEW

**Comment by t-rasmud** [comment]
@swift-ci test

**Comment by haoNoQ** [comment]
@swift-ci test

**Comment by haoNoQ** [comment]
Ok this wasn't our fault, let's try again.

@swift-ci test

**Comment by haoNoQ** [comment]
Now it works, great, let's land!

**Pull request merged**
