### PR TITLE
Cherry picks to Stable/20221013 #3

### PR DESCRIPTION
**Pull request by ziqingluo-90**

### CODE REVIEW

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by jkorous-apple** [comment]
LGTM but I'll leave the approval to @haoNoQ

**Comment by haoNoQ** [comment]
Uh-oh I looked but forgot to approve. LGTM! There's a CFG patch here (CFG patches may affect regular compiler warnings so we're cautious about cherry-picking them) but this one looks harmless.

**Review by haoNoQ — APPROVED** [review]

**Comment by ziqingluo-90** [comment]
Thanks for reviewing!

**Pull request merged**
