### PR TITLE
[CodeGen] Add public function to emit C++ constructor/destructor function info

### PR DESCRIPTION
**Pull request by ahatanaka**

### CODE REVIEW

**Comment by ahatanaka** [comment]
@swift-ci please smoke test

**Comment by ahatanaka** [comment]
@swift-ci please smoke test

**Review by A-Alanbri — APPROVED** [review]

**Comment by ahatanaka** [comment]
@swift-ci please smoke test

**Comment by ahatanaka** [comment]
@swift-ci please test

**Comment by ahatanaka** [comment]
@swift-ci please test

**Pull request merged**
