### PR TITLE
Avoid ingesting the main module's reflection sections twice.

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://80655416

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by jimingham — COMMENTED** [review]
I worry a little about the difficulty of ensuring that all the modules get loaded if we have to audit all the code to make sure it doesn't happen twice to each module.  It would be less error prone to have SwiftLanguageRuntimeImpl keep a list of modules we've added to the reflection context, and do nothing if one's already added.  But that's a bigger change, and maybe you don't have time for that now?

**Comment by adrian-prantl** [comment]
> I worry a little about the difficulty of ensuring that all the modules get loaded if we have to audit all the code to make sure it doesn't happen twice to each module. It would be less error prone to have SwiftLanguageRuntimeImpl keep a list of modules we've added to the reflection context, and do nothing if one's already added. But that's a bigger change, and maybe you don't have time for that now?

Conceptually, at startup we load all reflection sections for all images in the target. From then on we load all images sent to us via ModulesDidLoad. As a leftover of a refactoring to make initialization of this class lazy we were importing the main binary twice. I removed that code in this patch.

**Comment by adrian-prantl** [comment]
If we can trust that ModulesDidLoad doesn't send us duplicates, we should not need to worry about this.

**Comment by jimingham** [comment]
The main executable is a little weird because it doesn't really load, it's there at the start.  But we pretend that it loads and generate a ModulesDidLoad, so that should be okay.  And for everything else ModulesDidLoad should only show them to you once.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
