### PR TITLE
Cherry-pick upstream "early_tests" lit feature

### PR DESCRIPTION
**Pull request by davezarzycki**
For upstream: https://reviews.llvm.org/D96594

### CODE REVIEW

**Comment by davezarzycki** [comment]
@shahmishal – Can we please cherry-pick this change now that it has landed upstream?

@swift-ci please test

**Comment by shahmishal** [comment]
@davezarzycki Can you commit this on `apple/stable/20210107` which will automatically get merged into `swift/main`?

**Comment by davezarzycki** [comment]
@shahmishal – I rebased this PR as you requested.

@swift-ci please test

**Comment by shahmishal** [comment]
Thanks!

**Pull request merged**
