### PR TITLE
[clang][deps] Cherry-pick recent changes

### PR DESCRIPTION
**Pull request by jansvoboda11**
This patch cherry-picks some upstream changes to the dependency scanner.

### CODE REVIEW

**Comment by jansvoboda11** [comment]
@swift-ci please test

**Review by benlangmuir — APPROVED** [review]
LGTM, thanks!  I reviewed the list of commits comparing to all dependency scanner changes on "next".  I didn't check the actual diff.

**Comment by jansvoboda11** [comment]
@swift-ci please test
https://github.com/apple/swift/pull/60882

**Comment by benlangmuir** [comment]
https://github.com/apple/swift/pull/60882
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/swift/pull/60882
@swift-ci please test

**Comment by artemcm** [comment]
https://github.com/apple/swift/pull/60882
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/swift/pull/60882
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/swift/pull/60882
@swift-ci please test

**Comment by benlangmuir** [comment]
https://github.com/apple/swift/pull/60882
@swift-ci please test macOS

**Comment by benlangmuir** [comment]
New failures look like a real issue:

```
Test Case '-[SwiftDriverTests.ExplicitModuleBuildTests testExplicitModuleBuildEndToEnd]' started.
error: generate-pcm command failed with exit code 1 (use -v to see invocation)
/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20220421/swift-driver/Sources/SwiftDriverExecution/SwiftDriverExecutor.swift:88: error: -[SwiftDriverTests.ExplicitModuleBuildTests testExplicitModuleBuildEndToEnd] : failed: caught error: "fatalError"
Test Case '-[SwiftDriverTests.ExplicitModuleBuildTests testExplicitModuleBuildEndToEnd]' failed (0.800 seconds).

Test Case '-[SwiftDriverTests.ExplicitModuleBuildTests testModuleAliasingPrebuiltWithScanDeps]' started.
error: generate-pcm command failed with exit code 1 (use -v to see invocation)
/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20220421/swift-driver/Sources/SwiftDriverExecution/SwiftDriverExecutor.swift:88: error: -[SwiftDriverTests.ExplicitModuleBuildTests testModuleAliasingPrebuiltWithScanDeps] : failed: caught error: "fatalError"
Test Case '-[SwiftDriverTests.ExplicitModuleBuildTests testModuleAliasingPrebuiltWithScanDeps]' failed (0.245 seconds).

Test Case '-[SwiftDriverTests.ExplicitModuleBuildTests testModuleAliasingWithExplicitBuild]' started.
error: generate-pcm command failed with exit code 1 (use -v to see invocation)
/Users/ec2-user/jenkins/workspace/apple-llvm-project-pr-macos/branch-stable/20220421/swift-driver/Sources/SwiftDriverExecution/SwiftDriverExecutor.swift:88: error: -[SwiftDriverTests.ExplicitModuleBuildTests testModuleAliasingWithExplicitBuild] : failed: caught error: "fatalError"
Test Case '-[SwiftDriverTests.ExplicitModuleBuildTests testModuleAliasingWithExplicitBuild]' failed (0.245 seconds).
```

**Comment by artemcm** [comment]
We thought we addressed these with https://github.com/apple/swift/pull/61025.
Must be a slightly different issue.

**Comment by artemcm** [comment]
https://github.com/apple/swift/pull/60882
@swift-ci please test

**Comment by artemcm** [comment]
https://github.com/apple/swift/pull/60882
@swift-ci please test

**Comment by jansvoboda11** [comment]
https://github.com/apple/swift/pull/60882
@swift-ci please test

**Pull request merged**
