### PR TITLE
🍒 [clang][ExtractAPI] Remove extra pointer indirection from declaration…

### PR DESCRIPTION
**Pull request by daniel-grumberg**
… fragments for Obj-C lightweight generics on id

Fixes https://github.com/llvm/llvm-project/issues/61479

Reviewed By: dang

Differential Revision: https://reviews.llvm.org/D146866

rdar://103355398

### CODE REVIEW

**Comment by daniel-grumberg** [comment]
@swift-ci please test

**Comment by drodriguez** [comment]
~~@swift-ci please test llvm~~

It doesn't seem to work in already merged PRs.

**Comment by drodriguez** [comment]
I think these changes introduce `clang/test/ExtractAPI/objc_id_protocol.m` which depends on more changes than the ones just introduced with the cherry-pick of D146866 to pass cleanly in the `release/5.10` branch. I am seeing consistent failures with that test.

I think the failure might be because #7824 was added to this branch before this cherry-pick, but in LLVM upstream it was added after, and the changes to `objc_id_protocol.m` where skipped in #7824 when backporting from upstream.

**Comment by daniel-grumberg** [comment]
I think that's right @drodriguez sorry about that, I believe I have fixed this as part of backporting changes as part of https://github.com/llvm/llvm-project/pull/73369. Apologies for things no lining up for a bit.

**Comment by drodriguez** [comment]
Yes. I think #7841 includes the test modifications to match upstream. Thanks!

**Pull request merged**
