### PR TITLE
[TextAPI] add missing platforms for translating triples to tapi targets

### PR DESCRIPTION
**Pull request by cyndyishida**
(cherry picked from commit 06fea93341ae7d0d0faa82c4c8704591963c2d8c)

### CODE REVIEW

**Comment by cyndyishida** [comment]
@swift-ci please test

**Review by artemcm — APPROVED** [review]

**Comment by cyndyishida** [comment]
@swift-ci please test

**Review by aschwaighofer — APPROVED** [review]
Thank you!

**Comment by cyndyishida** [comment]
@swift-ci please test Windows

**Pull request merged**
