### PR TITLE
[DebugInfo] Remove spare bits mask from LLVM IR and DWARF

### PR DESCRIPTION
**Pull request by augusto2112**
We are able to calculate the spare bits mask from other information. Remove this from the LLVM  IR representation and DWARF.

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
https://github.com/swiftlang/swift/pull/77038
@swift-ci test

**Comment by augusto2112** [comment]
https://github.com/swiftlang/swift/pull/77038
@swift-ci test

**Comment by augusto2112** [comment]
https://github.com/swiftlang/swift/pull/77038
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]

**Comment by augusto2112** [comment]
https://github.com/swiftlang/swift/pull/77038
@swift-ci test

**Review by felipepiovezan — APPROVED** [review]
I'm not very familiar with this customization, but glad to see such an invasive change be removed from downstream!

**Pull request merged**
