### PR TITLE
Fix for SR-5994 with added Swift test

### PR DESCRIPTION
**Pull request by poya**
Merge upstream fix with added Swift specific test

https://bugs.swift.org/browse/SR-5994
https://reviews.llvm.org/D70393

### CODE REVIEW

**Comment by poya** [comment]
@dcci As discussed in the upstream review, here is the PR with downstream tests

**Comment by dcci** [comment]
@swift-ci test

**Review by dcci — APPROVED** [review]
LGTM. Thanks.

**Comment by poya** [comment]
Does the test [a2836b8](https://github.com/apple/llvm-project/pull/378/commits/a2836b8f27c771ac3e0d1ac0ca1f540ba27865b9) also need to go to swift/master-next, or is it enough to put it in current swift/master? The docs mention swift/master being periodically "rebranched" from swift/master-next

**Comment by poya** [comment]
> Does the test [a2836b8](https://github.com/apple/llvm-project/pull/378/commits/a2836b8f27c771ac3e0d1ac0ca1f540ba27865b9) also need to go to swift/master-next, or is it enough to put it in current swift/master? The docs mention swift/master being periodically "rebranched" from swift/master-next

Ignore, I just saw that it had already been taken care of in PR #383

**Pull request merged**
