### PR TITLE
rdar://104607183 [libclang] Remove the _v4 and _v5 scanning APIs

### PR DESCRIPTION
**Pull request by jansvoboda11**

### CODE REVIEW

**Comment by jansvoboda11** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
Can we do this in a less invasive way? I'm actively working on caching support that depends on the v4+ API being available and this PR will prevent me from cherry-picking to this branch.  My understanding is this is a workaround for a build failure we have not yet root-caused.  Some ideas
* We could update the client to default to v3 but conditionally use the v4 API based on some kind of setting
* We could change the implementation of v4+ to use the old implementation under the hood, conditional on an environment variable

**Review by benlangmuir — APPROVED** [review]
Sorry, thought this was for stable/20221013, but it's actually stable/20220421.

I have no concerns with changing 0421 branch. LGTM.

**Comment by jansvoboda11** [comment]
@swift-ci please test

**Pull request merged**
