### PR TITLE
[Swift async] Add a baseline test for arguments and locals in logical frames

### PR DESCRIPTION
**Pull request by fredriss**

### CODE REVIEW

**Comment by fredriss** [comment]
@swift-ci please test

**Comment by fredriss** [comment]
We should extend this test with more cases once they work.

**Comment by jasonmolenda** [comment]
LGTM.  I forgot to add the swiftTest skipIf(oslist=['windows', 'linux']) decorators to the first test I merged this weekend; do we need to skip on linux?

**Comment by jasonmolenda** [comment]
(I also thought we needed to tweak the UnwindPlans in the PR I merged Friday night before we could get locals out of the AsyncContext but I didn't check)

**Comment by fredriss** [comment]
> (I also thought we needed to tweak the UnwindPlans in the PR I merged Friday night before we could get locals out of the AsyncContext but I didn't check)

The test in its current form just looks at the argument of the live frame. The others don't work. I want to have a test to evolve with the fixes.

**Comment by jasonmolenda** [comment]
Last week was a blur.  I looked at my test case and I already had those decorators in there.

**Review by kastiglione — APPROVED** [review]
nice

**Pull request merged**
