### PR TITLE
Fix a dangling-gsl warning and avoid transitively including string.

### PR DESCRIPTION
**Pull request by adrian-prantl**
(cherry picked from commit 6a9edce25778e6c131914ab2e6c3f8528785a8df)

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by JDevlieghere — APPROVED** [review]

**Comment by JDevlieghere** [comment]
Perfect 👍

**Comment by JDevlieghere** [comment]
btw, for the dated branch only macOS is required, so you can speed up testing (and save some CI resources) by just doing `test macos`.

**Comment by adrian-prantl** [comment]
@swift-ci test macos

**Comment by adrian-prantl** [comment]
@swift-ci test platform macos

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
