### PR TITLE
Cherry-pick 51d5d7bbae92493a5bfa7cc6b519de8a5bb32fdb from LLVM mainline

### PR DESCRIPTION
**Pull request by asl**
Required for https://github.com/apple/swift/pull/69843

### CODE REVIEW

**Comment by asl** [comment]
@swift-ci Please test

**Comment by asl** [comment]
@rxwei Apparently I cannot trigger CI here. Will you please do it for me?

Thanks!

**Comment by asl** [comment]
Please test with https://github.com/apple/llvm-project/pull/7797
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test

**Comment by asl** [comment]
Tagging @rxwei

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test Windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test Windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test Windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test Windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test Windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test Windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test Windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test macOS platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test windows platform

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test

**Comment by asl** [comment]
Please test with https://github.com/apple/swift/pull/69843
@swift-ci please test macos platform

**Comment by asl** [comment]
@rxwei Looks like I do not have write access here. Will you please merge this PR for me? This is LLVM counterpart of https://github.com/apple/swift/pull/69843

**Comment by jasonmolenda** [comment]
Hi @asl swift main isn't building because this isn't merged yet.  Can you merge or revert https://github.com/apple/swift/pull/69843 ?  thanks.

**Comment by asl** [comment]
@jasonmolenda I realized that I do not have write access to apple/llvm-project after I merged https://github.com/apple/swift/pull/69843

Will you please merge this PR for me?

Thanks!

**Comment by asl** [comment]
@jasonmolenda Thanks a lot!

**Pull request merged**
