### PR TITLE
Un-XFAIL two tests fixed by recent DWARFImporter changes in 212faae.

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test macos

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
The project moved the branch to `swift/main` and deleted `swift/master` branch, so GitHub automatically closed the PR. Please re-create the pull request with `swift/main` branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
