### PR TITLE
Remove SwiftASTContext from SwiftMetatype_SummaryProvider

### PR DESCRIPTION
**Pull request by adrian-prantl**
This is done primarily for performance reasons.
The change is not entirely NFC, the type produced by the reflection API is more verbose, but also more accurate.

### CODE REVIEW

**Review by kastiglione — APPROVED** [review]

**Review by augusto2112 — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
I moved the bulk of the implementation into SwiftLanguageRuntime. My previous version didn't work for Metatypes that are assigned to Any
.

**Comment by adrian-prantl** [comment]
And I got rid of SwiftASTContext in the SwiftArray data formatter!

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test linux

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test platform windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Pull request merged**
