### PR TITLE
Regain the ability to detect a failure to load the Swift stdlib.

### PR DESCRIPTION
**Pull request by adrian-prantl**
This fixes a regression caused by turning on DWARFImporter by default.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by dcci — COMMENTED** [review]
I'm mildly nervous -- this broke already another time or two in the past, and it's unclear whether it's going to stick without breaking again. Is there anything we can do to test this? Maybe a setting that helps exercising this failure mode?

I won't hold merging this review -- but it's really something that worries me long term.

**Comment by adrian-prantl** [comment]
I might be possible to trigger this by compiling a `-no-serialize-debugging-options` and then force-overriding an invalid SDK path. I will try that.

**Comment by dcci** [comment]
Thank you Adrian.

**Comment by adrian-prantl** [comment]
@swift-ci test platform linux

**Comment by adrian-prantl** [comment]
@swift-ci test Linux

**Comment by adrian-prantl** [comment]
@dcci: I experimented quite a while and it is not possible to write a test for this without also adding a new setting to force-overwrite the Swift resource directory (something you would *never* want to do outside of testing). I'm thinking about doing this on master only, not on 5.2-branch.

**Comment by dcci** [comment]
I think it's fair doing that only on `master`. `5.2` isn't going to change a lot, anyway.

**Review by dcci — APPROVED** [review]

**Pull request merged**
