### PR TITLE
[lldb] Hide __C module name when demangling type names

### PR DESCRIPTION
**Pull request by kastiglione**

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
I'm not opposed to this change, but I wonder if there is a potential that this will hide more bugs and thus make troubleshooting harder.

**Comment by kastiglione** [comment]
> but I wonder if there is a potential that this will hide more bugs and thus make troubleshooting harder.

definitely possible, does leaving off the `__C` module name, when it can't be resolved, works around more bugs than it might create, or fewer.

**Comment by kastiglione** [comment]
@swift-ci test macOS

**Comment by kastiglione** [comment]
@swift-ci test macOS

**Pull request closed without merging**
