### PR TITLE
Avoid a costly SwiftASTContext initialization in SwiftUnsafeTypes for…

### PR DESCRIPTION
**Pull request by adrian-prantl**
…matter

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by kastiglione — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Pull request merged**
