### PR TITLE
[WIP] [lldb] Set up basic support for generic expressions

### PR DESCRIPTION
**Pull request by augusto2112**
Possible solution for https://bugs.swift.org/browse/SR-12397

This PR sets up for evaluating expressions involving generic types.

## Approach

Instead of only having `$__lldb_expr`, have two functions `$__lldb_expr` and `$__lldb_wrapped_expr`. Pass in all the previously generic variables in the environemnt as generics once more as arguments to `$__lldb_wrapped_expr`.

Example for illustration:

```
func f<T>(_ foo: T) {
    let test = foo != nil // breakpoint here
    print(test)
}
let x: Int? = nil
f(x)
```

For the example above, this setup would would look like:

```
func $__lldb_expr(_ $__lldb_arg : UnsafeMutablePointer<Any>) {
  @LLDBDebuggerFunction
  func $__lldb_wrapped_expr<T>(_ $__lldb_arg : UnsafeMutablePointer<Any>, foo: T) {
    // user expression here, along with error handling, etc.
  }
  $__lldb_wrapped_expr($__lldb_arg, foo: foo)
}

```

This will correctly print `true` for the expression `foo != nil`.
Also, it might be relevant that the initial approach that LLDB took with generic arguments looks pretty similar to this, although the generic arguments used to be placed inside `WrapExpression` (https://github.com/apple/llvm-project/commit/bd28bd5a3b139d1f4cd3301bde71ef62185f61b8 - look at SwiftASTManipulator.cpp, lines 320-342).

## Problem

The biggest problem with this approach is that it won't use the substituted type when that's more convenient. For example:
```
(lldb) e foo
(T) $R0 = 0x010000000000000000
(lldb) e foo as! Int?
(Int?) $R0 = nil
```

While beforehand, this would be the output:
```
(lldb) e foo
(Int?) $R0 = nil
```

I'm hoping there's some clean solution to this.

There are also some parts missing with this PR, requirements are ignored, evaluation inside classes is ignored, setting up more than one variable per generic type is broken for now, and I think the code could be a lot cleaner. All of this should be straightforward to fix, but I wanted to gather some feedback on this approach before going forward.

@vedantk, @adrian-prantl what do you think?

### CODE REVIEW

**Comment by adrian-prantl** [comment]
Thanks @augusto2112 ! Creating an inner generic function looks like a good solution to the problem. Do we understand why the result type in your `e foo` example is not being subject to dynamic type resolution? Did you run the expression with `-d no-run-target`?

**Comment by augusto2112** [comment]
@adrian-prantl I tried `-d no-run-target` and `-d run-target` but that doesn't work.

I have a sense of why it may be happening. Evaluating foo would look more or less like this (ignoring the do catch):
```
func $__lldb_expr(_ $__lldb_arg : UnsafeMutablePointer<Any>) {
  @LLDBDebuggerFunction 
  func $__lldb_wrapped_expr<T>(_ $__lldb_arg : UnsafeMutablePointer<Any>, foo: T) {
      let $__lldb_result: T = foo
  }
  $__lldb_wrapped_expr($__lldb_arg, foo: foo)
}

```

Notice that `$__lldb_result` has type `T`, so it's printing "correctly" in a sense. 

To confirm, this is what the assignment looks like in the AST (notice the `type='@lvalue τ_0_0'`):
```
(assign_expr implicit type='()' location=<EXPR>:9:1 range=[<EXPR>:9:1 - line:9:1]
  (declref_expr implicit type='@lvalue τ_0_0' location=<EXPR>:9:1 range=[<EXPR>:9:1 - line:9:1] decl=__lldb_expr_3.(file).$__lldb_expr(_:).$__lldb_wrapped_expr(_:foo:bar:).$__lldb_result@<EXPR>:5:72 function_ref=unapplied)
  (declref_expr type='τ_0_0' location=<EXPR>:9:1 range=[<EXPR>:9:1 - line:9:1] decl=__lldb_expr_3.(file).$__lldb_expr(_:).$__lldb_wrapped_expr(_:foo:bar:).foo function_ref=unapplied)))

```

What I could try to do is return the value inside the expression, that way outside the inner function `$__lldb_result` would have the correct type. So:
```
func $__lldb_expr(_ $__lldb_arg : UnsafeMutablePointer<Any>) {
  @LLDBDebuggerFunction 
  func $__lldb_wrapped_expr<T>(_ $__lldb_arg : UnsafeMutablePointer<Any>, foo: T) -> T {
      return foo
  }
  let __lldb_result = $__lldb_wrapped_expr($__lldb_arg, foo: foo)
}

```
I believe this way `$__lldb_result` would have as an inferred type `Int?`. It's a little more code as well, since we'd have to find out the type of the user's expression and modify the AST so the inner function returns it . We'd also have to think about how to deal with statements in this case, but I guess the inner function could return `Void` and everything would work out.

**Comment by adrian-prantl** [comment]
> Notice that $__lldb_result has type T, so it's printing "correctly" in a sense.

The type `T` is the _static_ return type, but when running the expression with `-d run-target` (which is the default unless you are in the LLDB testsuite) we should do dynamic type resolution on it. Perhaps this is a chicken-and-egg problem, since we'd need to do dynamic type resolution in the _outer_ function for the result type, effectively the same issue again?

**Comment by augusto2112** [comment]
@adrian-prantl I see what you mean. Yes, the type in the outer function is being resolved correctly (which is how we know that `foo` has type `Int?` when passing it as an argument). Maybe it's because I created a brand new generic type when setting up the function's signature (in `SetupGenericParameters`). Maybe there's a way to do this without losing this information?

**Comment by adrian-prantl** [comment]
In order to resolve a generic type, we need debug info for each generic type parameter's type metadata (these the the artificial tau_0_0 variables showing up in dwarfdump). We can't pass this to the outermost function, because we can only pass the opaque blob as the only function argument. Can you remind me again why a class C<T> works? And could we wrap the expression in an inner class? (I haven't thought this through yet, just throwing things out there)

**Comment by augusto2112** [comment]
@adrian-prantl if you mean my comment about classes in the issue, it only works for instantiating values that were substituted in (like: `e var t: T? = nil`.

It's pretty similar to what I'm doing. Something like this (I can post the whole AST if you prefer):
```
extension A {
  func $__lldb_wrapped_expr<T where T == Optional<Int>>(_ $__lldb_arg: UnsafeMutablePointer<Any>) {
    // body here
  }
}
```
But it suffers from the same problem as the normal function: `foo != nil` still evaluates to something different than the compiler because T was already substituted.

So I don't think classes would help us much here, unless I'm missing something.

Do you think the approach of returning the value from the inner function would be bad?

**Comment by augusto2112** [comment]
@adrian-prantl I'm trying to implement the return from the inner function as a test, but I thought of something that leads me to believe that the inner function approach is flawed.

Consider the following example:
```
struct A {
    func someFunc() {}
}
func f<T>(_ foo: T) -> T {
    return foo // breakpoint here and run "e foo.someFunc()"
}

let x = A()
_ = f(x)
```
If we use my approach we'd have something like:
```
func $__lldb_expr(_ $__lldb_arg : UnsafeMutablePointer<Any>) {
  @LLDBDebuggerFunction
  func $__lldb_wrapped_expr<T>(_ $__lldb_arg : UnsafeMutablePointer<Any>, foo: T) {
    return foo.someFunc()
  }
  $__lldb_wrapped_expr($__lldb_arg, foo: foo)
}
```

But the inner function can't know that T has the `someFunc` function. If we DO constrain `T: A`, this would work, however in the original example of `foo != nil`, foo would be constrained as `foo: Int?`, and we're back to square one, where the result would be different from the compiled code :disappointed:

**Comment by adrian-prantl** [comment]
> struct A {
>     func someFunc() {}
> }
> func f<T>(_ foo: T) -> T {
>     return foo // breakpoint here and run "e foo.someFunc()"
> }
> 
> let x = A()
> _ = f(x)

That doesn't necessarily sound like a problem to me. The Swift compiler also doesn't accept this code:

```
/tmp/t.swift:5:16: error: value of type 'T' has no member 'someFunc'
    return foo.someFunc()
           ~~~ ^~~~~~~~
```

When running without dynamic type resolution the `expr` command should behave as if we wrote that code in that location. Now users sometimes expect a more dynamic behavior akin to what `frame var` offers, but that is not generally something the expression evaluator can deliver. @jimingham probably has a more nuanced opinion on this topic.

**Comment by jimingham** [comment]
I haven't followed all the details here, but in the lldb expression parser for swift we make a distinction between the "dynamic type" of a variable and the "bound type of a generic".  We can't currently figure out the dynamic type in the expression parser because it depends on looking at the current value of the variable, but you really can't know that till you are running the expression in general, which is too late to inject types into the parsing phase.

Here's an example where `a` has a dynamic type, and indeed you can't use the dynamic type in the expression parser:

```
(lldb) run
Process 80333 launched: '/tmp/whatever' (x86_64)
Process 80333 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100002b94 whatever`whatever.foo(a: Any) -> () at whatever.swift:2
   1   	func foo(a: Any) {
-> 2   	  print(a) // Break here
    	        ^
   3   	}
   4   	
   5   	foo(a:[10, 230, 345])
Target 0: (whatever) stopped.
(lldb) v a
([Int]) a = 3 values {
  [0] = 10
  [1] = 230
  [2] = 345
}
(lldb) expr a.count
error: <EXPR>:3:3: error: value of type 'Any' has no member 'count'
a.count
~ ^~~~~

<EXPR>:3:3: note: cast 'Any' to 'AnyObject' or use 'as!' to force downcast to a more specific type to access members
a.count
  ^
( as AnyObject)

```
`frame var` was able to get the dynamic type of the object, but the expression parser won't be able to.

OTOH, if you had:

```
(lldb) run
Process 80353 launched: '/tmp/whatever' (x86_64)
Process 80353 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100002b08 whatever`whatever.foo<T>(a: T) -> () at whatever.swift:2
   1   	func foo<T>(a: T) {
-> 2   	  print(a) // Break here
    	        ^
   3   	}
   4   	
   5   	foo(a:[10, 230, 345])
Target 0: (whatever) stopped.
(lldb) expr a.count
(Int) $R0 = 3

```

Where the variable is a bound generic, we do fill in the bound generic types before parsing the expression so that when swift comes back to ask us what `a` means in this context, we tell them `[Int]`.

**Comment by jimingham** [comment]
I think people would be upset if you lost this ability.

**Comment by augusto2112** [comment]
Hi @jimingham, @adrian-prantl I definitely agree that keeping LLDB practical is probably more important than making this edge-case work, but it'd be ideal if we got these edge cases to work as well.

I thought about a way to overcome the limitation the previous limitation I stated. The idea would be to declare a dummy protocol containing the **entire** the public api of the generic type. This was just something I thought about, so I'm not 100% sure it would work. Let me show an example.

For the following code:

```
struct A {
    func someFunc() {}
}
func f<T>(_ foo: T) -> T {
    return foo // breakpoint here and run "e foo.someFunc()"
}

let x = A()
_ = f(x)
```

We'd generate something like:

```
protocol $_lldb_T_A {
    func someFunc()
}

extension A: $_lldb_T_A {}

func $__lldb_expr(_ $__lldb_arg : UnsafeMutablePointer<Any>) {
  @LLDBDebuggerFunction
  func $__lldb_wrapped_expr<T: $_lldb_T_A>(_ $__lldb_arg : UnsafeMutablePointer<Any>, foo: T) {
    return foo.someFunc()
  }
  $__lldb_wrapped_expr($__lldb_arg, foo: foo)
}
```

I believe this would allow us to evaluate expressions of generics as we currently do, and take care of the edge cases regarding generics and optionals.

At this point though, even if this would work, I'm unsure if it's worth the cost. There would be a cost in maintanability, runtime (especially if the there are many generic types involved, or if their public API is extensive), all to support an edge-case that seems fairly niche.

The other path we could pursue is identifying the situations where the compiler does magic, especially involving optionals. For this specific bug that be something like "if we're comparing optional values, but one of the types was generic, then wrap the value in an extra optional before comparison". The reason I didn't initially want to go about it this way is because:
- We're duplicating work between the compiler and LLDB.
- Not scalable. We'd have to implement all the "special" rules.
- Not future-proof. New rules would need to be added in later.

Still, if there are very _few_ of these special rules, it might be a saner way to do this.

At this point, I'd really like to hear from you guys, who are more familiar with LLDB, if this is worth pursuing, and what way would be best. I'd be happy to continue working on the issue, but if you guys think it's not worth it (or at least not right now) I'd be ok in picking some other issue on LLDB to work on as well.

**Comment by adrian-prantl** [comment]
> We can't currently figure out the dynamic type in the expression parser because it depends on looking at the current value of the variable, but you really can't know that till you are running the expression in general, which is too late to inject types into the parsing phase.

@jimingham I would like to learn more about this. My understanding is that LLDB provides a callback to the Swift compiler that fill in types that LLDB then grabs from debug info. While we cannot to dynamic type resolution on _objects_ during this phase, because we'd need a `ValueObject` (= a `self` pointer) for that, we should be able to resolve generic type parameters, if we have access to the generic type metadata (i.e., the `tau_0_0` artificial generic type metadata variables from the debug info). Is my statement correct, or is there something preventing us from doing that?

**Comment by jimingham** [comment]
> On Nov 13, 2020, at 10:58 AM, adrian-prantl <notifications@github.com> wrote:
> 
> 
> We can't currently figure out the dynamic type in the expression parser because it depends on looking at the current value of the variable, but you really can't know that till you are running the expression in general, which is too late to inject types into the parsing phase.
> 
> @jimingham <https://github.com/jimingham> I would like to learn more about this. My understanding is that LLDB provides a callback to the Swift compiler that fill in types that LLDB then grabs from debug info. While we cannot to dynamic type resolution on objects during this phase, because we'd need a ValueObject (= a self pointer) for that, we should be able to resolve generic type parameters, if we have access to the generic type metadata (i.e., the tau_0_0 artificial generic type metadata variables from the debug info). Is my statement correct, or is there something preventing us from doing that?
> 
> 

How would we handle:

expr local_var.giveMeSomethingWithADynamicType().methodThatOnlyExistsInOneParticularDynamicType()

Until you evaluate giveMeSomethingWithADynamicType() you have ho idea whether the result supports methodThatOnlyExistsInOneParticularDynamicType...

Jim

**Comment by adrian-prantl** [comment]
> expr local_var.giveMeSomethingWithADynamicType().methodThatOnlyExistsInOneParticularDynamicType()

That makes sense, it's not possible to do that. But @augusto2112 's example was about resolving the generic type of a local variable. I'm wondering if there is some middle ground here. Augusto's example (doing generic parameter binding for expression _inputs_ seems doable to me. Would you agree or am I still seeing this through rose-colored glasses?

**Comment by jimingham** [comment]
The lldb expression parser's stated goal is to run code "as if it had been written in the current frame."  We violate that rule by broadening some searches (for instance we'll let you see classes that visibility rules might have hidden from you.)  But for the sake of predictability we try to keep these shenanigans to a minimum.

This patch would allow you to run code that clearly wouldn't be possible in the current context.  If it were minimal in complexity and didn't regress other things that actually work (like reporting the real type of results), that might not rule out the change.  But it seems like this adds a fair bit of complexity and has some negative side effects.  Plus it will make some things that really shouldn't work work (calling methods of the actual bound type) but not others that seem equally reasonable (calling methods of dynamic types).  This would make it even harder for people to figure out what to expect.

If we really want to address this sort of issue, I think the best way to go about it is to add an "interpreter" mode to lldb's expression parser.  Instead of trying to wrap and compile the user expression, it would parse the expression, then begin evaluating the expression's subexpressions depth-first.  After each evaluation, we could provide the dynamic type of the result of each subexpression, and use that to evaluate the next highest level of subexpression.  This method is likely not to be as faithful a representation of the source language as the current expression parser method, but would come in handy when you don't need rigor just "show me what's here right now".

This "evaluator" is pretty much how the gdb expression parser works.  It's interesting to note that a variant of lldb's expression parser method (but for top-level code only) was added to gdb recently alongside it's traditional evaluator.  I think both methods are useful in different circumstances.

So IMHO, instead of adding complexity to the already quite complex expression evaluator, and more importantly adding complexity to what does and doesn't work in the expression parser, we should solve these sort of issues by introducing an evaluator mode to lldb's expression parser.

**Comment by augusto2112** [comment]
Closing this PR since this probably isn't the way to go to solve this issue.

**Pull request closed without merging**
