### PR TITLE
[SelectionDAG] Fix lowering of vector geps

### PR DESCRIPTION
**Pull request by jroelofs**
This fixes an assertion failure that was being triggered in
SelectionDAG::getZeroExtendInReg(), where it was trying to extend the <2xi32>
to i64 (which should have been <2xi64>).

Fixes: rdar://66016901

Differential Revision: https://reviews.llvm.org/D84884

This is a cherry-pick of: afae6d97fa55984003321245ec6ceb5af9cc5856

### CODE REVIEW

**Comment by jroelofs** [comment]
@nathawes for review

**Review by nathawes — APPROVED** [review]
Thanks!

**Comment by nathawes** [comment]
@swift-ci please test

**Comment by nathawes** [comment]
This Linux failure seems unrelated and is affecting other PRs too. Going to go ahead and merge this.

**Pull request merged**
