### PR TITLE
[cherry-pick stable/20230725] [Modules] Make clang modules for the C standard library headers

### PR DESCRIPTION
**Pull request by ian-twilightcoder**
Differential Revision: https://reviews.llvm.org/D159064
https://github.com/llvm/llvm-project/pull/68163
https://github.com/llvm/llvm-project/pull/68241
rdar://105819340

https://github.com/apple/llvm-project/pull/7576
rdar://116522302

### CODE REVIEW

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test Linux

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test Windows

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test Windows

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test Windows

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test
https://github.com/apple/swift/pull/69707%0A@swift-ci%20test

**Comment by ian-twilightcoder** [comment]
@swift-ci test
https://github.com/apple/swift/pull/69707%0A@swift-ci%20test

**Comment by ian-twilightcoder** [comment]
@swift-ci test
https://github.com/apple/swift/pull/69707%0A@swift-ci%20test

**Comment by ian-twilightcoder** [comment]
@swift-ci test
https://github.com/apple/swift/pull/69707

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/llvm-project/pull/7848
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
https://github.com/apple/swift/pull/69707
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by ian-twilightcoder** [comment]
@swift-ci test

**Comment by hyp** [comment]
@ian-twilightcoder  this broke windows toolchain build for Swift, can you please take a look:

https://github.com/thebrowsercompany/swift-build/actions/runs/7457288070/job/20290377000

```
C:/a/swift-build/swift-build/SourceCache/swift-corelibs-libdispatch/dispatch/dispatch.h:35:10: note: while building module 'ucrt' imported from C:/a/swift-build/swift-build/SourceCache/swift-corelibs-libdispatch/dispatch/dispatch.h:35:
#include <sys/types.h>
         ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt/fenv.h:13:10: note: while building module '_Builtin_float' imported from C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt/fenv.h:13:
#include <float.h>
         ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "float.h"
         ^
C:\a\swift-build\swift-build/BuildRoot/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift\clang\include/float.h:32:17: error: cyclic dependency in module 'ucrt': ucrt -> _Builtin_float -> ucrt
#  include_next <float.h>
                ^
```

**Comment by ian-twilightcoder** [comment]
> @ian-twilightcoder this broke windows toolchain build for Swift, can you please take a look:
> 
> https://github.com/thebrowsercompany/swift-build/actions/runs/7457288070/job/20290377000
> 
> ```
> C:/a/swift-build/swift-build/SourceCache/swift-corelibs-libdispatch/dispatch/dispatch.h:35:10: note: while building module 'ucrt' imported from C:/a/swift-build/swift-build/SourceCache/swift-corelibs-libdispatch/dispatch/dispatch.h:35:
> #include <sys/types.h>
>          ^
> C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt/fenv.h:13:10: note: while building module '_Builtin_float' imported from C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt/fenv.h:13:
> #include <float.h>
>          ^
> <module-includes>:1:10: note: in file included from <module-includes>:1:
> #include "float.h"
>          ^
> C:\a\swift-build\swift-build/BuildRoot/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/lib/swift\clang\include/float.h:32:17: error: cyclic dependency in module 'ucrt': ucrt -> _Builtin_float -> ucrt
> #  include_next <float.h>
>                 ^
> ```

Do you know if that run includes https://github.com/apple/swift/pull/69707 ? That one is supposed to fix that cycle. Where is that toolchain's command line set up? It's passing a vfs that requires `-strict-implicit-module-context -Xcc -Xclang -Xcc -fbuiltin-headers-in-system-modules` but it's not passing those flags. I thought I found all of those in that PR, but maybe I missed one?

**Comment by ian-twilightcoder** [comment]
@hyp ⬆️

**Pull request merged**
