### PR TITLE
Cherry-pick https://github.com/apple/llvm-project/pull/8482 to swift/release/6.0

### PR DESCRIPTION
**Pull request by rastogishubham**

### CODE REVIEW

**Comment by rastogishubham** [comment]
@swift-ci please test

**Comment by rastogishubham** [comment]
@swift-ci please test

**Comment by rastogishubham** [comment]
@swift-ci please test windows

**Comment by rastogishubham** [comment]
@swift-ci please test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Review by adrian-prantl — APPROVED** [review]

**Pull request merged**
