### PR TITLE
Cherry pick ISel fixes for constant pointers

### PR DESCRIPTION
**Pull request by felipepiovezan**
Cherry pick the four fixes submitted upstream for rdar://12976823

### CODE REVIEW

**Comment by felipepiovezan** [comment]
@swift-ci please test

**Review by adrian-prantl — APPROVED** [review]

**Comment by felipepiovezan** [comment]
Rebased.

@swift-ci please test

**Comment by felipepiovezan** [comment]
@swift-ci please test

**Comment by felipepiovezan** [comment]
rebased.

@swift-ci please test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
