### PR TITLE
Revert "Salvage debug info for function arguments in coro-split funclets."

### PR DESCRIPTION
**Pull request by DougGregor**
Reverts apple/llvm-project#2223. @ktoso has some examples where this crashes.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by ktoso** [comment]
Thanks a lot! I can confirm this revert fixes my issue in https://github.com/apple/swift/pull/34722

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by adrian-prantl** [comment]
Here is a PR that fixes the crash: https://github.com/apple/llvm-project/pull/2284

**Comment by DougGregor** [comment]
Closing in favor of https://github.com/apple/llvm-project/pull/2284#pullrequestreview-563144615

**Pull request closed without merging**
