### PR TITLE
🍒 Cherrypicks to allow Swift to enable LLDB tests in Windows builds

### PR DESCRIPTION
**Pull request by weliveindetail**
This is the companion PR with all the llvm-project changes for https://github.com/swiftlang/swift/pull/76894

### CODE REVIEW

**Comment by hjyamauchi** [comment]
@swift-ci please test

**Comment by weliveindetail** [comment]
Thanks for running the test and good to know it doesn't bother macOS and Linux.

Windows platform failed with:
```
CMake Error at C:/Users/swift-ci/jenkins/workspace/apple-llvm-project-pull-request-windows/llvm-project/lldb/test/API/CMakeLists.txt:74 (message):
  LLDB tests require 'make' tool.  Please pass via `LLDB_TEST_MAKE` (or
  otherwise disable tests with `LLDB_INCLUDE_TESTS=OFF`)
```
We have to test in combination with https://github.com/swiftlang/swift/pull/76894, because `build.ps1` needs a patch: https://github.com/swiftlang/swift/pull/76894/commits/e25d4a81cad1adc89d4e1193b2602b56041ce3be

**Comment by hjyamauchi** [comment]
Please test with following PRs:
https://github.com/swiftlang/swift/pull/76894

@swift-ci please test

**Comment by hjyamauchi** [comment]
Please test with following PRs:
https://github.com/swiftlang/swift/pull/76894

@swift-ci please test Windows Platform

**Comment by weliveindetail** [comment]
Same test summary as https://github.com/swiftlang/swift/pull/76894. No flakes. Investigating the failures.

**Comment by hjyamauchi** [comment]
Please test with following PRs:
https://github.com/swiftlang/swift/pull/76894

@swift-ci please test Windows Platform

**Comment by hjyamauchi** [comment]
Please test with following PRs:
https://github.com/swiftlang/swift/pull/76894

@swift-ci please test Windows Platform

**Comment by weliveindetail** [comment]
The Swift rebranch landed and main now builds against the new stable branch (since https://github.com/compnerd/swift-build/pull/840), so we need a new companion PR: https://github.com/swiftlang/llvm-project/pull/9513

**Pull request closed without merging**
