### PR TITLE
[stable/20211026] Cherry-pick missing commits

### PR DESCRIPTION
**Pull request by bnbarham**
There are a whole bunch of commits on stable/20210726 *and* next that are not on stable/20211026 due to only being cherry-picked to next *after* the branch point.

Furthermore all current work is going into stable/20210726 and next (or done upstream and only cherry-picked to stable/20210726) so there's that too.

I did my best here to check that the commits should *actually* go into stable/20211026 but given the number it's quite possible I got some wrong. Below is a list of all commits I went though, with some reasoning added for skipped commits. These were generated from a script that first does a `git cherry` and then attempted to find the same commit in the branch-to-cherry-to, logging if it couldn't be found.

425c6b5bacd784c0dd909a9b71755ae3a18f98f7 X86 swifttailcc remove invalid check
  Skipped - merge fix for 20210726
22a54d0a5448e5d4f908b42fca45506513684d0e [lldb] Only warn about 'auto' types in the log instead of stderr
  Skipped - says not to add to newer branches
07058aa5c72a90792d165c7a06c99223de0bf43a Revert "[SimplifyLibCalls][NFC] Clean up LibCallSimplifier from 'memset + malloc into calloc' transformation"
  Skipped - not needed
a9c4190526d06a6d334ea9841efddc6febf56f08 Revert "[DSE] Transform memset + malloc --> calloc (PR25892)"
  Skipped - not needed
48a091a5de897921036005eb5ff099e2195ad1a2 A random collection of little fixes needed to get this branch building.
  Skipped - compilation fixes not needed in 20211026
a334b4c3642cd1a593ae7c838eb557ad5f4a415f Relax test to account for differences in swift-llvm
  Skipped - committed separately to next (before 20211026 branch)
0b6bbe90ab71e1a649ddb695a01df0ddd231336f Revert "[llvm][sve] Lowering for VLS truncating stores"
  Skipped - not needed
d825321ea82213af1f1e278879305969697e9521 Update copy of code in UpdateValue from DoUpdateChildrenAddressType
  Skipped - copy should not have existed and was removed
ec6318a56349fac542b3773ed883a9b57f2c9ab2 [lldb] Include TargetConditionals.h
  Skipped - no longer necessary
e34145fed6a1d9abec6a83ec3383a3065f92e508 [lldb] Re-enable TestBitfields.py
5d9789d0c1d43927f177230caf051ce61b788c62 [lldb] Re-enable TestDataFormatterObjCNSError.py
7fb9da50f8be0d3cc5a253cd130f400216317694 Revert "Reland "[Clang] Propagate guaranteed alignment for malloc and others""
  Skipped - not needed
c74e6272f65c7570210cac053f0af82602ca5d3b Update test to allow for Swift.String instead of just String
703a0ea940f2751d46ed3ba401c44108265356c7 Revert "[Coverage] Store compilation dir separately in coverage mapping"
  Skipped - only intended for 20210726
ff06f2f9307a79c22bf7cab541e837c2254831e3 Temporarily mark swiftasync unavailable for x86_64 Windows.
  Skipped - avoid conflicts (reverted and added back)
d7f78e948599d5b9b6d78bf2621b530d2d53896a Run coro::salavageDebugInfo on dbg.declares in entry function
de8c4e4e1f7561299125a10cbe24d9cf7d19789b [lldb] Support diagnostic options in Swift REPL
aeeda41ca4e25e1daaa5ffbf95cc0f83dfb555b4 Default to swift-async-fp=always
  Skipped - seems to have been a partial commit of a773db7d76222ccf4365979e01dd582fd2b5b3df
e46dc39cc14fa7c7efe30c6cf49c29e3e19b5db4 Experimentally make clang default to SwiftAsyncFramePointerKind::Always too
  Skipped - f670c5aeeef09cd7b88e72cf8c1f2505d044a8ea already defaults to Always
d0f00c4d76d1d3d6595cb8f0ce4aca1afae87781 Target: explicitly handle `.swift1_autolink_entries`
1242ce6c8d6df81131609b33863b7f6ac113a9d1 [lldb] Name UnsafePointer's single child 'pointee'
e4386faef58d7e505ede6eb3ef2893b369df5a1e Disable assertion
2319e3eaf75099ef4bf2eb5294431fd6f6bcfa5d [lldb] Temporarily disable the reproducer tests
f3e93f3a22343faa54df4a0cc8685cbc029ff908 [lldb] XFAIL SwiftREPL/Resilient{Dict,Array}.test
  Skipped - no longer XFAILed
f1f077ccf29c22d9c61d02483d1a0a7c6df511e8 [lldb] Remove unused folder source/Plugins/Process/Darwin
15fdd40500c3c5b6ebda98f47a8fe17df969bb2e [lldb] Allow for getting the current/inherited environment separately
  Skipped - partial cherry-pick from next, have the full in stable/20211026 already
742fc6240d203545d35cba89759db2afa4d81b5d [lldb] Skip failing tests on Linux
b7b84d9341a41d1712cfb520043af09ed6af9e21 [lldb] Toggle the reproducer default in the driver
d01355677e354791d56b3b7ca0d6ee9db50affb0 Update CMakeLists.txt
3598797f52d8996e6b5849491fe08ffc42b08f47 [lldb] Add missing serialization status strings
  Skipped - already updated
cc13fd54a3d65e0c9de76029a5c68db8ec79bb9c update RevisionIncompatible string
  Skipped - already updated
8a22207a3ded8dab5d69135c80ce9d6aba303d2a refine RevisionIncompatible string
  Skipped - already updated
09bdb99d57c65c397297823d9fd9c17ac8912d9d Support: unlock Windows API support, switch to Windows 10 RS1+ APIs
5c40704c6a4ea315e21bdec2db5270df588cdc37 Disable lifetime.start sinking for ABI::Async and ABI::Retcon
9edc5eeba269b9b4346620da78077c3c745549cc Don't use lifetime.start based alloca localization for ABI.Async/ABI.Retcon
813a25a4a170f27abb040ec20a2533af64c86732 Reland "[lldb] Use CompileUnit::ResolveSymbolContext in SymbolFileDWARF"
cbaccb0a0e961865767dd7caf57f3f748ffa18a1 [lldb] Pass extra clang args by const-ref (NFC)
109798f15c30b90bbeb8f630459cc68e4014d3b2 Unxfail test.
  Picked e2e6bee59401b233481ebaa0d2f0ecc57b754d54 instead as the file was renamed
0113c2eaa4030d91c7f359301db84e1e4e246cd6 Merge pull request #3316 from apple/fixfornewsig
  Skipped - already updated
f6faf0c825cc47100247c602ff48c81db3725ab5 [lldb] Add new Swift log channel
97740ea0e9800e78cf9192ef1b2a86582498834d [lldb] Log SwiftASTContext configuration to Swift health
8b4225df39f5b8f626ec1338d2653af69913e72e [lldb] Remove superfluous SDKTypeMinVersion type (NFC)
4fee9a73793ea46a8c30559cf3ab83d83a0907e9 wrap in LLDB_ENABLE_SWIFT
48fe48ab9cc579e2ef64a48ff780e62017c6c3fb reuse LOG_PRINTF_IMPL
43e3983c680be8978aa551518710077245961d89 missed a LLDB_ENABLE_SWIFT
082d1eba994e21398e5cbd12cb4054bd8e23101f [lldb] Modify call to ASTContext::get as per new signature
  Skipped - already updated
07bbf6c3814005a6a8f521ef4fd816763e7d773d Revert "[modules] Fix miscompilation when using two RecordDecl definitions with the same name."
73ec6709051863d1126e9afa9cd9a9eadffb3bcf Revert "Work around outdated system header files on Amazon Linux"
  Skipped - picked 89f633a4dddb0a4250e11b3a0428087e371db34f and then bbd22f47d85fb115259006904dcc68ad703afbd3 instead
2db66e8c0b03ec9721003c0d02fb1d9bd42ab70f [lldb] Auto-enable swift health logging to memory buffer
dcfe81e7625f01c9d30d72e561fc22774c1f3596 [lldb] Add basic healthcheck command
0379089472f74d21547d68d425fcde23d80d556a wrap in LLDB_ENABLE_SWIFT
30515a1447a6a8baca69b0fb64c2333f17635a3c Merge pull request #2646 from apple/lldb-Add-work-around-handling-of-recursive_mutex-lock-failures
9bc7ba655257b7af1a8053ab4a8834d7e0b23d8f Revert "[profile] Add binary id into profiles"
  Skipped - only for 20210726
87f3da5866fac00fc5f93b4806abe9451db6341d Revert "Work around outdated system header files on Amazon Linux"
  Skipped - see previous revert
41c3c52567612869cb9b56f574b9f1d552960d56 [lldb] Add call to registerClangImporterRequestFunctions in SwiftASTContext
cc706bf27426988cd03e4ff3f60d237e93b07aeb [lldb] Rename 'healthcheck' to 'swift-healthcheck'
1ae255224d50ab481e1cf7c222bddfcebd33bbb4 Revert "Work around outdated system header files on Amazon Linux"
  Skipped - see previous revert
9394255f5c242b5268290a05da73fa3ad125c7b0 [lldb] Duplicate SwiftASTContext::CreateInstance errors to swift health log
79e98609bef7cd9393d375acc1af685ee9cf31e1 Revert "Work around outdated system header files on Amazon Linux"
  Skipped - see previous revert
2d5f6915e74f3024f79a1745030a6cf1a068fa55 Revert "Work around outdated system header files on Amazon Linux"
  Skipped - see previous revert
110fe51b2ab4966e3fa645a6ec25287612f2c02b disable test on linux
13ac86a97b60d099e38b85b0d1c066a92f895228 [lldb] Remove swiftc -enable-experimental-concurrency from tests
a0e1c6015af72bffb31866c20e58cb39379a508e [lldb/test] Remove XFAIL on TestSwiftStepping.py
de1497203822626c8490165aa9be79f7d405b220 [lldb] Skip tests for target var without a proc on both arm64 & arm64e
0aca6351460b3811e9d5c6da21fab1047ad85662 [lldb] Move reference related functions to TypeSystemSwift
92251f5827eab5fd085afac778a28f903b975963 [lldb] Implement GetPointeeType
d4afbfcb67455e94e7c17cb9d2f7c387a05b9653 [lldb] Disable swift-create-module-contexts-in-parallel for a few tests
  Skipped - since reverted
860affefd94e3ef596f91e44d5f1d8209f82ff1a [lldb] Add message to functions not worth implementing in tss-typeref
c81320b6d010d877320e6d135a03e6e7eb52f2be add comment and radar link
  Skipped - since reverted
3c6d4b1e1dd2764f6da8f2c470daaf47c7018277 [lldb] Move DumpSummary implementation to TypeSystemSwift
c8c963cadebc9f65f7c786bfc20f93c5e05edfb7 [lldb] Fixup code addresses in the Objective-C language runtime
dc39a8ae0e9d8370356a1a49b9e99f34d248fc1e Fix Stable lldb Release Builds
e57ab301673b8147c10db9ead69b8297d3434baf [lldb] The os and version are not separate components in the triple
668722ce87fc43d4b4a2a6573112131a3297d8e1 build: optionalize some clang resource headers
5ae95eaa8162fcb479328cc1d9ddac6f2cd9c867 [debugserver] Fix typo in DNBArchImplARM64
  Skipped - already fixed by e4235bdf26a2dd3b678daad4581d8e8edbc1aa7b
83a8378c4e3254ab826bd1e92d95c2bfd90ad4f9 [lldb] Use reflection metadata to find the value type of an existential
4301f820fc909431f271c3e5f2892df19f6c8713 [lldb] Use std::string instead of llvm::Twine in GDBRemoteCommunicationClient
1e21555961d86f3541afc094e4d9abdcd609cccb [lldb] Remove nested switches from ARMGetSupportedArchitectureAtIndex (NFC)
f4451aa7fb5a47395215bb9d02caed9a900c3929 [lldb] Remove 'result' variable which is set but not used (NFC)
1512c8f2d9a1b0edfb4711d961bd3d394ece0648 [lldb] Fix C2360: initialization of 'identifier' is skipped by 'case' label
3a153b625ee71eb739f8050be713b35af862c466 Support looking up absolute symbols
9afd5a03c45ba286203d97870c8aa9a1c4bf2d82 Add a requires line to test.
f71c16238c73ef3bfcfc2446f869e6cd844d6afe Use yaml2obj instead of relying on invoking the Darwin system assembler.
f55350ddef41363d8c476e50ce6e0be7917ddcf5 headers: optionalise some generated resource headers
  Skipped - picked the correpsonding next commit c17d9b4b125e5561925aa85aaa0b113e383a2ee5 and d96161a179c7dabad3af0bbf8e899cfe077a8a4b instead
b987701c0c7c9faa0443b3888e842c096e520572 test: mark more ARM64 tests are requiring the ARM backend
  Skipped - not on next
a160e45e45cd094327ed2881529559632f6dac19 [AArch64] Add missing tests for i8 vector to half conversions.
  Skipped - already fixed by 9583d5f591e82be69751499949d46203fa3297ef
74973c3a97fd45e10fcc63775e9bbd2f1f972b7c [lldb] Fix that the embedded Python REPL crashes if it receives SIGINT
55a9501651a0197d4666f5609e4b631b3b65ff95 reland: [VFS] Use original path when falling back to external FS
3a083b5dc36b18ea8a8f591d69959dfd3655e0d3 [lldb] Fix Scripted ProcessLaunchInfo Argument nullptr deref
fd6b58b925450ed8f5a099cada0b03c4d7246fa3 [lldb/bindings] Change ScriptedThread initializer parameters
11ab69d84cedac10be5ce49961d13a2298143bbb [lldb/test] Update TestScriptedProcess to use skinny corefiles
ff790af7ab759e0d8888c810acc99dda61da4b22 [lldb/test] Skip TestScriptedProcess when using system's debugserver (NFC)
c7b4936e807bc6c76e769c9d0382a55843e07a5e [lldb/Plugins] Refactor ScriptedThread register context creation
4c1056637d176b2b5f3f6601018f2a0acf092ceb [lldb] Fix ScriptedThread build failure (NFC)
  Skipped - have upstream 214054f78a4e40656b17838300dff2f136032172
a7c4c5fe88c4f567439dfcc5405152881af6735d [lldb/bindings] Update python static bindings (NFC)
  Skipped - already regenerated bindings
03844d173ba7b00228d8018995f0a3c312386634 [lldb] Improve error reporting in `lang objc tagged-pointer info`
3a3a862896ef81cab2f868e58f376b54d5b95cee [lldb] Update tagged pointer command output and test.
68b08e5653ef83d0c2d44e4332d905192277fc2a [lldb] Improve 'lang objc tagged-pointer info' command
52a7a8d10b55c9d890c94c2fa60edc64590bcdb6 [lldb] Remove failures case from TestTaggedPointerCmd
13a2b204874e5dc67e94cb5c3421175e8e8b4175 Windows: support `DoLoadImage`
  Skipped - picked the corresponding next commit fbf9b76f5360df5f486aaef72cfffe124f42c1a3 instead
7a77da8c3a51dde0c4821dbf6fea45aeda81ed72 [lldb] Remove unused GetAllocationStrategy function
716bb2c5be0c07e638904790faf73e997f138049 Update PlatformWindows.cpp
  Skipped - picked the corresponding next commit 01f8e3db88560a593d4cbb880c6e86b095e99136 instead
627f7d36b0241ddca3f156a342a72f1df3d2e5e0 [lldb] Don't set the OS for ARMGetSupportedArchitectureAtIndex
248daba2ddf35be88c25fa162e38174ee12282d2 [lldb] Consider bound types when deciding if the overall type is dynamic
b26f76314fe85c31872c6bc04268c381aea1f342 Add support for 32-bit reflection contexts.
c0b76ea8f88fded23d764e8a302168104623b278 [lldb] Desugar unlimited levels when calculating type name
1f2c20f16bfd2218fc4808f30a7ff44d63ad25c4 [lldb] Fix desugaring of dicts on TypeSystemSwiftTypeRef
f7e500c2d796ff098a163bd0d38e43e5978818f2 [lldb] Implement TypeSystemSwiftTypeRef::GetFullyUnqualifiedType
a5c262237329d3800196820466d5ce5eac7f62ee [lldb] Implement GetFormat in terms of GetTypeInfo
  Skipped - picked the corresponding next commit bd51db5878210d61c41e03ed0dc5e6ba6175be42 instead
5efa8c076c21a60e1a6739dbef88d428fb93ca05 [lldb] Use Desugar function in GetCanonicalNode and remove duped code
15da5c8c55321f9dba4175ec9d623aff7e05c521 Add missing default specifier
5897a27e42b181ab4dc0ccc4a7ed9bad47ff2683 Simplify logic to identify dyld_sim in Simulator debugging on macos

### CODE REVIEW

**Comment by bnbarham** [comment]
@aschwaighofer please confirm whether the following two are needed:
609fe52005af - (9 weeks ago) Don't use lifetime.start based alloca localization for ABI.Async/ABI.Retcon - Arnold Schwaighofer
cb413d937bb2 - (9 weeks ago) Disable lifetime.start sinking for ABI::Async and ABI::Retcon - Arnold Schwaighofer

I've included them at the moment since it seems like they will be, but note that the corresponding upstream PR isn't merged yet.

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]
Please make sure that @JDevlieghere explicitly signs off here - I'm not sure about the changes to the python bindings generated swig file.

**Comment by JDevlieghere** [comment]
We'll just generate them again :-)

**Comment by bnbarham** [comment]
Two test failures on MacOS:
  Swift(macosx-x86_64) :: DebugInfo/async-args.swift
  Swift(macosx-x86_64) :: Sanitizers/tsan/racy_async_let_fibonacci.swift

racy_async_let_fibonacci.swift should have been fixed by https://github.com/apple/llvm-project/pull/3596 so I'll have to look into that one again. async-args.swift is new.

Linux failed to build a LLDB unittest but it's not caused by this PR and should be failing on MacOS too 🤔. In any case I'll fix in a follow up PR.
  lldb/unittests/Symbol/TestTypeSystem.cpp:76:11: error: no matching member function for call to 'GetTypeSystemForLanguage'

Can also regenerate the bindings in a followup. Going to go ahead and merge.

**Comment by adrian-prantl** [comment]
Just a guess, but maybe we need to cherry-pick commit fb8981d6ee651b820a597757439bea60dae1c57d for the async args test?

**Comment by bnbarham** [comment]
Thanks Adrian! I'll do another follow-up PR with some more fixes.

**Comment by bnbarham** [comment]
Fixed async-args on the Swift side, see comments in https://github.com/apple/swift/pull/40447.

Re-generated bindings and fixed `TestTypeSystem.cpp` in https://github.com/apple/llvm-project/pull/3635.

**Pull request merged**
