### PR TITLE
[lldb] Fix incorrect format specifiers

### PR DESCRIPTION
**Pull request by adrian-prantl**
depends on https://github.com/swiftlang/llvm-project/pull/9615

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by JDevlieghere — APPROVED** [review]
`6f910e1d07ce914152acda44b5959f7ae7c80b69` LGTM

**Review by kastiglione — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
