### PR TITLE
JIT ASi cherry-picks

### PR DESCRIPTION
**Pull request by compnerd**
Cherry-pick a couple of commits from master to fix JIT issues with the PAGEOFF12 relocation with addend cases.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @lhames @hyp

**Comment by compnerd** [comment]
@swift-ci please test

**Review by lhames — APPROVED** [review]
Tested locally. Fixes rdar://66285639.

**Comment by cooperp** [comment]
LGTM.

**Review by cooperp — APPROVED** [review]

**Pull request merged**
