### PR TITLE
Reland __attribute__((swiftasynccall)) w/ debuginfo and codegen fixes.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
Most of the patch is as earlier, with the following changes:

1. Correct target checks: right now, we only allow ARM (32-bit and 64-bit) and x86_64.
2. Removed the restriction that `swift_async_context` can only be applied to `swiftasynccall` functions.
3. Updated the `swiftasyccall` documentation.

TODO:
- [x] Remove some superfluous whitespace changes that crept in due to a rebase.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci  test

**Review by aschwaighofer — APPROVED** [review]
lgtm

**Comment by varungandhi-apple** [comment]
@swift-ci test and merge

**Comment by aschwaighofer** [comment]
@swift-ci please test

**Comment by varungandhi-apple** [comment]
There is a compilation error on Linux but not on macOS.

```
/home/buildnode/jenkins/workspace/apple-llvm-project-pr-linux/llvm-project/clang/lib/CodeGen/CGCall.cpp:5155:52: error: ‘CallingConv’ is not a class, namespace, or enumeration
     else if (CallInfo.getASTCallingConvention() == CallingConv::CC_SwiftAsync &&
                                                    ^
/home/buildnode/jenkins/workspace/apple-llvm-project-pr-linux/llvm-project/clang/lib/CodeGen/CGCall.cpp:5156:54: error: ‘CallingConv’ is not a class, namespace, or enumeration
              CurFnInfo->getASTCallingConvention() == CallingConv::CC_SwiftAsync)
                                                      ^
```

Strange...

**Comment by varungandhi-apple** [comment]
Let's see if this works without the qualifier.

@swift-ci test

**Comment by varungandhi-apple** [comment]
It's the baseline test failures on Linux. Merging.

**Pull request merged**
