### PR TITLE
Static analyzer cherrypicks 25

### PR DESCRIPTION
**Pull request by haoNoQ**
Clang Static Analyzer is traditionally kept reasonably fresh on stable branches through continuous cherry-picking.

### CODE REVIEW

**Comment by haoNoQ** [comment]
@swift-ci test

**Comment by haoNoQ** [comment]
@swift-ci test 🤞

**Comment by haoNoQ** [comment]
@swift-ci test

**Comment by t-rasmud** [comment]
The following commits were landed without being accepted by their reviewers:
[https://github.com/apple/llvm-project/pull/3982/commits/bd4f579711c4a4e51ad369dd715cb722e34ff3bf](https://github.com/apple/llvm-project/pull/3982/commits/bd4f579711c4a4e51ad369dd715cb722e34ff3bf)
[https://github.com/apple/llvm-project/pull/3982/commits/989e905dc291d23880b21d9fff343f22653512f2](https://github.com/apple/llvm-project/pull/3982/commits/989e905dc291d23880b21d9fff343f22653512f2)

Otherwise, LGTM.

**Review by t-rasmud — APPROVED** [review]

**Comment by haoNoQ** [comment]
> The following commits were landed without being accepted by their reviewers: [bd4f579](https://github.com/apple/llvm-project/commit/bd4f579711c4a4e51ad369dd715cb722e34ff3bf) [989e905](https://github.com/apple/llvm-project/commit/989e905dc291d23880b21d9fff343f22653512f2)

Yeah this happens from time to time.

[989e905](https://github.com/apple/llvm-project/commit/989e905dc291d23880b21d9fff343f22653512f2) is accepted by Gabor but previously marked as rejected by Valeriy with minor comments; Valeriy isn't working on the static analyzer anymore so he couldn't update his verdict as these comments were fixed but phabricator still thinks it's 1:1 so it's not marking the whole revision as accepted.

[bd4f579](https://github.com/apple/llvm-project/commit/bd4f579711c4a4e51ad369dd715cb722e34ff3bf) is a relatively small patch by Gabor who already contributed a lot to our ad-hoc constraint solver. I think post-commit review (with the verbal accept by Balázs) is appropriate here. To be fair, I also think I should have at least said "cool!" because the patch is really cool :)

> All checks have failed

Ok jenkins crashed, third time the charm I guess.

**Comment by haoNoQ** [comment]
@swift-ci test

**Pull request merged**
