### PR TITLE
[lldb] Skip failing tests on Linux

### PR DESCRIPTION
**Pull request by JDevlieghere**

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test linux platform

**Comment by shahmishal** [comment]
```
/home/buildnode/jenkins/workspace/apple-llvm-project-pr-linux/swift-corelibs-foundation/Sources/Foundation/NSLock.swift:26:35: error: no type named 'pthread_mutex_t' in module 'Glibc'
```

**Comment by shahmishal** [comment]
@swift-ci please test linux platform

**Comment by JDevlieghere** [comment]
Same error, but this happens after all the LLDB tests passed.

**Pull request merged**
