### PR TITLE
Cherry-picking

### PR DESCRIPTION
**Pull request by ziqingluo-90**
Cherry picks the up-to-date commits, which introduce no conflict, for clang static analyzer.

### CODE REVIEW

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Comment by haoNoQ** [comment]
Looks like 80328016c88e34ecd34fc6fa4539f60a341a800c may introduce new compiler warnings on each compilation (i.e., not constrained to static analysis) so it may disrupt people's build if they build with `-Werror`. I think we shouldn't cherry-pick it. It looks like a good patch and we would have cherry-picked it if it was _our_ patch, but when it's just a random warning improvement that we aren't explicitly seeking, it's just not our call to make, there are other folks that may or may not cherry-pick it depending on their circumstances. In any case it'll be picked up automatically on the next `stable/...` branch.

**Comment by haoNoQ** [comment]
Everything else looks great, thanks!!

**Review by haoNoQ — APPROVED** [review]
LGTM!

**Comment by ziqingluo-90** [comment]
> Looks like [8032801](https://github.com/apple/llvm-project/commit/80328016c88e34ecd34fc6fa4539f60a341a800c) may introduce new compiler warnings on each compilation (i.e., not constrained to static analysis) so it may disrupt people's build if they build with `-Werror`. I think we shouldn't cherry-pick it. It looks like a good patch and we would have cherry-picked it if it was _our_ patch, but when it's just a random warning improvement that we aren't explicitly seeking, it's just not our call to make, there are other folks that may or may not cherry-pick it depending on their circumstances. In any case it'll be picked up automatically on the next `stable/...` branch.

Got it.  I'll keep this in mind.

**Comment by ziqingluo-90** [comment]
@swift-ci test

**Pull request merged**
