### PR TITLE
[clang][cli] Generate custom cc1 options

### PR DESCRIPTION
**Pull request by jansvoboda11**
This PR implements generation of remaining command line options.

### CODE REVIEW

**Comment by dexonsmith** [comment]
@swift-ci test

**Review by dexonsmith — APPROVED** [review]
LGTM assuming the pre-commit CI passes.

**Comment by jansvoboda11** [comment]
The test failures don't seem to be related to my changes. Trying to rebase and run again...

**Comment by jansvoboda11** [comment]
@swift-ci test

**Comment by jansvoboda11** [comment]
@swift-ci test

**Comment by jansvoboda11** [comment]
@swift-ci Please test

**Comment by jansvoboda11** [comment]
@swift-ci Please test

**Comment by jansvoboda11** [comment]
The `LLVM :: Transforms/Coroutines/coro-split-swift-async.ll` failure reported in macOS tests is known on `main`.

Linux build fails because LLVM recently bumped the required Python version to 3.6 and the CI has version 3.5.2. installed. This was reported to the infrastructure team last week, so hopefully I'll soon be able to run the tests on Linux too.

**Comment by dexonsmith** [comment]
Woah, if it's already been down for a week, I don't think it makes sense to wait indefinitely on CI infrastructure. Feel free to merge once the macOS tests are passing / or match main exactly; I think that's enough signal.

**Comment by jansvoboda11** [comment]
Fair enough, thanks.

**Pull request merged**
