### PR TITLE
[AVR] make the AVR ABI Swift compatible

### PR DESCRIPTION
**Pull request by carlos4242**

### CODE REVIEW

**Comment by carlos4242** [comment]
@kubamracek

**Review by kubamracek — APPROVED** [review]

**Comment by kubamracek** [comment]
This will also need a cherry-pick.

**Comment by rauhul** [comment]
neat! I have no idea what this does

**Comment by carlos4242** [comment]
> neat! I have no idea what this does

Hi @rauhul ... good question, I have to say the slightly unsatisfying answer is I curated a load of bug fixes over the years without keeping close enough notes as to the exact details of the bugs they were fixing. In nearly every case, the fix was to address the compiler "crashing" (i.e. trapping on an assert).

I'm pretty certain the "crash" in question that this patch is intended to fix is from this helper function in clang...
```
  /// Returns Swift ABI info helper for the target.
  const SwiftABIInfo &getSwiftABIInfo() const {
    assert(SwiftInfo && "Swift ABI info has not been initialized");
    return *SwiftInfo;
  }
```

...what I can't tell you (without doing a custom build to track it down) is where exactly this crash occurs in normal use. My vague memory/guess is if you run the swift compiler and it accesses the clang importer then that frequently causes this "crash" and as a result, all architectures that swift supports must have this sort of patch added to clang. It did come up on the call a week ago, discussed by @kubamracek and I because he had to add it to clang in order to get RISCV working. I flagged that I had tried without luck to get this patch merged to llvm/clang back in December/January and gave up. Kuba seemed to be saying that he too thinks this patch is essential for Swift to properly support AVR, but he can probably fill in the details a lot better than I can.

For me, from the next point on, it's most useful to try building the standard library for AVR and seeing what breaks next.

**Comment by kubamracek** [comment]
I think this change can go in, it's clearly needed for any compilations to work on AVR. We did the exact same change for RISC-V here: https://github.com/apple/llvm-project/pull/8229/

But we'll need a cherry-pick to `stable/20230725`, can you prepare it?

**Comment by carlos4242** [comment]
@kubamracek sure thing... do I just create a separate PR targeted to that release? I'm sorry I'm not very familiar with the apple procedures for llvm patches.

**Comment by kubamracek** [comment]
Yes, a separate PR.

**Comment by carlos4242** [comment]
https://github.com/apple/llvm-project/pull/8970 is this ok?

**Pull request merged**
