### PR TITLE
[lldb] Cherry-pick lost commits during the 6.1 branch

### PR DESCRIPTION
**Pull request by felipepiovezan**

### CODE REVIEW

**Comment by felipepiovezan** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by felipepiovezan** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]

**Comment by felipepiovezan** [comment]
Closing in favor of https://github.com/swiftlang/llvm-project/pull/9691

**Pull request closed without merging**
