### PR TITLE
[CMake] BUILD_SHARED_LIBS fixes

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please test platform

**Review by compnerd — APPROVED** [review]
The changes are fine, but to verify, these are due to the swift changes?

You probably want to mirror these to apple/stable/20200714 for the rebranch.

**Comment by davezarzycki** [comment]
I just haven't built with BUILD_SHARED_LIBS in a while. These problems tend to pile up and I think I'm the only person testing this Swift build setup. And ya, the master rebranch will need retesting.

**Comment by davezarzycki** [comment]
I guess said differently, I try to always verify that top-of-tree LLVM still successfully builds with ` BUILD_SHARED_LIBS` before submitting a patch to Apple's fork. Sometimes LLVM proper can go a few days where ` BUILD_SHARED_LIBS` is broken before it is fixed because very few if any LLVM bots test with ` BUILD_SHARED_LIBS` enabled.

**Pull request merged**
