### PR TITLE
Windows compatibility fixes

### PR DESCRIPTION
**Pull request by ravi-ramaseshan**
A few changes required to get these test to work on Windows.

### CODE REVIEW

**Comment by ravi-ramaseshan** [comment]
@swift-ci test

**Comment by hyp** [comment]
Disabling the refactoring test cases on Windows seems fine to me. I'd like to get @jkorous-apple opinion on the indexing changes before this is merged though.

**Review by dexonsmith — APPROVED** [review]
This LGTM.

**Comment by dexonsmith** [comment]
> Disabling the refactoring test cases on Windows seems fine to me. I'd like to get @jkorous-apple opinion on the indexing changes before this is merged though.

I had a look and I'm comfortable signing off on it.

**Review by jkorous-apple — APPROVED** [review]
LGTM. Ravi, thanks for fixing this and sorry for the delay!

**Comment by ravi-ramaseshan** [comment]
Can someone please merge this change. I do not (think I) have commit access.

**Pull request merged**
