### PR TITLE
[stable/20211026] More cherry-picks

### PR DESCRIPTION
**Pull request by bnbarham**
More changes from stable/20210726. Most of these aren't in `next` yet either but I assume they all should be.

### CODE REVIEW

**Comment by bnbarham** [comment]
@compnerd 27d9612 is actually pretty old, I somehow missed it in my last round of cherry-picks. Hopefully I didn't miss any others!

**Review by ahatanaka — APPROVED** [review]

**Review by medismailben — APPROVED** [review]

**Review by compnerd — APPROVED** [review]

**Comment by bnbarham** [comment]
Just added e0d82ff which I mistakenly skipped in the previous set (@compnerd)

**Comment by bnbarham** [comment]
@swift-ci please test

**Review by kastiglione — APPROVED** [review]
+1 for the commits of mine

**Review by JDevlieghere — APPROVED** [review]
Thank you!

**Comment by bnbarham** [comment]
@swift-ci please test

**Pull request merged**
