### PR TITLE
Fix module build for clang cc1_main CAS

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
rdar://103448355

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Review by akyrtzi — APPROVED** [review]
I think we should add `using namespace llvm;` in `cc1_main.cpp`, so that the error "reference to 'cas' is ambiguous" shows up for non-module build as well, otherwise we may keep introducing this kind of error.

Otherwise LGTM.

**Comment by cachemeifyoucan** [comment]
> I think we should add `using namespace llvm;` in `cc1_main.cpp`, so that the error "reference to 'cas' is ambiguous" shows up for non-module build as well, otherwise we may keep introducing this kind of error.
> 
> Otherwise LGTM.

I think that can create the reverse problem of forgetting to prefix `llvm::` for other things. I don't like diverge that from upstream. At least we can catch this mistake when landing on `next branch now

**Comment by akyrtzi** [comment]
> I think that can create the reverse problem of forgetting to prefix `llvm::` for other things.

How so, is your concern is that we'll pick something from `cc1_main.cpp` to upstream and we'd have to fix potential errors for the patch? At least no CI is going to break that way, it's only an issue for when creating the upstreaming patch.

> I don't like diverge that from upstream. At least we can catch this mistake when landing on `next branch now

Wasn't the related code already in `next` for a long time now? Or am I misunderstanding?
I'd like to avoid being in a situation where I merge PR with all tests passing and days (weeks?) later I get radars for bots that have build errors because of the PR.

**Comment by akyrtzi** [comment]
In any case, we should move the caching code out of `cc1_main.cpp` anyway, in which case we can add `using namespace llvm;` to the new file; we don't need to add it to `cc1_main.cpp`.

**Comment by cachemeifyoucan** [comment]
Agree we should move out when upstream.

My concern was that we will forgot to spell out types correctly from llvm namespace. 

Let me merge this so the bootstrap bots can recover over the weekend. We can discuss future mitigation later

**Pull request merged**
