### PR TITLE
Sink SwiftHost.cpp into HostInfo (NFC)

### PR DESCRIPTION
**Pull request by adrian-prantl**
This refactors the code that currently lives in Expression/SwiftHost
to find a new home in HostInfo. The idea is to eventually allow
different implementations per host platform. Note that this is
intentionally just moving the code around, there has been no attempt
at cleaning up the code or interface.

rdar://92640609

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by JDevlieghere — APPROVED** [review]

**Review by compnerd — COMMENTED** [review]
How does this hook up the `HostInfoPosix` into the Windows path?  It feels like this regresses the Windows path.

**Comment by adrian-prantl** [comment]
> How does this hook up the `HostInfoPosix` into the Windows path? It feels like this regresses the Windows path.

Thanks @compnerd, you are right, HostInfoWindows does not inherit from HostInfoPosix. So I made the patch even more complex, by moving the shared functionality into `common/` :-)

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
