### PR TITLE
[Gardening] Adjust for apple/swift#29155

### PR DESCRIPTION
**Pull request by CodaFi**
Forwarding #563 to master-next.

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]
Seems reasonable.

**Comment by adrian-prantl** [comment]
You may or may not also need to make this change in swift/master-rebranch.

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
Spoke with Jonas about the branching strategy here.  Going to merge this despite the failure for now.

**Comment by CodaFi** [comment]
⛵️

**Comment by CodaFi** [comment]
Off to swift/master-rebranch next

**Comment by CodaFi** [comment]
Ah, cool it's already there.  Thanks y'all.

**Pull request merged**
