### PR TITLE
[Swift] Implement error handling for dwim-print -O

### PR DESCRIPTION
**Pull request by adrian-prantl**
rdar://126071026

This is mostly cherry-picks from upstream, the Swift specific changes are in the topmost commit.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by kastiglione — APPROVED** [review]

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
