### PR TITLE
[WIP/RFC] Remove swift::ASTContext from lldb::SwiftASTContext

### PR DESCRIPTION
**Pull request by adrian-prantl**
This experimental branch explores a world where each per-module Swift TypeSystem only deals with CompilerTypes that are mangled names and SwiftASTContextForExpressions is the only class to hold a swift::ASTContext.

This is not ready yet, the patch is full of FIXMEs and redundant pattern-matching code that wants to be factored out.

### CODE REVIEW

**Review by dcci — APPROVED** [review]
lgtm

**Comment by adrian-prantl** [comment]
Current status:
```
Expected Passes    : 128
  Expected Failures  : 1
  Unsupported Tests  : 12
  Unresolved Tests   : 1
  Unexpected Failures: 164
```

**Comment by adrian-prantl** [comment]
Now at

```
  Expected Passes    : 147
  Expected Failures  : 1
  Unsupported Tests  : 12
  Unresolved Tests   : 14 (new assertion in GetMemberOffset)
  Unexpected Failures: 132
```

**Comment by adrian-prantl** [comment]
```
  Expected Passes    : 210
  Expected Failures  : 1
  Unsupported Tests  : 12
  Unresolved Tests   : 12
  Unexpected Failures: 71
```

**Comment by dcci** [comment]
@adrian-prantl please ping me and let me know when this is ready for review

**Comment by adrian-prantl** [comment]
Now with typeref-based typealias binding / canonicalization.

```
  Expected Passes    : 211
  Expected Failures  : 1
  Unsupported Tests  : 12
  Unresolved Tests   : 13
  Unexpected Failures: 70
```

**Comment by adrian-prantl** [comment]
Today's update include type canonicalization and several incidental bugfixes.
```
  Expected Passes    : 218
  Expected Failures  : 1
  Unsupported Tests  : 12
  Unresolved Tests   : 9
  Unexpected Failures: 67
```

**Comment by dcci** [comment]
Way to go!

**Comment by adrian-prantl** [comment]
Frustrated with the slow progress I've been making I added a mechanism that allows running (most) queries in TypeRef and AST space, throwing an assertion when they mismatch. *Much* faster to debug this way!

```
  Expected Passes    : 236
  Expected Failures  : 1
  Unsupported Tests  : 12
  Unresolved Tests   : 8
  Unexpected Failures: 50
```

**Comment by adrian-prantl** [comment]
More assertions and the ability to resolve Clang types:

```
  Expected Passes    : 231
  Expected Failures  : 1
  Unsupported Tests  : 12
  Unresolved Tests   : 5
  Unexpected Failures: 58
```

**Comment by adrian-prantl** [comment]
I discovered an interesting challenge today. I was wondering why the TypeRef context couldn't return the same type name for a Clang-imported `NSDecimal` type. Turns out the ASTContext returns the name as `Foundation.Decimal and` this is significant for LLDB's data formatters. This is unfortunate since only ClangImporter really knows the complicated rules by which to import Clang Decls into Swift. So I thought, let's bite the bullet and initialize a minimal ClangImporter for each context and pick out the correct Clang module from DWARF and so we can ask our minimal ClangImporter to compute the imported name of `Foundation.Decimal`. However, that doesn't work! The problem is that the mapping from NSDecimal to Decimal is defined in an APINote file and because the clang::Decl we sent to ClangImporter was deserialized from DWARF, the APINote is missing. Here are a couple of options I've brainstormed:
- import system modules from source (full accuracy, but DOSes the filesystem if every context does that, also not resilient against search path snafu)
- parse APINotes in LLDB and attach the attributes to the AST we're generating
- parse APINotes in LLDB and perform trivial substitutions such as the one in this example in LLDB
- serialize APINote attributes in clang in DWARF and deserialize them (really I only need the Swift name attribute for the debugger) in LLDB and attach them to the AST. (It's not clear to me where they are parsed, so this may or may not make sense).

**Comment by adrian-prantl** [comment]
I've uploaded a working implementation of loading APINotes via the Clang module provenience information in DWARF.

I am going to switch to a new strategy now where I'm not going to attempt to load this patch in one go, but instead land it one NFC refactoring at a time, now that I know what's needed.

**Comment by shahmishal** [comment]
The project moved the branch to `swift/main` and deleted `swift/master` branch, so GitHub automatically closed the PR. Please re-create the pull request with `swift/main` branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
