### PR TITLE
[BoundsSafety] Bring full support for -fbounds-safety

### PR DESCRIPTION
**Pull request by rapidsna**
-fbounds-safety is a C extension to enforce bounds safety to prevent out-of-bounds (OOB) memory accesses. The extension offers bounds annotations that programmers can use to attach bounds to pointers. Using this bounds information, the compiler inserts bounds checks on every pointer dereference, ensuring that the program does not access memory outside the specified bounds. The compiler requires programmers to provide enough bounds information so that the accesses can be checked at either run time or compile time — and it rejects code if it cannot.

For more details, please refer to

RFC discussions: https://discourse.llvm.org/t/rfc-enforcing-bounds-safety-in-c-fbounds-safety/70854
The design documentation: https://clang.llvm.org/docs/BoundsSafety.html
The bounds annotations provided by -fbounds-safety could potentially be useful to implement safe interoperation between C/C++ and safe languages such as Swift. Similar to lifetime dependency annotations as pitched [here](https://forums.swift.org/t/safe-and-efficient-c-interoperability-via-non-escapable-types-and-lifetimes/75426).

This patch contains collaborative work from @rapidsna @apple-fcloutier @patrykstefanski @delcypher @hnrklssn and from many other collaborators from the optimization and debugger side of support.

Cherry-picking https://github.com/swiftlang/llvm-project/pull/9665

### CODE REVIEW

**Comment by rapidsna** [comment]
@swift-ci test

**Comment by rapidsna** [comment]
@swift-ci llvm test

**Comment by rapidsna** [comment]
@swift-ci test

**Comment by rapidsna** [comment]
@swift-ci llvm test

**Comment by rapidsna** [comment]
@swift-ci test

**Comment by rapidsna** [comment]
@swift-ci llvm test

**Comment by rapidsna** [comment]
@swift-ci test

**Comment by rapidsna** [comment]
@swift-ci test

**Comment by rapidsna** [comment]
@swift-ci test llvm

**Review by devincoughlin — APPROVED** [review]

**Comment by rapidsna** [comment]
@swift-ci test

**Comment by rapidsna** [comment]
@swift-ci test llvm

**Comment by rapidsna** [comment]
@swift-ci test

**Comment by rapidsna** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]
Debug info / LLDB parts LGTM.

**Pull request merged**
