### PR TITLE
cherry picks to Stable/20221013 #4

### PR DESCRIPTION
**Pull request by ziqingluo-90**

### CODE REVIEW

**Comment by ziqingluo-90** [comment]
I removed `-Wunsafe-buffer-usage` commits.  Let me politely ping @haoNoQ and @jkorous-apple

**Review by haoNoQ — APPROVED** [review]
LGTM!

**Comment by haoNoQ** [comment]
Wait a sec, I don't see any `std::nullopt` in this branch yet, and I suspect this isn't because we didn't cherry-pick any, but because we're still compiling downstream with c++14 which doesn't have optionals yet.

**Comment by haoNoQ** [comment]
Yeah indeed, I tried it manually and I'm getting errors on this branch:
```
/Users/artemdergachev/github/llvm-project/clang/lib/StaticAnalyzer/Checkers/SimpleStreamChecker.cpp:239:3: error: no template named 'optional' in namespace 'std'; did you mean 'Optional'?
  std::optional<int> Opt = std::nullopt;
  ^~~~~~~~~~~~~
  Optional
/Users/artemdergachev/github/llvm-project/clang/include/clang/Basic/LLVM.h:78:15: note: 'Optional' declared here
  using llvm::Optional;
              ^
/Users/artemdergachev/github/llvm-project/clang/lib/StaticAnalyzer/Checkers/SimpleStreamChecker.cpp:239:33: error: no member named 'nullopt' in namespace 'std'
  std::optional<int> Opt = std::nullopt;
                           ~~~~~^
2 errors generated.
```
Did these cherry-picks compile locally for you? I suspect that they rely on another patch that bumps the C++ standard version in CMake configs, and we probably don't have the authority to cherry-pick them.

**Comment by haoNoQ** [comment]
Never mind, I looked at the wrong branch. This compiles perfectly, please merge!

**Comment by ziqingluo-90** [comment]
> Never mind, I looked at the wrong branch. This compiles perfectly, please merge!

Thank you! :)

**Pull request merged**
