### PR TITLE
Fix 40056: Prevent outlining of blocks with token type instructions (…

### PR DESCRIPTION
**Pull request by compnerd**
…#99759)

Hot cold splitting should not outline:
1. Basic blocks with token type instructions
1. Functions with scoped EH personality (As suggested by Vedant in https://github.com/llvm/llvm-project/issues/40056#issuecomment-981009129)

Fixes: #40056
(cherry picked from commit c59ee7ec627533e00f654d052ade51c9daf7e722) (cherry picked from commit 267c6ed85f62ef521c93982f988e56ab9ed535de)

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
**Explanation**: Avoid performing HCS on certain constructs where the results are unlikely to be valuable and cause invalid IR to be formed.
**Scope**: This fixes compilation of code, particularly with C++, on Windows, including code in the toolchain (e.g. llbuild).
**Issue**: llvm/llvm-project#40056
**Risk**: C++ code with exceptions on Windows may continue to not be compiled properly.
**Testing**: CI builds of the toolchain
**Reviewer**: @compnerd

**Comment by compnerd** [comment]
CC: @airspeedswift @DougGregor

**Comment by compnerd** [comment]
CC: @bnbarham

**Review by fredriss — APPROVED** [review]

**Pull request merged**
