### PR TITLE
[rebranch] Couple missing cherry-picks from stable/20230725

### PR DESCRIPTION
**Pull request by bnbarham**

### CODE REVIEW

**Comment by bnbarham** [comment]
@al45tair this branch isn't sticking around and so it may be that we don't even need these here. But if they're needed in general, they should either go to upstream or next so that they are picked up in the next stable branch (I'll probably close this PR if rebranch ends up building).

**Comment by al45tair** [comment]
Yeah, they could do with going to next, I think. I had cherry picked them to upstream, but honestly I think we might be better off just landing them on next at this point.

**Review by al45tair — APPROVED** [review]

**Comment by al45tair** [comment]
Whether we need them in this branch, I'm not sure — it depends on whether we're ever in any danger of using this to build a Swift toolchain that might want to work with the fully static Linux SDK. If that isn't happening with this branch, they aren't really needed here.

**Comment by bnbarham** [comment]
> it depends on whether we're ever in any danger of using this to build a Swift toolchain that might want to work with the fully static Linux SDK

Extremely unlikely. We'll branch again in a few weeks. I'll just close, thanks 🙇

**Pull request closed without merging**
