### PR TITLE
arm64e: Don't authenticate a ptrauth-qualified pointer before it's

### PR DESCRIPTION
**Pull request by ahatanaka**
passed to @llvm.ptrauth.strip, @llvm.ptrauth.auth, or
@llvm.ptrauth.resign

rdar://problem/60393465

### CODE REVIEW

**Review by rjmccall — COMMENTED** [review]
You need to update the documentation for these builtins: both the comments in `<ptrauth.h>` and the user documentation.

I feel like this is much more obviously the right thing to do with `ptrauth_strip` than it is with `ptrauth_auth` or `ptrauth_auth_and_resign`, and I'm much more concerned about this interacting poorly with macros or other kinds of metaprogramming with the latter two.  Are we sure that the latter cases are actually important?

**Comment by ahatanaka** [comment]
I searched purplefish for the uses of `ptrauth_auth` and `ptrauth_auth_and_resign` and I didn't see places where ptrauth-qualified pointers are passed. It looks like those cases are not really important.

Are there cases where ptrauth-qualified pointers are passed to those builtins and the code isn't incorrect? It seems that passing an authenticated raw pointer to those builtins is almost always wrong. It's not too clear to me what kind of poor interaction with macros or metaprogramming you are worried about.

**Comment by ahatanaka** [comment]
I searched the codebase for the uses of ptrauth_auth and ptrauth_auth_and_resign and I didn't see places where ptrauth-qualified pointers are passed. It looks like those cases are not really important.

Are there cases where ptrauth-qualified pointers are passed to those builtins and the code isn't incorrect? It seems that passing an authenticated raw pointer to those builtins is almost always wrong. It's not too clear to me what kind of poor interaction with macros or metaprogramming you are worried about.

**Comment by rjmccall** [comment]
Oops, sorry for accidentally closing, I mis-clicked.

Not seeing any checked-in code that does this may not be very informative — after all, it doesn’t work, they'll have worked around that.  So you may need to look at the surrounding context to see if there's some sort of attempt to load a pointer without resigning it.

The macro case would be something that expects a value that's signed the standard way for a pointer value of its type — e.g. a function pointer — which would then fail if you passed it an expression that loads that pointer directly from a `__ptrauth`-qualified l-value.  So the intermediate step may be semantically important in a way that it probably isn't for a strip.

I think we should warn for `ptrauth_auth` and `ptrauth_auth_and_resign` unless the expeceted schema matches the expected schema for the pointer type.  Only `ptrauth_strip` should get this "do what I mean" behavior.

**Comment by ahatanaka** [comment]
Ah, I forgot about function pointers.

I audited the uses of `ptrauth_auth` and `ptrauth_auth_and_resign` and I didn't see anything that looked like an attempt to avoid an auth on a ptrauth-qualified pointer. But it's possible that someone might have initially tried to use a ptrauth-qualified pointer and changed the code after learning that ptrauth-qualified pointer gets resigned or authenticated when it's passed to the builtins.

After thinking about this more, I think suppressing the auth call as this patch is doing has problems. For example, this patch doesn't suppress auth calls when a more complex expression (e.g., conditional expression) is passed to the builtins: 

```
void * __ptrauth(1,0,100) g1 = p1;
void * __ptrauth(1,0,100) g2 = p2;
__builtin_ptrauth_auth(c ? g1 : g2, 1, 100);
```

It seems that the root of the problem is that it's not immediately clear that lvalue conversion causes the ptrauth-qualified pointer to be authenticated. Maybe it's not even clear that there is an implicit lvalue conversion. For example, is it clear to most people that `g1` and `g2` get authenticated before the result of the conditional expression is signed in the following code?

```
void * __ptrauth(1,0,100) g1 = p1;
void * __ptrauth(1,0,100) g2 = p2;
void * __ptrauth(1,0,100) p = c ? g1 : g2;
```

So maybe we shouldn't change the existing behavior and instead warn when ptrauth-qualified pointers are passed to `ptrauth_auth` or `ptrauth_auth_and_resign` and, as you suggested, define a new builtin that does a raw load of a ptrauth-qualified pointer in case there are users who want to avoid emitting the resign or auth call.

**Comment by rjmccall** [comment]
Yeah, I think warning with the auth/auth-and-resign builtins is the way to go.  We can look through strips, and we'll just have to be explicit that it only works when the argument is immediately an l-value.

**Comment by ahatanaka** [comment]
If we are going to diagnose invalid pointers passed to the builtins, I think we'll have to do it in Sema, and to do that in Sema, we'll have to move `CodeGenOptions::PointerAuthOptions` to `LangOptions`. Should I create a separate pull request for that?

**Comment by rjmccall** [comment]
Oh, I hadn't even thought about that.  Maybe we can just warn unconditionally for now and see if it's a problem.

**Comment by ahatanaka** [comment]
Do you mean unconditionally when the pointer argument is an lvalue-to-rvalue conversion of a ptrauth-qualified variable or field (except when the builtin is `ptrauth_strip`)? So, at least for now, we won't diagnose pointers that are known to be signed using a key or discriminator value that is different from the expected value? I think you can detect that kind of mismatch when the pointer's type is a function pointer type, for example.

**Comment by shahmishal** [comment]
The project moved the branch to `apple/main` and deleted `apple/master` branch, so GitHub automatically closed the PR. Please re-create the pull request with `apple/main` branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
