### PR TITLE
Merge bastille into rebranch

### PR DESCRIPTION
**Pull request by JDevlieghere**

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by fredriss** [comment]
@swift-ci Please test Linux

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@shahmishal is looking into the Linux build failure. On macOS `TestPlaygrounds.py` failed because of the builder refactoring, let me take a look and push a fix for that.

**Comment by shahmishal** [comment]
Linux bot is using clang-4.0: 
```
19:58:01 -- The C compiler identification is Clang 4.0.0
19:58:02 -- The CXX compiler identification is Clang 4.0.0
```

**Comment by shahmishal** [comment]
@swift-ci clean test Linux

**Comment by shahmishal** [comment]
cc: @hyp @Bigcheese Do you know what's going on with Linux failure?

```
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:120:23: error: no matching constructor for initialization of 'std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >'
```

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci Please test

**Pull request merged**
