### PR TITLE
[lldb] Various next fixes

### PR DESCRIPTION
**Pull request by bnbarham**
Noticed some failures when I cherry-picked a few commits in a previous PR. This is fixes for most of those.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@JDevlieghere I expect the build to fail in `lldb/source/Plugins/Language/Swift/SwiftFormatters.cpp`. https://reviews.llvm.org/D113098 made some to `ProcessSP` and `TargetSP` changes that will need to be taken into account in there, but they seemed more involved than I was comfortable with.

**Comment by bnbarham** [comment]
@compnerd 1509f81 is the cherry-pick for the swifttailcc issue.

EDIT: I'm putting that up in another PR. These are all LLDB compilation issues where as that one is a LLVM test, so probably better to get it in separately.

**Review by JDevlieghere — APPROVED** [review]
I wouldn't have cherrypicked the static bindings commit, but it doesn't hurt either.

**Comment by bnbarham** [comment]
> I wouldn't have cherrypicked the static bindings commit, but it doesn't hurt either.

I honestly can't remember if I actually just regenerated them or if it was a cherry-pick 🤔. Worth me removing?

EDIT: Note that the only cherry-pick here was the "Re-arrange some..." which I just rebased to replace "APPLE" with "SWIFT" since that's what's used everywhere else. So the regenerate isn't a cherry pick, I did actually re-generate.

**Pull request merged**
