### PR TITLE
[lldb] Disable tests affected by ld_new bug

### PR DESCRIPTION
**Pull request by kastiglione**
Cherry pick https://github.com/llvm/llvm-project/pull/83941 and https://github.com/llvm/llvm-project/pull/84246

### CODE REVIEW

**Comment by kastiglione** [comment]
@swift-ci test

**Review by JDevlieghere — APPROVED** [review]

**Review by bulbazord — APPROVED** [review]

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test windows

**Comment by kastiglione** [comment]
@swift-ci test windows

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test windows

**Comment by kastiglione** [comment]
@JDevlieghere can you merge?

**Pull request merged**
