### PR TITLE
Fix a bits/bytes confusion

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Review by kastiglione — APPROVED** [review]

**Comment by kastiglione** [comment]
Nice find

**Review by vedantk — APPROVED** [review]
Surprised we haven't seen test failures on ci.swift.org due to this!

**Comment by adrian-prantl** [comment]
> Surprised we haven't seen test failures on ci.swift.org due to this!

I should really add one. Something like

`let i = 23 // target variable i`

without actually launching the process should do the trick.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Pull request merged**
