### PR TITLE
Deal with DIComposite types which aren't enums in isUnsignedDIType

### PR DESCRIPTION
**Pull request by augusto2112**

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]
This is fine, but please upstream this soon.

**Comment by augusto2112** [comment]
@swift-ci test Windows

**Comment by adrian-prantl** [comment]
@augusto2112  Remember, you will need to re-cherry pick this to swift/release/6.0

**Comment by drodriguez** [comment]
This change makes ` LLVM :: DebugInfo/COFF/global-constants.ll` fail.

`llc` outputs the following after these changes:

```
.Ltmp18:
	.short	4359                            # Record kind: S_CONSTANT
	.long	4101                            # Type
	.byte	0x0a, 0x80, 0x40, 0x61          # Value
	.byte	0x07, 0x80, 0xff, 0xff
	.byte	0xff, 0xff
	.asciz	"ENUM_B"                        # Name
	.p2align	2, 0x0
```

But the test is expecting a different bytes:

```
; ASM:        .short  4359                    # Record kind: S_CONSTANT
; ASM-NEXT:   .long 4101                    # Type
; ASM-NEXT:   .byte 0x03, 0x80, 0x40, 0x61  # Value
; ASM-NEXT:   .byte 0x07, 0x80
; ASM-NEXT:   .asciz  "ENUM_B"                # Name
; ASM-NEXT:   .p2align  2
; ASM-NOT:    .asciz "S::SEnum"             # Name
```

There's also more problems if you remove the first test and let the second test run.

**Comment by augusto2112** [comment]
@drodriguez thanks, I'll take a look

**Pull request merged**
