### PR TITLE
cherry-pick FileManager fixes

### PR DESCRIPTION
**Pull request by marcrasi**
It would be nice to have these fixes in swift/master because they fix some segfaults in our internal Swift tests.

I've never cherry-picked something into swift/master before, so let me know if I should be doing it differently or if I shouldn't be doing this at all! Thanks :)

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@marcrasi these should be cherry-picked to apple/stable/20190619. `swift/master` accepts LLDB changes only.

**Comment by marcrasi** [comment]
Thanks! I rebased it onto `apple/stable/20190619`.

**Comment by marcrasi** [comment]
@swift-ci please test

**Review by lastthyme — APPROVED** [review]

**Pull request closed without merging**
