### PR TITLE
[CMake] Add missing dep when building with BUILD_SHARED_LIBS

### PR DESCRIPTION
**Pull request by davezarzycki**

### CODE REVIEW

**Comment by davezarzycki** [comment]
@swift-ci please smoke test platform

**Comment by davezarzycki** [comment]
@swift-ci please smoke test platform

**Comment by davezarzycki** [comment]
Okay, I think I did everything correctly. APINotes is an Apple only thing. I'm not sure why Apple's version of clang's Index library is different.

Do we not support CI testing for `apple/master`?

**Review by compnerd — DISMISSED** [review]

**Comment by compnerd** [comment]
I think that this should be submitted to `apple/stable/20190619`

**Comment by davezarzycki** [comment]
I'm still confused about Apple's branch scheme. Why is this change wrong for `apple/master`? Why `apple/stable/20190619` and not `apple/stable/20191106`?

EDIT – And why did you mark this pull request as being approved when the comments suggest otherwise?

**Comment by compnerd** [comment]
@davezarzycki - you are asking the right questions!  I feel the same way.  My understanding, which I admit may be incorrect, is: the current swift/master branch is an integration branch based on apple/stable/20190619.  Changes are applied to that branch, go through testing and if everything passes, gets merged into swift/master.   The apple/master branch is tracking llvm/master I believe.

As to the incorrect marking - that was a side effect of not being fully awake, sorry about the confusion.

**Comment by hyp** [comment]
@davezarzycki It looks like this needs to be submitted to both apple/master (that merges into swift/master-next, and thus is important for Swift's master-next branch), and then cherry-picked to apple/stable/20190619 (that merges into swift/master, and thus is need for Swift's master branch). Is our branching guide document helpful:
https://github.com/apple/llvm-project/blob/apple/master/apple-docs/AppleBranchingScheme.md
?

**Review by hyp — APPROVED** [review]
LGTM. Please cherry-pick to apple/stable/20190619 as well.

**Pull request merged**
