### PR TITLE
[Monorepo fixup] Reset lld contents in the swift/master branch to mat…

### PR DESCRIPTION
**Pull request by hyp**
…ch apple/stable/20190619

The monorepo conversion for the swift/master branch brought in contents in
untracked directory that landed after the apple/stable/20190619 branch was cut.

This commit fixes this content by resetting the sub-trees to match apple/stable/20190619.

Here's how this commit was contructed:

Step 1: reset the subtrees to match the apple/stable/20190619 state

repos="debuginfo-tests libclc libcxxabi libunwind lld llgo openmp parallel-libs polly pstl"

for repo in $repos
do
  git rm -rf $repo > /dev/null
  latest_commit=$(git rev-list HEAD -n1 -- $repo)
  tree=$(git rev-parse origin/apple/stable/20190619:$repo)
  git read-tree --prefix=$repo $tree
  echo "LATEST COMMIT FOR $repo -p $latest_commit"
done

Step 2: construct an octopus merge commit with new subtrees

tree=$(git write-tree)
git commit-tree -p HEAD -p ... -m "[Monorepo fixup] ..." $tree

### CODE REVIEW

**Comment by dexonsmith** [comment]
@hyp , is lld the only thing that's wrong, or is it all of the untracked directories?  If the latter, I'd rather fix them all at the same time.

**Comment by hyp** [comment]
> @hyp , is lld the only thing that's wrong, or is it all of the untracked directories? If the latter, I'd rather fix them all at the same time.

There's probably more, I need to check.

**Comment by dexonsmith** [comment]
> > @hyp , is lld the only thing that's wrong, or is it all of the untracked directories? If the latter, I'd rather fix them all at the same time.
> 
> There's probably more, I need to check.

Yeah, I think the problem is that LLDB branched later, and implicitly brought in a ton of other content in the untracked directories.

**Comment by dexonsmith** [comment]
> > > @hyp , is lld the only thing that's wrong, or is it all of the untracked directories? If the latter, I'd rather fix them all at the same time.
> > 
> > 
> > There's probably more, I need to check.
> 
> Yeah, I think the problem is that LLDB branched later, and implicitly brought in a ton of other content in the untracked directories.

You can get the content from apple/stable/20190619/start, although I don't see that tag on llvm-project.  Did you forward the tags yet from llvm-project-v5?

**Comment by hyp** [comment]
@dexonsmith Fixed up.

**Comment by dexonsmith** [comment]
> @dexonsmith Fixed up.

I checked the tree and confirm it looks right.  I'm not sure about having all those parents; it seems cleaner to just have a simple merge commit to the most recently already-merged apple/stable/20190619, which has the same tree.

**Comment by dexonsmith** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by dexonsmith** [comment]
@hyp we'll have to ignore the test failure:
```
17:26:09 + python /Users/buildnode/jenkins/workspace/apple-llvm-project-pr-macos/swift-ci/jobs/pull-request/check_changed_files.py
17:26:09 ERROR: File debuginfo-tests/nrvo-string.cpp is not allowed to be changed directly on swift/master
```

Let me know what you think about parents.  I could be convinced that this giant octopus is the right thing, but it adds a lot of noise to `git log --graph` so I still think just re-merging from apple/stable/20190619 sets a better balance.

**Comment by dexonsmith** [comment]
I put up my proposed alternative as https://github.com/apple/llvm-project/pull/16

**Comment by hyp** [comment]
Closing as #16 did it.

**Pull request closed without merging**
