### PR TITLE
Sema: add support for `__attribute__((__swift_private__))`

### PR DESCRIPTION
**Pull request by compnerd**
This attribute allows declarations to be restricted to the framework
itself, enabling Swift to remove the declarations when importing
libraries.  This is useful in the case that the functions can be
implemented in a more natural way for Swift.

This is based on the work of the original changes in
https://github.com/llvm/llvm-project-staging/commit/8afaf3aad2af43cfedca7a24cd817848c4e95c0c

Differential Revision: https://reviews.llvm.org/D87720
Reviewed By: Aaron Ballman

### CODE REVIEW

**Comment by compnerd** [comment]
Upstream Review: https://reviews.llvm.org/D87720

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by JDevlieghere** [comment]
@vsapsai Do we have a bot that runs this branch in CI or is there only PR testing? The failure seems pretty unrelated to that test.

**Comment by JDevlieghere** [comment]
> @vsapsai Do we have a bot that runs this branch in CI or is there only PR testing? The failure seems pretty unrelated to that test.

Found it right after I commented here, of course :-) `LLVM.Assembler.disubprogram.ll` is failing there too (in run #10773).

**Comment by compnerd** [comment]
Merging this to unblock further work.  This is a pre-application of a change destined for llvm.org, to aid with merge conflict resolution.

**Pull request merged**
