### PR TITLE
[Swift] Replace calls to FuncDecl::getName & EnumElementDecl::getName with ValueDecl::getBaseIdentifier

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
for apple/swift#30606

### CODE REVIEW

**Comment by jckarter** [comment]
Please test with following pull request:

apple/swift#30606

@swift-ci Please test

**Comment by AnthonyLatsis** [comment]
Ok, so there's at least one new call site.

**Comment by AnthonyLatsis** [comment]
@jckarter Could you trigger the tests once again please?

**Comment by AnthonyLatsis** [comment]
apple/swift#30606

@swift-ci Please test

**Comment by AnthonyLatsis** [comment]
Never mind, TIL CI permissions are cross-repository. Leaving the simultaneous merge to you.

**Comment by jckarter** [comment]
apple/swift#30606

@swift-ci Please smoke test

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
