### PR TITLE
[lldb] Add test to check that we can resolve self even if there are no references to it in a dynamic context

### PR DESCRIPTION
**Pull request by augusto2112**
Depends on https://github.com/apple/swift/pull/34835.

@adrian-prantl @vedantk

### CODE REVIEW

**Review by vedantk — APPROVED** [review]

**Comment by vedantk** [comment]
We'll need to merge this into the `next` branch as well -- no need to put up a separate PR, I'll do the cherry-pick after this lands.

**Comment by vedantk** [comment]
@swift-ci test

**Comment by vedantk** [comment]
Looks like the runtime reporting for exclusivity violations has changed. lldb will need to be fixed before we can merge.

**Comment by augusto2112** [comment]
Hi Vedant, do you think this is mergeable now? I'm having some weird issues with my system, and I can't build swift atm, so I wasn't able to test locally.

**Comment by vedantk** [comment]
@swift-ci test

**Comment by vedantk** [comment]
To github.com:apple/llvm-project.git
   dba05ab259dc..581bdb330bed  swift/next -> swift/next

**Pull request merged**
