### PR TITLE
Reduce the amount of daemon in clang-cas tests

### PR DESCRIPTION
**Pull request by cachemeifyoucan**

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci test linux platform

**Comment by cachemeifyoucan** [comment]
@swift-ci test linux platform

**Comment by akyrtzi** [comment]
This reduces our test coverage, we should at least pull out to separate test files that only run on `darwin`.

**Comment by cachemeifyoucan** [comment]
> This reduces our test coverage, we should at least pull out to separate test files that only run on `darwin`.

Those are either duplicated tests just running under `cache-build-session`, which I think it totally unnecessary, where the function of `cache-build-session` should be covered in other tests. `cache-build-session` will cause a new daemon to spawn every time.

Or the other one is just repeat the same tests done with inline, which we can keep. But in general, `inline` and `daemon` are going down the same path for depscanning. The code path doesn't diverge for the function that the tests are trying to cover.

**Comment by akyrtzi** [comment]
> Those are either duplicated tests just running under cache-build-session, which I think it totally unnecessary, where the function of cache-build-session should be covered in other tests

The intention of these `RUN`s is to test the daemon, and using `cache-build-session` is a convenient means for that, it's not the intention to test `cache-build-session` itself.

> But in general, inline and daemon are going down the same path for depscanning.

The daemon has separate code where it sets up the dep-scanning mechanism, separate from the inline path; essentially we need test coverage for the `cc1depscand_main()` function.

**Comment by cachemeifyoucan** [comment]
> > Those are either duplicated tests just running under cache-build-session, which I think it totally unnecessary, where the function of cache-build-session should be covered in other tests
> 
> The intention of these `RUN`s is to test the daemon, and using `cache-build-session` is a convenient means for that, it's not the intention to test `cache-build-session` itself.

Using `clang-cache` is fine but `cache-build-session` will force a new long-running daemon every time.

> 
> > But in general, inline and daemon are going down the same path for depscanning.
> 
> The daemon has separate code where it sets up the dep-scanning mechanism, separate from the inline path; essentially we need test coverage for the `cc1depscand_main()` function.

We only need to cover daemon launch code in some tests test targeted to test daemon. While it probably makes no difference when it comes to testing error serialization.


I have a separate patch to force each daemon only run one command and quit. If you think it is better that way, we can go that route too.

**Comment by cachemeifyoucan** [comment]
Other way to do that: https://github.com/apple/llvm-project/pull/5219

**Comment by akyrtzi** [comment]
> We only need to cover daemon launch code in some tests test targeted to test daemon. While it probably makes no difference when it comes to testing error serialization.

I admit that testing the daemon with error serialization was perhaps unnecessary but `depscan-prefix-map.c` specifically tests that [the prefix mapping flags are propagated to the daemon](https://github.com/apple/llvm-project/blob/a9e334915b75b1839f02cd3102e1480c21c4ae40/clang/tools/driver/cc1depscan_main.cpp#L960) as expected, and in general I'd prefer that we err on the side of unnecessary testing instead of not enough testing.

> I have a separate patch to force each daemon only run one command and quit. If you think it is better that way, we can go that route too.

Seems like a great idea to me!

**Pull request closed without merging**
