### PR TITLE
[lld/test] Remove a downstream test config that is not needed

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
rdar://125632860

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Review by rintaro — APPROVED** [review]

**Comment by rintaro** [comment]
Looks safe. Force merging to unblock bots.

**Comment by drodriguez** [comment]
Was this rewritten out of the history of `stable/20230725` after it landed? I cannot find it in the branch anymore.

**Comment by cachemeifyoucan** [comment]
> Was this rewritten out of the history of stable/20230725 after it landed? I cannot find it in the branch anymore.

https://github.com/apple/llvm-project/pull/8507/commits/255ab881036ea620ab43116012eda90a97bce30e

**Comment by drodriguez** [comment]
Sorry, GitHub shows this in their UI in the middle of March 19th commits for some reason. I got a warning in a rebase script about this commits being gone from the branch. I don't understand what might have happened.

**Pull request merged**
