### PR TITLE
CAS: Stop duplicating on-disk result cache in-memory

### PR DESCRIPTION
**Pull request by dexonsmith**

### CODE REVIEW

**Comment by dexonsmith** [comment]
@swift-ci test

**Comment by dexonsmith** [comment]
@swift-ci test

**Comment by dexonsmith** [comment]
Failures in https://ci.swift.org/job/apple-llvm-project-pr-linux/3270/ are in compiling `lld` (@cachemeifyoucan, were you already aware of them?). Pushing anyway.

**Comment by cachemeifyoucan** [comment]
> Failures in https://ci.swift.org/job/apple-llvm-project-pr-linux/3270/ are in compiling `lld` (@cachemeifyoucan, were you already aware of them?). Pushing anyway.

You are not rebased onto TOT right? I think TOT doesn't have that ICE on gcc.

**Comment by dexonsmith** [comment]
> > Failures in https://ci.swift.org/job/apple-llvm-project-pr-linux/3270/ are in compiling `lld` (@cachemeifyoucan, were you already aware of them?). Pushing anyway.
> 
> You are not rebased onto TOT right? I think TOT doesn't have that ICE on gcc.

Aha; I had assumed that swift-ci did a merge with ToT before running tests. I'll be careful to do that myself in the future.

**Pull request merged**
