### PR TITLE
[clang][modules][deps] Cherry-pick explicit modules commits

### PR DESCRIPTION
**Pull request by jansvoboda11**
This PR cherry-picks upstream commits motivated by implicitly discovered, explicitly built Clang modules.

### CODE REVIEW

**Comment by jansvoboda11** [comment]
@swift-ci please test

**Comment by dcci** [comment]
@swift-ci please test

**Review by dcci — APPROVED** [review]
LGTM. This should fix an assertion we're seeing in rdar://problem/102119326 (cc: @fredriss)

**Comment by artemcm** [comment]
Any chance we can also include https://github.com/apple/llvm-project/commit/060b25346b95cc161d21418f31c333f9a115d77e?

**Comment by jansvoboda11** [comment]
That commit already is in the target branch: 35515c92be06aef1c8bfa147e6429b9b60eb2317.

**Comment by artemcm** [comment]
> That commit already is in the target branch: [35515c9](https://github.com/apple/llvm-project/commit/35515c92be06aef1c8bfa147e6429b9b60eb2317).

Ah. I was looking it up by hash. Thank you!

**Comment by porglezomp** [comment]
I believe some Swift fixes came in recently that might unblock this
@swift-ci please test

**Pull request merged**
