### PR TITLE
[llvm-cov] Fix lcov coverage report contains functions from other compilation units.

### PR DESCRIPTION
**Pull request by keith**
Summary: Patch by Chuan Qiu (@eagleonhill).

Reviewers: Dor1s

Reviewed By: Dor1s

Subscribers: lebedev.ri, llvm-commits

Tags: #llvm

Differential Revision: https://reviews.llvm.org/D63571

llvm-svn: 364653
(cherry picked from commit 176b9f651685c52bce25e700a758bd33e6a5354d)

### CODE REVIEW

**Comment by keith** [comment]
Related https://forums.swift.org/t/llvm-cherry-pick-for-swift-5-2-branch/32837

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
Hey Keith, thanks for working on this. Cherry-pick from llvm.org should go on the `apple/stable/20190619` branch, they'll get auto merged into the `swift/swift-5.2-branch`. Can you please change the target branch?

**Comment by keith** [comment]
Updated!

**Comment by compnerd** [comment]
@swift-ci please test

**Review by vedantk — APPROVED** [review]

**Comment by keith** [comment]
Thanks!

**Pull request merged**
