### PR TITLE
[lldb] Show --lldb-use-system-debugserver in readme

### PR DESCRIPTION
**Pull request by kastiglione**
Most people will likely want to build and test using the system debugserver.

### CODE REVIEW

**Review by jimingham — COMMENTED** [review]
I thought we preferred people run lldb/scripts/macos-setup-codesign.sh and then they can use the debugserver they built?  Might at least mention that as an option.

**Comment by atrick** [comment]
> I thought we preferred people run lldb/scripts/macos-setup-codesign.sh and then they can use the debugserver they built? Might at least mention that as an option.

This is all from one build-script invocation. Would the build-script need to run that automatically then?

**Comment by kastiglione** [comment]
> I thought we preferred people run `lldb/scripts/macos-setup-codesign.sh` and then they can use the debugserver they built?

I'm not sure what we prefer, but I will update the readme to mention the relationship between the flag and the script.

**Comment by jimingham** [comment]
That script creates the code signing cert which subsequent build will use.  Until the cert expires, you don't need to run the command again.

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test

**Comment by kastiglione** [comment]
@swift-ci test macOS

**Pull request merged**
