### PR TITLE
[next] Cherry-pick missing commits from stable/20210726

### PR DESCRIPTION
**Pull request by bnbarham**
I found these while going through commits for stable/20211026 and noticed they weren't on next, but seem like they should be.

### CODE REVIEW

**Comment by kastiglione** [comment]
+1 for 96eb53601bcacfcfb1df5c4e3d02f0ea8b84d532

**Comment by etcwilde** [comment]
+1 for `a0423cc`.

**Comment by compnerd** [comment]
+1 for the other two remaining changes.

**Review by compnerd — APPROVED** [review]

**Review by etcwilde — APPROVED** [review]

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Failure is caused by a method removed in 7e6df41f655e51c984b92bbd9c19a6fb851f35d4. I'll fix that separately, these commits are all needed in next so going to merge anyway.

**Pull request merged**
