### PR TITLE
[6.0][Tests] Fix broken clang-deps-scan tests after link-libraries are added

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Explanation: Test only change to fix clang unit test
Scope: Fixing tests on swift 6.0 branch
Reviewer: @artemcm 
Original PR: https://github.com/apple/llvm-project/pull/8857
Risk: Test fix

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please test

**Review by nkcsgexi — APPROVED** [review]

**Comment by cachemeifyoucan** [comment]
@nkcsgexi  ping for merging.

**Comment by cachemeifyoucan** [comment]
ping!

**Comment by bnbarham** [comment]
Thanks @cachemeifyoucan 🙇‍♂️

**Pull request merged**
