### PR TITLE
Cherry pick "Expose DWARFDIE::GetDeclContext()"

### PR DESCRIPTION
**Pull request by adrian-prantl**
The only purpose of this PR is to cherry-pick [Expose DWARFDIE::GetDeclContext() in lldb_private::Function.](https://github.com/apple/llvm-project/commit/5ef5e7f8606522f3782d7e334731afa288ebb811).
However, because of the many DWARF parser changes upstream I ended up cherry-picking a bunch of dependencies that help reduce the risk for merge conflicts and make it easier to cherry-pick more changes in the future.

### CODE REVIEW

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
@swift-ci test windows

**Comment by adrian-prantl** [comment]
ping @JDevlieghere @bulbazord

**Review by JDevlieghere — APPROVED** [review]
🚢

**Pull request merged**
