### PR TITLE
[lldb][PECOFF] Exclude alignment padding when reading section data

### PR DESCRIPTION
**Pull request by hjyamauchi**
[Second try]

There can be zero padding bytes at a section end for file alignment in PECOFF. Exclude those padding bytes when reading the section data.

This fixes the spurious "unable to load module" and "error: AST validation error" messages in lldb on windows.

Cherrypick https://reviews.llvm.org/rGe9040e875d9252f726c41579f70663154718c3c6

### CODE REVIEW

**Comment by hjyamauchi** [comment]
CC @compnerd

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
Closing this in favour of https://github.com/apple/llvm-project/pull/7189.  I think that its better to just cherry-pick the two changes from upstream for ARM64/CHPE rather than trying to adjust in slightly different ways.

**Comment by hjyamauchi** [comment]
I guess I was a bit too late. Sorry for the trouble. Thanks for the fix!

**Comment by SharonXSharon** [comment]
Hi, will this be merged to main branch? We are still seeing the test failure of `tools/yaml2obj/COFF/xrelocs.yaml` without this pull request being merged on main branch.

**Comment by compnerd** [comment]
@SharonXSharon do you have logs that I could take a look at?  https://github.com/apple/llvm-project/pull/7189 is merged into stable/20221013.

**Comment by SharonXSharon** [comment]
@compnerd the error we are seeing is as follows:
```
llvm/test/tools/yaml2obj/COFF/xrelocs.yaml:33:20: error: CHECK-YAML-NEXT: expected string not found in input
# CHECK-YAML-NEXT: SizeOfRawData: 16
                   ^
<stdin>:9:49: note: scanning from here
 SectionData: '00000000000000000000000000000000'
                                                ^
<stdin>:10:2: note: possible intended match here
 Relocations:
 ^

Input file: <stdin>
Check file: /llvm/test/tools/yaml2obj/COFF/xrelocs.yaml

-dump-input=help explains the following input dump.

Input was:
<<<<<<
           1: --- !COFF 
           2: header: 
           3:  Machine: IMAGE_FILE_MACHINE_AMD64 
           4:  Characteristics: [ ] 
           5: sections: 
           6:  - Name: .data 
           7:  Characteristics: [ IMAGE_SCN_CNT_INITIALIZED_DATA, IMAGE_SCN_LNK_NRELOC_OVFL, IMAGE_SCN_MEM_READ ] 
           8:  Alignment: 16 
           9:  SectionData: '00000000000000000000000000000000' 
next:33'0                                                     X error: no match found
          10:  Relocations: 
next:33'0     ~~~~~~~~~~~~~~
next:33'1      ?             possible intended match
          11:  - VirtualAddress: 0 
next:33'0     ~~~~~~~~~~~~~~~~~~~~~
          12:  SymbolName: foo 
next:33'0     ~~~~~~~~~~~~~~~~~
          13:  Type: IMAGE_REL_AMD64_ADDR64 
next:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          14:  - VirtualAddress: 8 
next:33'0     ~~~~~~~~~~~~~~~~~~~~~
          15:  SymbolName: bar 
next:33'0     ~~~~~~~~~~~~~~~~~
           .
           .
           .
>>>>>>
```
I think the error is because the `llvm/lib/ObjectYAML/COFFYAML.cpp` file is not merged/picked correctly in the original commit/merge?

**Comment by hjyamauchi** [comment]
I realize that the COFFYAML.cpp change wasn't in #7189 and I think we need to reapply the cherrypick on top of #7189. Will do this.

**Comment by hjyamauchi** [comment]
This reapplies the cherrypick: https://github.com/apple/llvm-project/pull/7218

**Pull request closed without merging**
