### PR TITLE
[cherry-pick] [lldb] Support frame variable for generic types in embedded Swift

### PR DESCRIPTION
**Pull request by augusto2112**
[lldb] Change embedded swift test to use "clean" doubles

    (cherry picked from commit 75a08e36298018cb6cddcca92f9faf26679d0394)

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
Original PR: https://github.com/apple/llvm-project/pull/8267

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci smoke test

**Comment by augusto2112** [comment]
@swift-ci test windows

**Comment by augusto2112** [comment]
@adrian-prantl I added the nfc commit you asked to change the test to use check_variable here

**Review by adrian-prantl — APPROVED** [review]
Thanks!!

**Comment by augusto2112** [comment]
@swift-ci test Windows

**Pull request merged**
