### PR TITLE
[lldb] Make ReadCStringFromMemory default to read from the file-cache.

### PR DESCRIPTION
**Pull request by augusto2112**
Differential Revision: https://reviews.llvm.org/D118265

(cherry picked from commit b414954a5f1c2f8f6adecf20e5a433dfbc320cc2)

### CODE REVIEW

**Comment by augusto2112** [comment]
@swift-ci test

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Comment by augusto2112** [comment]
Besides the cherry-pick, I added a second commit so we don't read from the file-cache when we didn't resolve the address ourselves:

    [lldb] Force live memory if we can't read from the file-cache

    Now that reading C strings go through the file-cache by default, make
    sure that any calls that come from LLDBMemoryReader force live memory
    when we can't read from the file-cache. This is the case when:
    - The LLDB setting marks it as disabled.
    - The target is 32 bits (this may be subject to change).
    - The address we're reading from is not one of the fake addresses we
      resolved in LLDBMemoryReader.

**Comment by augusto2112** [comment]
@swift-ci test

**Review by adrian-prantl — APPROVED** [review]

**Comment by augusto2112** [comment]
@swift-ci test macOS

**Pull request merged**
