### PR TITLE
[Clang][ScanDeps] Add C API and implement enough to build Foundation.

### PR DESCRIPTION
**Pull request by Bigcheese**
This adds an experimental C API to `clang-scan-deps` and implements enough to build the Foundation module and everything it depends on. See individual commit messages for details.

### CODE REVIEW

**Comment by Bigcheese** [comment]
@swift-ci please test

**Review by dexonsmith — APPROVED** [review]
I'm fine with this being on apple/master temporarily, as long as we continue to push forward on getting this reviewed at llvm.org in parallel.

**Comment by Bigcheese** [comment]
Test failure was due to non determinism in the output. Fixed by sorting file-deps in the C API.

@swift-ci please test

**Comment by Bigcheese** [comment]
I was not able to reproduce the previous test failure. Trying again.

@swift-ci please test

**Comment by Bigcheese** [comment]
I was able to confirm that the failing tests were already failing on master, and aren't related to this change.

**Pull request merged**
