### PR TITLE
[lldb] Update TestSwiftAvailability.py to use lldbplatformutil.getArchitectu…

### PR DESCRIPTION
**Pull request by shahmishal**
…re()

### CODE REVIEW

**Review by adrian-prantl — APPROVED** [review]
Thanks, this should work!

**Comment by adrian-prantl** [comment]
We'll need to cherry-pick to the `next` and `stable/20240723` afterwards.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
next: https://github.com/swiftlang/llvm-project/pull/9336
stable/20240723: https://github.com/swiftlang/llvm-project/pull/9337

**Pull request merged**
