### PR TITLE
[move-keyword] Update move tests to use the keyword form instead of the function form.

### PR DESCRIPTION
**Pull request by gottesmm**
NFC.

### CODE REVIEW

**Comment by gottesmm** [comment]
This is the lldb part of this apple/swift#60404

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/60404

@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/60404

@swift-ci test

**Review by atrick — APPROVED** [review]
LGTM

**Review by adrian-prantl — APPROVED** [review]

**Comment by gottesmm** [comment]
Swift syntax PR: https://github.com/apple/swift-syntax/pull/563

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/60404
https://github.com/apple/swift-syntax/pull/563

@swift-ci test

**Pull request merged**
