### PR TITLE
Disable driver tests on macosx that are currently disabled on darwin

### PR DESCRIPTION
**Pull request by ahatanaka**
macosx and darwin in triples are equivalent.

rdar://124246653

### CODE REVIEW

**Comment by ahatanaka** [comment]
@swift-ci please smoke test

**Comment by ahatanak** [comment]
@swift-ci please smoke test macOS

**Comment by ahatanak** [comment]
@swift-ci please test macOS

**Comment by ahatanaka** [comment]
@swift-ci smoke test macOS

**Comment by ahatanaka** [comment]
@swift-ci test Linux

**Comment by ahatanaka** [comment]
@swift-ci test macOS

**Pull request merged**
