### PR TITLE
[clang][deps] Cherry-pick recent API changes

### PR DESCRIPTION
**Pull request by artemcm**
https://github.com/apple/llvm-project/pull/7128/ But for `stable/20230725`

### CODE REVIEW

**Comment by artemcm** [comment]
@swift-ci test

**Comment by artemcm** [comment]
@swift-ci test

**Review by jansvoboda11 — APPROVED** [review]

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
I've done this https://github.com/apple/llvm-project/pull/7212 using the conflict resolutions from next

**Pull request closed without merging**
