### PR TITLE
Backport REPL changes for Swift REPL completion fix

### PR DESCRIPTION
**Pull request by Teemperor**
Those are the non-swift changes for #679

Pavel's commit is a back port. The change to the REPL interface is a commit I'll push tomorrow and the fix for the CompletionRequest is a new commit for this branch (as I already deleted the wrong code upstream).

### CODE REVIEW

**Comment by dcci** [comment]
@fredriss has to approve this.

**Review by dcci — APPROVED** [review]

**Review by JDevlieghere — APPROVED** [review]
Thanks!

**Comment by Teemperor** [comment]
@swift-ci test

**Comment by dcci** [comment]
@Teemperor are these commits upstream, and then cherry-picked? Doesn't look like it.

**Comment by dcci** [comment]
[except for Pavel's]

**Comment by Teemperor** [comment]
Now the PR has:
* Backport from Pavel's commit.
* My own change to CompletionRequest that isn't a backport as the code upstream is already deleted.
* Backport of the REPL API change that I just pushed and now back ported.

**Review by fredriss — APPROVED** [review]

**Comment by fredriss** [comment]
@swift-ci test macOS

**Comment by Teemperor** [comment]
Alright, I'll merge this now and then check on the automerger and let's see how that goes.

**Comment by fredriss** [comment]
Please make sure to take those on the new stable branch

**Pull request merged**
