### PR TITLE
Cherry-pick: [GlobalISel] Ensure that translateInvoke adds all successors for inlineasm

### PR DESCRIPTION
**Pull request by ahoppen**
Cherry-pick 3eabcda81453854677faa70ae20f41e1a483cfe2 to stable/20210726 to fix test failures tracked by rdar://84477340.

---

The existing code didn't add all necessary successors, which resulted in
disjoint basic blocks. These would end up not being legalized which, in the
best case, caused a fallback only in assert builds.

Here's an example:

https://godbolt.org/z/ndx15Enfj

We also end up getting weird codegen here as well.

Refactoring the code here allows us to correctly attach all successors. With
this patch, the above example gives correct codegen at -O0 with and without
asserts.

Also autogen the testcase to show that we add all the successors now.

Differential Revision: https://reviews.llvm.org/D113437

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@bnbarham Would we also need to cherry-pick this to `stable/20211026`?

**Comment by bnbarham** [comment]
Seems likely, thanks (merged in https://github.com/apple/llvm-project/pull/3596)

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
